### ISSUE TITLE
Decide final package name (resolved: org.jspecify.annotations)

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#1]
Some considerations:

* Should it be under any existing known organization, or register a new domain and use reverse-domain naming, or just stake out a new top-level package?

* Should the idea of being annotations-only be built into the name?

* Should it be a "boring" prosaic descriptive name, or something more codenamey?

* Finally, what should be the dang name :-)

**Comment by cpovirk** [comment]
I wasn't around for many of the early discussions about the package name, but I want to make at least a weak case in _favor_ of [the "overstructuring" of putting the nullness-specific annotations in a subpackage](https://github.com/jspecify/jspecify/issues/1#issuecomment-506016706):

One question that we've considered (such as briefly in [this text](https://docs.google.com/document/d/16pPBoejDZJa2iz9HeAIh7GShyWOJNTYRN5_6P9xhAgw/edit#heading=h.hhojnf8gl3k5) and at slightly more length in some comment threads) is how much of our specification should go in Javadoc versus how much should go in some separate document. If we decide that we want to put a lot of the spec into Javadoc, then where would it go? Neither `@Nullable` nor `@NullAnnotated` nor any other single annotation will be the ideal place for treatment of all the questions we'll need to answer -- substitution rules, glossary entries, etc.

Maybe this is primarily an argument in favor of writing a separate spec, rather than squeezing everything into Javadoc. But if we do want the information in Javadoc, then it seems like it would fit best in a `package-info` file for a package _specific to nullness_.

**Comment by cpovirk** [comment]
(While I believe it's possible to include arbitrary .html files in the output of Javadoc, I suspect that they aren't as easily visible from IDEs, etc. Then again, I'm unsure how easily visible rendered *package-info* files are from IDEs :))

**Comment by kevinb9n** [comment]
Breaking it down, we have these lingering questions:

* Should the top-level package be
   * dev.jspecify 
      * concern that `dev` sounds like "under development" (contrast to stable)
      * also it is a top-level package most people haven't seen in java code before
   * org.jspecify and we make jspecify.org the canonical web site address instead of the redirect
      * fwiw, google may have some policy about dev being the one true domain to use now
   * jspecify by itself
      * perhaps ironic for a project for creating a standard to not care about standards

* Should we have deeper structure within the annotations package for say nullness
   * Let's decide no for now, there will be time to restructure before release.

* Is it `annotation` or `annotations`
   * [Precedent](https://stackoverflow.com/questions/4963300/which-notnull-java-annotation-should-i-use) is split
   * `java.lang.annotation` isn't a guide, since it doesn't contain annotations

**Comment by kevinb9n** [comment]
If no strong opinions emerge I am proposing we go with `org.jspecify.annotations`.

**Comment by kevin1e100** [comment]
I guess I'd be partial to dropping the trailing `s` to save a letter, otherwise LGTM

**Comment by lazaroclapp** [comment]
Vote in favor of `org.`, no opinion on the `s`.

**Comment by abreslav** [comment]
`org.` looks good, no opinion on the `s`.

**Comment by cpovirk** [comment]
Slight preference for including the `s`:

- I like differentiating from `java.lang.annotation`, since, as you note, that one _doesn't_ include annotations.
- While I have only a small preference when it comers to the _package_ name, I have a slightly larger preference for the _jar_ (and maybe _artifact_?) name. I guess it feels better to me to have a jar "of annotations" than a jar "of annotation?" And if we use plural for the jar, then I think it makes sense to follow suit for the artifact, package, and module. See also ~2x as many ["annotations" artifacts](https://search.maven.org/search?q=a:annotations) as ["annotation" artifacts](https://search.maven.org/search?q=a:annotation) in Maven Central.

**Comment by kevinb9n** [comment]
Clearly we could go either way. Let's make the call for
org.jspecify.annotations at this time.

**Comment by cpovirk** [comment]
As noted in #160, we've changed course to `org.jspecify.nullness` for nullness annotations, with other packages to be named as we create them.

**Comment by kluever** [comment]
Just to close the loop, the final decision that shipped in [JSpecify v1.0.0](https://jspecify.dev/blog/release-1.0.0/) was [`org.jspecify.annotations`](https://jspecify.dev/docs/api/org/jspecify/annotations/package-summary.html).
