### ISSUE TITLE
Common pattern for a set of exclusive scope-annotations (e.g. null-marked and null-unmarked) [working decision: sibling named annotations]

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#109]
A "cascading" annotation is one which we allow to be applied at (some subset of) these granularities: module, package (flat), top-level class, nested class, or method/constructor/field; and it applies to all code within that scope. So, there should never be a semantic distinction between applying it to, say, a package rather than to every individual top-level class inside that package (except for what happens when you create a new class!).

Our requirements around incrementality will make it important that such an annotation can be placed on a broad scope but still overridden/counteracted/negated at a smaller scope, recursively.

To learn what annotation semantics are in effect for a given piece of code, one should always search "outward" from that code to each successive containing construct until the first matching annotation is found, then stop.

Note that as you search outward, it may be a *set* of annotations that you are searching until you find any one of. For example, in the *current* Error Prone annotations, to learn whether a method has the property that ignoring its return value is a likely bug, one searches outward until hitting either `@CheckReturnValue` OR `@CanIgnoreReturnValue`, but once either is found, one can definitively stop searching.

Three use cases I currently have in mind happen to be binary (either on or off, nothing else). I'll list the *positive* formulation of each, not the negative formulation (i.e. that which should be assumed when no annotation was found at all).

* must use return value
* nullness defaults are in effect
* parameter names are published API

Assuming for the sake of argument that we eventually support these three, it would be preferable to support them in a consistent way. 

I can see two main options:

Option A. A single annotation with a `boolean value`. Here, `true` should represent the positive formulation and `false` the negative formulation (defined above). Either we should consistently not have a default value, or consistently use `true` as the default value (since for `false` you would _typically_ just not use the annotation at all). To learn which meaning is in effect for a piece of code, there is one single annotation to search outward for, and its value of true or false is all you need to know.

Option B. A pair of annotations (as illustrated above with the current Error Prone approach). They should be linked by a meta-annotation such as `@NegatedBy` or `@NegationOf`. They'll be in the same compilation unit so the link could be made in both directions, but we do still want a way to recognize which is the positive sense (distinct from unannotated code) and which the negative. So we would either withhold the annotation in one direction, or actually use _both_ `@NegatedBy` and `@NegationOf`. To learn which meaning is in effect for a piece of code, you need to know both annotations to search for, and search outward until either is found. And, technically, we should meta-meta-annotate the negation annotations as shown in #101, whereas in option A it is taken care of naturally by javac.

Which option to favor?

A makes the job of writing and specifying annotations like `@MustUseReturnValue` cleaner and easier. It gives a more accurate impression when one looks at the surface area of our annotation library; you won't see what look like two separate concepts, just one. A also seems to extend more cleanly to ternary or even more stateful annotations; the attribute space just enlarges from a boolean to an enum or something more complex (I would still encourage that each smaller-scope annotation *completely* override the information from the broader scope, but we're getting afield).

B gives you the freedom to choose a nicely tailored wording for the negative annotation instead of being stuck with `@PositiveSense(false)`.  "May ignore return value" is probably a little easier to parse than "Must use return value? No!"  (That said, the need to decide on both sets of terms, the "use" and the "ignore", which users would have to try to remember, isn't necessarily great.)

Other arguments?

**Comment by cpovirk** [comment]
> Option A. A single annotation with a `boolean value`.

I think at least _part_ of @kevin1e100 's [objection](https://github.com/jspecify/jspecify/issues/87#issuecomment-575293496) was the use of a boolean specifically. How would you feel about a 2-element enum (since you mention the possibility of larger enums)? I'm not sure how much that would actually help, but it gives us more naming flexibility than "true" and "false."

> Option B. A pair of annotations (as illustrated above with the current Error Prone approach). They should be linked by a meta-annotation such as `@NegatedBy` or `@NegationOf`. They'll be in the same compilation unit so the link could be made in both directions, but we do still want a way to recognize which is the positive sense (distinct from unannotated code) and which the negative.

Can you say more about why it's important to _programmatically_ link the two and tag one as "positive?" I would expect for any tool that understands them to be willing to hardcode that knowledge. (I grant that there's _some_ value in not having to hardcode it, but compared to implementing the actual semantics of nullability, etc., implementing "NullAnnotated is the opposite of "NotNullAnnotated" is trivial :))

(I suppose that an Option C is to recognize a particular convention like `@NullAnnotated` and `@NullAnnotated.Disable`, but I don't see anything in particular that that buys us.)

**Comment by kevinb9n** [comment]
Yeah, I've been pushing us primarily toward *having* standardized behaviors that can span various annotation domains, but yes, also specifically for encoding those as meta-annotations.

Some reasons

* It provides the information to both tool implementors and to users (via javadoc) in a consistent way.
* Seems to make it more likely that we'll stay consistent with that pattern in future annotation work.
* Users will have similar situations with their own annotations as well, and if they use our meta-annotations we'll be driving the world toward more standardized annotation practices.

It's always a dangerous thing to try to generalize too much from the start. There are ratholes to fall into; it's just that I think it's better to be good at pulling *out* of ratholes once they reveal themselves as ratholes than being afraid to ever set foot in.  And you know, once we fire nullness in the kiln it will already be too late.

**Comment by kevinb9n** [comment]
Re: enums, my understanding is that we want to try to avoid them when we can, because they make a harder compile-time dependency?

**Comment by cpovirk** [comment]
Ah, thanks, I think we have [a similar discussion about enum-valued annotations in another thread](https://github.com/jspecify/jspecify/issues/50#issuecomment-520468335), which I had forgotten.

**Comment by mernst** [comment]
My quick gut reaction is to prefer option B for its nicely tailored wording.

**Comment by kevinb9n** [comment]
Small point Chris mentioned about Option B: you *could*, if you wanted to, allow one annotation to be used at a finer granularity than the other. You probably wouldn't want to on net balance but the option is there.

**Comment by kevinb9n** [comment]
Btw, for the record. I'd say that "@CanIgnoreReturnValue" doesn't have "nicely tailored wording". it just has "tailored wording" :-); in other words, I personally found it to be a burden that we had to settle on two different verbs (or find some contortion to avoid it).

**Comment by kevin1e100** [comment]
+1 on option B for nullness in particular.  An enum-valued option A can work as well but I don't see that as a great fit for nullness either.  A boolean is in my opinion inappropriate for nullness.

The reason is that I'd want to challenge the premise that nullness in particular is necessarily "binary", as witnessed by the configuration options in existing defaulting annotations (Eclipse, Checkerframework).  Even if we start out with two modes I'd like to not be painted into a corner, and I don't think it's very obvious what `@SomeNullnessDefaultAnnotation(false)` is meant to mean.  An enum-valued annotation can avoid these issues, though with potential issues if we ever want to have additional attributes.  I'm not convinced there's compiler issues with using an enum, but it also is lengthy to type; marker annotations are just more compact and read better.

**Comment by cpovirk** [comment]
I think I would feel bad if we ever needed more than 2 "modes": We have generally been down on per-project customization for treatment of, say, bounds.

That said, I wouldn't rule out all customizations out of hand. Still, if we go to support some other customization, do you think our design options are a lot different if we have `@NullExplicit` and `@NotNullExplicit` as opposed to `@NullExplicit` and `@NullExplicit(false)`?

One possibility is that the customization is orthogonal. Then we might make it its own annotation. That seems to work OK under either approach.

Another possibility is that the customization is closely tied to null-explicitness. In that case, I'm still not sure how much the different approaches affect things. Then again, I'm having a hard time coming up with an example customization that really makes sense. Anything I think of, like `@NullExplicit(except = {FIELDS})`, raises a lot of questions once you start putting opposing annotations on nested scopes. Again, that's true regardless of our approach.

**Comment by cpovirk** [comment]
Despite all that, I do feel somewhat better about `@NullExplicit` and `@NotNullExplicit`, based primarily on the argument that `@NullExplicit(false)` may not be obvious to readers. I don't worry about that _too_ much because `@NullExplicit(false)` may be moderately rare. However, if we extend the pattern to other domains, we might see negations more often in those domains -- like `@MustUseResult(false)`. (And maybe that example is even more confusing, since users might think it somehow has to do with the cases in which the method returns `false` or something??)

But I'm conflicted. It's one thing to add 2 annotations instead of 1 for nullness. It's another thing to add 2<i>n</i> annotations instead of <i>n</i> for <i>n</i> domains.

**Comment by cpovirk** [comment]
It's also just slightly sad to think that the boolean approach actually lets authors write _3_ things:

- `@NullExplicit`
- `@NullExplicit(true)`
- `@NullExplicit(false)`

Of course the first two are equivalent, but someone is going to write the second one, anyway, and readers may scratch their heads just briefly.

Not to mention that authors can actually write 2 more:

- `@NullExplicit(value = true)`
- `@NullExplicit(value = false)`

And those would be especially odd for readers who don't know that "value" is a magic name to Java: What would it mean to be "null explicit for a value of true?"

All of this is very minor -- just tiny things to pile atop the "Must use return value? No!" concerns around booleans.

**Comment by kevin1e100** [comment]
Related observation in #35 ([here](https://github.com/jspecify/jspecify/issues/35#issuecomment-605670897)): Aliasing syntax `@Implies(Nullable.class)` only really works with marker annotations.

**Comment by donnerpeter** [comment]
BTW this will interact with aliasing feature: when going upward searching for some set of annotations, that set should include all aliases. And if complementary annotations refer to each other, their aliases should probably do as well, and `@Notnull`-alias would probably be an opposite of the base `@Nullable`, which might complicate things.

**Comment by Maaartinus** [comment]
@cpovirk 
I guess, the five variants mentioned above (`@NullExplicit`, `@NullExplicit(true)`, `@NullExplicit(false)`, `@NullExplicit(value = true)`, `@NullExplicit(value = false)` are a simple job for something like checkstyle. I'd personally allow just the first and third ones and be done.

Using enums would make everything much longer, which is a pain, especially on parameters.

Using two different names is bad for beginners with poor English. It's also bad for grepping and other simple searches.

There's an option C: Use `@NullExplicit` and a nested annotation like `@NullExplicit.Off`. It's short, it avoids booleans and enums and it's friendly to non native speakers.

**Comment by kevinb9n** [comment]
The boolean option is getting pretty close to dead for me for the reasons discussed.

(Even if null-awareness does always remain N=2, I filed the bug in want of a "common" approach, so we might as well accommodate greater Ns.)

Separate annotations can be fine, and "ideally" a meta-annotation would capture their relationship. (That relationship being something like, "this set of annotations are all mutually exclusive, cascading, and can override each other".)

But meta-annotation or not, the names should be as clear as possible so that the relationship is evident.

To pair with `@NullAware` (for example), I see several nice advantages to each of `@NullUnaware` and `@NullAware.Disable` and am not sure which will prove best.

**Comment by kevin1e100** [comment]
> Using enums would make everything much longer, which is a pain, especially on parameters.

At least for nullness _defaulting_ (`@NullExplicit`/`@DefaultNonNull`, or whatever we call it) I don't see us allowing such annotations on method parameters, FWIW, but I suppose there could systems where that granularity could be useful.  `@NullExplicit(OFF)` also doesn't seem necessarily more verbose than `NullExplicit(false)`, though it'll of course depend on the enum names.

That said, enums in annotation values have raised usability concerns repeatedly at this point.  To summarize issues I seem to recall:
* they probably require an additional (static) import, which can be frustrating.
* there's scenarios where they can cause weird errors, specifically when additional enum constants are added in later versions of a Jar.  (This possibly makes them less evolution-safe than I would personally like to believe.)
* enum constant names can be long.

These may each not be that bad, but they do probably compound, and in any event it seems there's a fair amount of unease with using enums in annotations.

**Comment by kevin1e100** [comment]
Hesitantly, I'll throw out another idea that's pretty similar to `@NullAware.Off`:

`@OptOut(NullAware.class)`

(maybe `@Disable(@...class)`).

Logically, I should have concerns with both that and `@NullAware.Off`, as it's not clear to me that that can be anything but binary, and so it doesn't seem all that different, other than syntax, from `@NullAware(false)`.  I guess one benefit of `@OptOut(NullAware.class)` and `@NullAware.Off` is that it allows `@NullAware` itself to have configuration attributes.  While that may not be practical for nullness, it's probably useful flexibility to have in a general pattern.  But it seems like there are still potential pitfalls: If we ever wanted to introduce a 3rd default (e.g., the for-the-moment-rejected `@DefaultNullable` from #41) then it becomes very unclear how `@NullAware.Off` and `@DefaultNullable.Off` relate (just like with `false`).

Nonetheless I'm probably warming up to having a standard solution that's limited to binaries: we just have to be judicious to only apply it where we're reasonably sure we won't need a 3rd option.  And the fact that we may be able to allow configuration knobs is at least mildly helpful, as in a pinch we may be able to encode a later-discovered 3rd option as a configuration knob.  (For instance, encode `@DefaultNullable` as `@NullAware(unannotated=Nullable.class)`, though this particular encoding is probably not really viable.)

Writing this also brings up a new concern with these patterns: what happens if there is no surrounding annotation to undo?  In other words: is it legal to annotate something `@NullAware.Off`, if there is no `@NullAware` on a surrounding scope?  The answer is probably that it's fine, not least to avoid weird "breaking at a distance" problems from removing annotations from surrounding scopes, but it is still odd.

**Comment by cpovirk** [comment]
Interesting, thanks. I don't remember any past discussion of `@OptOut(NullAware.class)`. A few thoughts:

- Users might accidentally apply it to the wrong class. Maybe they'd write `@OptOut(Nullable.class)` or `@OptOut(SomeTotallyUnrelatedThing.class)`. (We can of course try to catch this with validation, but it's always a bonus if illegal things are completely inexpressible.)
- It might not be possible to use with aliasing/implies: As [you noted above](https://github.com/jspecify/jspecify/issues/109#issuecomment-630517056), aliasing/implies might not support annotations that accept parameters. That said, we could have special support for the specific case of "opt me out" annotations, e.g., `@ImpliesOptOutOf(NullAware.class)`. (Not that I'd expect people to want to alias things to `@NotNullAware` specifically, since there probably aren't any existing annotations with comparable semantics for them to _want_ to alias. (Probably someone will try someday, but I'm not worried :)) But we can think ahead to `@MustUseResult`: Then, we may want to turn existing "opt me out" annotations like Error Prone's `@CanIgnoreReturnValue` into aliases for "opt out of `@MustUseResult`.")
- I don't remember any problems with `Class` values similar to the problems with `enum` values discussed previously. But if we wanted to use `Class` values, I'd want to look into it a little more.
- I'm unsure what to think of opting out of multiple things at the same scope. Would it be `@OptOut({Foo.class, Bar.class})`? Would it be `@OptOut(Foo.class) @OptOut(Bar.class)`? Would we support both? Are those better or worse than `@Foo.Off @Bar.Off` (or whatever our leading alternative would be)?

**Comment by cpovirk** [comment]
As for `@NullAware.Off` with no surrounding `@NullAware`: I think I agree that it's fine (with tools perhaps interested in issuing a very low-level warning/notice). That may still be something for us to keep in mind as we pick a name. But offhand, I don't think it rules out any of the proposed options (`@NullAware.Off`, `@NullAware.Disable`, etc.).

Jumping off on the specific term "disable": Would anyone ever think that `@NullAware.Disable` means "If you see `@NullAware` under this scope, ignore it?" I don't think that thinking would be _common_ -- and I'm not sure that our various alternatives are much better in that respect -- but maybe it's another naming point to keep in mind.

**Comment by cpovirk** [comment]
(As for the aside about annotations on individual parameters, I filed #128.)

**Comment by cpovirk** [comment]
One small thing to watch out for if we go with a pattern like `@NullExplicit.Off`: Will we end up with double negatives? `@NullExplicit.Off` is fine; `@DefaultNonNull.Off` would be slightly awkward.

I can't think of any other defaulting annotations in our future that would have "negative" naming, so maybe this isn't a big concern.

**Comment by cpovirk** [comment]
A few other points about `@Foo.Off` (or `@Foo.Disable` or `@Foo.Exempt` or `@Foo.Legacy` or `@Foo.Exclude` or whatever):

- It may sounds like it turns off _checking of code in that scope_ rather than _information about code in that scope_. That is, `@MustUseResult.Disable` may sound like "Don't run a MustUseResult checker on code in this scope," rather than "Don't require _anyone_ to use the result of methods declared in this scope."

- That said, it may be premature to generalize to a "common pattern" right now: If we can just name the annotations for nullness, that's the most important thing. And names like `@NullExplicit.Disable` probably don't have the problems of `@MustUseResult.Disable`. (Plus, it's even possible that we could someday find an alternative name for "MustUseResult" that doesn't have the problem, either.) On top of all that, we could argue that `@MustUseResult` is a slightly different case, since it has no associated _type_ annotation, and thus it's fine to have a separate pattern for it.

- It's _technically_ possible for someone to deep import a nested annotation, producing code that is just `@Disable class Foo {}`. But I can't see letting that factor into our decision.

**Comment by cpovirk** [comment]
Yet another possible complication is that we may want to offer a standard _`CLASS`-retention_ version of these annotations ([because Android has problems with `RUNTIME`-retention annotations if they are widely used](https://github.com/jspecify/jspecify/issues/28#issuecomment-766955882)).

I would assume that we would want to give that a different name (i.e., not just put it in a different package with with the same simple class name). We could consider either an entirely separate name (`@InTheClubNoRuntimeRetention`) or the same nesting approach discussed above (`@InTheClub.NoRuntimeRetention`). If we went with the former, we'd want to keep an eye on how unwieldy the name is. If we went with the latter, we'd probably want to avoid `@InTheClub.Exclude.NoRuntimeRetention` (or is it `@InTheClub.NoRuntimeRetention.Exclude`? :)).

**Comment by cpovirk** [comment]
Another possible variant of `@InTheClub` to add to [the one I just mentioned](https://github.com/jspecify/jspecify/issues/109#issuecomment-766976421): A variant that applies to `MODULE`, since the main `@InTheClub` [might not](https://github.com/jspecify/jspecify/issues/34#issuecomment-768379178).

(Perhaps we can kill two birds with one stone by offering just the standard `@InTheClub` (class retention, not applicable to `MODULE`) and the "enhanced but possibly dangerous" one (runtime retention, applicable to `MODULE`). Android users would likely be satisfied with the former. Most JRE users would, too, but if they wanted more, they could likely safely use the "enhanced" one. Once we bring multiple dimensions into it, though, I'm not sure we'll be able to find simple annotation names, whether we try to offer 2, 4, or what. Alternatively, we can leave defining aliases up to users, but that just means that each of _n_ users is stuck facing same problem....)

**Comment by kevinb9n** [comment]
If #127 is a "yes", as I think it is, then we will need to decide this soon.

* `@NullMarked` and `@NullUnmarked`?
* `@NullMarked` and `@NullMarked.Off`?
* `@NullMarked` and `@NullMarked(false)`?
* `@NullMarked` and `@Cancel(NullMarked.class)`?

I would like to take a pass at how we would do this for #200 as well before we lock anything in.

**Comment by sdeleuze** [comment]
I am tempted by `@NullMarked` and `@NullMarked(false)` since a boolean seems expressive enough for this kind of on/off toggle. Maybe an expressive attribute name could help. Maybe something like `@NullMarked(enabled = false)`?

**Comment by netdpb** [comment]
I think the least restrictive option we have is Option B (two separate annotations). That lets us name the negative annotation `@NotPositive`, `@Positive.Not`, `@Positive.Off`, or `@Negative` (an antonym).

I appreciate the problem for people with poor English, but I think just understanding a phrase like "null marked" will be a strictly harder problem for them in the first place, and then learning what "not null marked" means is a negligible amount of more difficulty.

For now, tools can hard code the pairs. Later, we can come up with meta-annotations that allow tools to recognize these pairs without hard-coding. If and when we come up with a reason to want an annotation with a boolean, or `@Cancel(Class)`, we can always decide to document those conventions so that tools can recognize them as well. That all seems not required for an initial release.

**Comment by sdeleuze** [comment]
@netdpb I am not sure to understand why a convention for negative annotation would be better than a boolean flag, could you please share your advice on this?

**Comment by netdpb** [comment]
I think other comments in this thread have mentioned some of the issues with a boolean argument. But here are a few from my perspective:
* It doesn't handle anything more complex than a binary choice (which I admit is hypothetical at the moment).
* It imposes a constraint on the name of the annotation. For example, there may be cases where the positive annotation has a name that is not simple to negate, as in the possible `@DefaultNotNull(false)`, which would include a double negative. Double negatives cancel each other out in some languages but not in others. Even in Standard English, which cancels, it may be unclear whether "default not null is false" means "the default is null" or "there is no default regarding null" or something else entirely. In that case something like `@NoDefaultNullable` or `@DefaultNull` might be clearer.

In any case, I'm saying a convention of having a separate annotation allows a lot of flexibility, including having that annotation be nested within the positive annotation, as in `@DefaultNotNull.Off` if that is what we think is most clear.

**Comment by sdeleuze** [comment]
Thanks for sharing. I tend to prefer solving the expressiveness issue with an explicit attribute name like `@DefaultNotNull(enabled = false)` rather than via nested annotation even if people will have the choice to use the short version. Let's maybe discuss that in a future meeting, I will try to convince some of you.

**Comment by kevinb9n** [comment]
As a working decision we are going with `@NullMarked` and `@NullUnmarked` for now. It is the most "down-to-earth" approach, I think.

One small note about having a parameter that negates the whole meaning is that it makes it tough to write a reasonable javadoc topic sentence for the annotation.

**Comment by netdpb** [comment]
Decision: We haven't formalized a common pattern, but our first example uses sibling annotations `@NullMarked` and `@NullUnmarked` without a repeatable naming pattern.
