### ISSUE TITLE
What is the nullness signature of a multiply-inherited abstract method?

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#110]
[EDIT: this whole comment is about case 1, where the method is abstract because all inherited methods are abstract.]

First consider a discrepancy in return types:

```
// in null-marked context

interface Foo { @Nullable String get(); }
interface Bar { /*non-nullable*/ String get(); }
interface Qux extends Foo, Bar {}
```

In this case, we can probably just follow Java's lead. With a quick experiment it seems that it won't just happily gin up an arbitrary intersection type, but if one of the types is more specific than the other (as should always be the case for us), it seems to go with that. (Or maybe I've gotten it wrong, but whatever it does, we can probably(?) stay consistent with.)

```
// in null-marked context

interface Foo { void accept(@Nullable String x); }
interface Bar { void accept(/*non-nullable*/ String x); }
interface Qux extends Foo, Bar {}
```

Here, Java is no guide, because any discrepancy in the types results in both overloads existing separately in `Qux` which we obviously can't mirror. (Or if they have the same erasure it just complains.)

It seems reasonable to go with the broader type; implementing `Foo` requires it to accept null, whereas `Bar` doesn't care whether it does or not. But is this tantamount to supporting contravariant nullness in parameter overrides, which we've said in #49 we don't intend to do?

**Comment by mernst** [comment]
For arguments, the broader type is the right choice.  This suggests we should permit formal parameter type contravariance.

**Comment by cpovirk** [comment]
Somewhat related to https://github.com/jspecify/jspecify/issues/67

**Comment by kevinb9n** [comment]
So we should choose the weakest contract that is no weaker than any supermethod's. Intersect the nullness of the return types, union the nullness of corresponding parameter types.

**Comment by wmdietlGC** [comment]
I think it should be the other way around: intersect the nullness of the parameter types and union the nullness of the return types.
Otherwise it would be possible to call a method that expects a non-null argument through an interface that permits null arguments; or, the other way around, invoke a method that returns null through an interface that promises a non-null return value.
Both would be unsound and can lead to NPEs.

The Checker Framework does not currently handle this correctly and I wrote up a small example [here](https://github.com/typetools/checker-framework/issues/2724#issuecomment-644469386).

**Comment by kevinb9n** [comment]
[Unrelated: I realize it might be confusing what *exactly* this bug is even asking. I think I mislabeled it as a "how to handle" question. It's just this: since the type `Qux` contains a member called `get`/`accept`, I want to be able to say _what the signature_ of that member is. Such that if I then overrode the methods with that exact signature, it would change nothing.]

Ah, Werner, I think your example is a different case: one inherited method is concrete, so the invisible method we are deciding the contract of is also concrete. That probably can be evaluated just as if the concrete method had been written in the subclass itself (which is what I ?think? your bug is asking CF to do).

I think that is probably a different case from mine above, where the supermethods are all abstract and so the method we are deciding the contract of is abstract. Someone will still have to implement the method, and when doing so will be "held" to the contract we decide on (whatever we decide that "held" actually means).

**Comment by wmdietlGC** [comment]
Sorry, yes, I had mis-read the example.
I agree that the effective signature in interface `Qux` should be the union of the parameter types and the intersection of the return types. That will ensure that any implementations of that method will fulfill all promises.

**Comment by kevinb9n** [comment]
Just realized we should de-emphasize "is concrete or abstract" and instead say "does it have an implementation", since that might have come from an interface default method, and it's a common source of confusion whether those are concrete or not, but for our purposes it should count.

Putting it together into a proposed resolution:

What is the nullness signature (the augmented types of each parameter and the augmented return type) of an inherited method?

* If the method has an implementation -- either because it is concrete in a superclass or because an appropriate interface default method will be used -- then the signature is exactly as given for that implementation.

* Otherwise form the signature using the intersection of each supermethod return type, and the union of each corresponding parameter type.

(Note that all supermethod signatures are seen post-substitution.)

**Comment by wmdietlGC** [comment]
Regarding when the method has an implementation, there are probably several distinct cases.

Relative to the problem I had before, in an example like:

```java
interface Foo { void accept(@Nullable String x); }
class Bar { public void accept(String x) { x.hashCode(); } }
class Qux extends Bar implements Foo {}
```

Method `accept` in `Qux` has the signature from `Bar`, because it has an implementation.
I would expect an error that class `Qux` does not implement interface `Foo`, because the parameter type of method `accept` is too narrow.
This is also related to #111 where we're discussing whether such narrowing errors should be of a different kind.

For default methods I'm not sure we have an issue with multiply-inherited methods. An example like this:

```java
interface Foo { void accept(@Nullable String x); }
interface Bar { default void accept(String x) { x.hashCode(); } }
interface Qux extends Foo, Bar {}
```

gives an error from javac: `Error: interface Qux inherits abstract and default for accept(java.lang.String) from types Bar and Foo`.

If I change to `class Qux implements Foo, Bar {}` javac gives: `Error: Qux is not abstract and does not override abstract method accept(@org.checkerframework.checker.nullness.qual.Nullable java.lang.String) in Foo`.

So `Qux` would need to be implemented as:

```java
interface Foo { void accept(@Nullable String x); }
interface Bar { default void accept(String x) { x.hashCode(); } }
class Qux implements Foo, Bar {
    public void accept(@Nullable String x) {}
}
```

and here the rule should be again that the union of the parameter types and the intersection of the return types should be used for `Qux.accept`. Otherwise, an invocation through `Foo` could violate the assumptions of the implementation in `Qux`.
So the fact that `Bar.accept` has a default implementation shouldn't have an impact on the signature in `Qux`.

Does that sound correct?

**Comment by kevinb9n** [comment]
> ```java
> interface Foo { void accept(@Nullable String x); }
> class Bar { public void accept(String x) { x.hashCode(); } }
> class Qux extends Bar implements Foo {}
> ```
> 
> Method `accept` in `Qux` has the signature from `Bar`, because it has an implementation. I would expect an error that class `Qux` does not implement interface `Foo`, because the parameter type of method `accept` is too narrow. This is also related to #111 where we're discussing whether such narrowing errors should be of a different kind.

I do think this case is exactly #111, in different clothing.


> For default methods I'm not sure we have an issue with multiply-inherited methods.

I think I agree? So to restate, then:

To find the signature of an abstract method inherited from multiple supertypes, use the intersection the supermethod return types, and the union of each set of corresponding parameter types.

I think we can resolve this.

**Comment by kevinb9n** [comment]
Of course, we can't express union or intersection types. Where we said "use the intersection of the supermethods' return types", I think we meant the glb; likewise lub for parameter types, with both being restricted to what we can express.

But we're also limited by what javac will allow: we can't change the base type at all.

I'm not sure we considered a case like this, where the nullness varies for a non-root type. What is the parameter type of `AB.foo`?

```java
// null-marked code
interface SuperA { void foo(List<String> bar); }
interface SuperB { void foo(List<@Nullable String> bar); }
interface AB implements SuperA, SuperB {}
```

The lub of these two types would be `List<? extends @Nullable String>`, but we can't do that.

If we are analyzing AB itself, we can say: "please override this method and choose which of the two signatures you want". (Of course, whichever way they choose they'd still get a warning about the other one.)

But what about when AB is a dependency?

One option is: the answer is `List<@Nullable String>`, with the reasoning that type parameters are *more* likely covariant than contravariant, so we might as well behave as though `? extends` *were* there.

So, throughout all components of parameter types, *except* those that actually use `? super` (which we can handle normally), we would use the "most nullable" of the types. For return types, the least nullable.

**Comment by kevinb9n** [comment]
Just to state that more directly: for this purpose only, treat wildcardless type arguments as if `? extends` is there. Would that resolve every case?

@cpovirk floated an intriguing alternative: the inherited method gets the parameter type `List</*nullness-unspecified*/String>`. This seems to make a lot of sense to me: in order to specify it, we needed them to provide an explicit override, and they didn't, so it's unspecified.

**Comment by kevinb9n** [comment]
TODO: check into what javac does with base types; write test-case-like code

**Comment by kevinb9n** [comment]
I'm not sure what I meant to learn from javac. If there's any variation in parameter types at all, it just gives an error -- we knew that! I guess what it does with return types is a bit illustrative:

```java
import java.util.*;

class Issue110 {
  interface A { List<? extends Integer> foo(); }
  interface B { List<? extends Number> foo(); }
  interface C extends A, B {}

  static {
    C c = null;
    List<? extends Integer> list = c.foo();
  }
}
```

This does compile. In other words, it's happy to go ahead and pick the more specific type. But this is just further argument justifying the *original* decision here from way back when. If I take out all the `? extends` it refuses to compile `C` at all. Again though, we knew this.

**Comment by kevinb9n** [comment]
As mentioned I will write out test cases, but they'll be...  long. We'd normally not wait to mark this issue resolved until we do that, unless anyone feels that we don't even understand what we're deciding yet without writing all that out.

**Comment by cpovirk** [comment]
I had forgotten about this one! :)

It is a _little_ weird that someone might write...

```java
interface Foo { @Nullable String passThrough(@Nullable String s); }
interface Bar { String passThrough(String s); }
interface Qux extends Foo, Bar {}
```

...and end up as if `Qux` had a signature like `String passThrough(@Nullable String s)`, which is presumably unsound.

In #67, I'd cited https://docs.oracle.com/javase/specs/jls/se12/html/jls-8.html#jls-8.4.8.4, which appears to match [kevinb9n's results](https://github.com/jspecify/jspecify/issues/110#issuecomment-1283169720). It's similar to our rule in that it picks the most specific return type.

But we go further by trying to perform a full on glb/lub of multiple types. For example, the JLS wouldn't "merge" `Iterable<? extends String>` and `List<? extends Object>` into `List<? extends String>`, but we're effectively trying to do that. But we can make that happen because we know that the base types match—well, [_mostly_](https://github.com/jspecify/jspecify/issues/110#issuecomment-1279468389).

Arguably a more JLS-like approach would be pick one of the _n_ signatures. Maybe it would make sense to pick the one with the more specific return type (since that's the part that the JLS allows to vary). Granted, even "more specific return type" isn't a well-defined concept: If we inherit both `@Nullable List<? extends Object>` and `List<? extends @Nullable Object>`, then neither is strictly more specific than the other. So we're back to glb/lub and possibly even unspecified nullness.

(Maybe ideally a checker that analyzes _that class_ would produce an error to get the programmer to resolve the conflict. But programmers can avoid any such error by suppressing or at least by not running a checker in the first place. So there's no getting around defining behavior for a checker that analyzes _usages_ of such a method.)

**Comment by cpovirk** [comment]
(I'm here because @kevinb9n just pointed out to me in chat that there's a related but separable issue: If `Qux` _declares_ some `passThrough(String)` method, then checkers should probably check it against _both_ of the supertypes' methods _separately_. The question of _this_ issue is what happens when there is no such declaration in `Qux`.)

**Comment by cpovirk** [comment]
Hmm, https://github.com/jspecify/jspecify/issues/110#issuecomment-1286168910 has me thinking more about unspecified nullness.

I've read the description there, and I'm not sure if it adds behavior beyond what glb/lub already does. I may be misunderstanding, though.

One possible goal could be to prefer to _ignore_ unspecified when we have "better" information:

```java
@NullMarked
interface Foo {
  void use(String s);
}

@NullUnmarked
interface Bar {
  void use(String s);
}

interface Qux extends Foo, Bar {}
```

There, the unspec rule from above and the glb/lub rule give us `void use(String*)`, I think? But we could instead say that the type is `void use(String!)`, since we have an affirmatively non-nullable type from `Foo`. Of course, someone could in the future annotate `Bar` with `@Nullable String`, in which case the type would become `String*` again because of the conflict. But maybe that's overall a better user experience, since the type probably is meant to be `String!`.

This spec-unspec mix may well be the most common kind of "conflict" that we'd see in practice, so we might want to err on the side of doing the "right" thing for it.
