### ISSUE TITLE
Casing of "jspecify" name

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#116]
Let's... try not to invest too much time in this...

I weakly propose that the official name of the project be "jspecify" and not "Jspecify" or "JSpecify" or "jSpecify". 

I think most users will encounter the name more often in import statements etc. than anything else, where the name will be all lowercase by established convention, so I just don't see much value in having a second style in other contexts.

I further propose that we explicitly not care whether people capitalize the "j" when used at the start of a sentence. (We are not the iPhone...)

If anyone feels that a different approach is significantly better and can explain why, please comment.

**Comment by mernst** [comment]
I proposed that we use normal English rules and call it Jspecify.
 * It is easier for people to understand, because it is not an exception to standard capitalization
 * It is how almost all other tools (e.g., Guava) are treated.

**Comment by kevinb9n** [comment]
That can work as well, we're just gonna need more people to weigh in.

**Comment by kevin1e100** [comment]
Here we go: I personally like "jSpecify" best, which Google docs at least doesn't seem to auto-correct at the beginning of sentences, unlike "jspecify".  I frankly like "jspecify" best for its visual balance (sticking down in front and back) but I don't think it's great in sentences, which I suspect goes back to Mike's point, and it's annoying to me to get different spellings and auto-corrections when starting a sentence.  While I want to support Mike's point, I have to admit that Jspecify to me parses especially poorly, and I suspect that's because it's not really a word, unlike "Guava", and it also looks especially unappealing to me (because it sticks up in the front and down in the back I think).  But, maybe jSpecify is a decent compromise, since it uses a capital letter where the actual word starts?

**Comment by wmdietlGC** [comment]
Just to get it out there, my ranking is:
1. "JSpecify" makes it much easier to parse for me. Also like "JRuby".
2. "jSpecify" for the resons @kevin1e100 gives above.
3. "jspecify" is simple.
4. "Jspecify" because autocorrect changes 3. into it.

**Comment by cpovirk** [comment]
I would like to preface this by saying that I can live with any of those 4 and that I want to err on the side of making this conversation shorter, rather than longer.

With that said: I was surprised not to see a "JSpecify" proponent until now. To my mind, that is the "standard" for names of the form "j" + "foo." Besides JRuby, I have heard of at least:

- JUnit
- JCommander
- JFreeChart
- JGraphT
- JGit
- JLine

There are certainly many exceptions (like jsoup), but many apparent exceptions are acronyms (like jOOQ), which isn't what we're doing here.

Consequently, I would expect for users to fairly commonly write "JSpecify" no matter what we say. (To be fair, I'm sure that at least one person will write *every* form no matter what we say :))

Granted, it's _possible_ that I just happen to have been exposed to more JFoo libraries and that other users will be more familiar with more jFoo, jfoo, or Jfoo libraries. But https://github.com/akullpp/awesome-java seems to overall lean toward JFoo (for what that's worth), and of course JUnit in particular is extremely commonly used.

**Comment by kevinb9n** [comment]
This last point seems strong to me. I suppose that my starting off with "jspecify" actually came from a streak of contrarianism.

**Comment by kevin1e100** [comment]
I can get behind "JSpecify". I like the symmetry of j and y but j can look
like other letters depending on font, so J is probably better/clearer
anyways.  Plus, my sense of symmetry probably isn't the deciding factor
here.

**Comment by kevinb9n** [comment]
I've reread everything here. I am comfortable pronouncing an official decision of JSpecify and any bitter complaints about that can be sent to me offline. :-)

That is a decision on how it officially appears in prose. As for how it should appear in code, of course the package name remains "jspecify", and the names of various identifiers (e.g. maven whatnot) should follow dominant conventions in that arena.

If we write, say, a test method that includes JSpecify in part of its name, a close reading of the Google Style Guide permits either `testJSpecifyCompliant` or `testJspecifyCompliant` and let's not have a big debate on that. :-)

We good?
