### ISSUE TITLE
Default nullness of type parameter bound in non-null-by-default context

### ISSUE THREAD

**Issue by dzharkov** [jspecify/jspecify#12]
\[TODO: direct link to doc about this issue\]

In the document, it's been said about `@DefaultNotNull`:
> This annotation establishes defaults for unannotated method parameters etc. in the annotated package or class/interface (but not sub-packages or subtypes) and matches CF’s defaults except for declarations of type variables without explicit bounds, which default to non-null in this proposal

Does it mean that generic (type) parameters have not-null bounds independently of the presence of `@DefaultNotNull` somewhere in the scope or have I just misread the statement?

**Comment by kevinb9n** [comment]
I've moved discussion of this issue into an editable document. It's a bit alarming that this one issue fills six pages, but well, at least it's organized/skimmable.

We invite review, comments, and even edits by all.
https://docs.google.com/document/d/1mD_wvJLiSvg7YOLcVTqZh303XktqO-S4vzQEgx-Gnts/edit

**Comment by kevinb9n** [comment]
We'll need more scrutiny of this doc before we ever make a final decision, but at this time we are closing issues when we have a "working decision", and I am very confident we've met the bar for that.  The implicitly-bounded `<T>` will have an upper bound of *non-nullable* `T`.

There is no need to stop making/suggesting edits to the document just because this issue is currently closed, and at some point it could even become clear we need to rethink it.

**Comment by netdpb** [comment]
**Current decision**: `T`'s upper bound is non-nullable in `@NullMarked class Foo<T>` and in `@NullMarked class Foo<T extends Object>`. (Those are identical in bytecode.) `Object` is not treated specially when it is a type parameter's upper bound.

**Argument for changing**: A bare, apparently unbounded type parameter has always meant effectively unbounded, and with the current decision that's no longer the case. Now to get an actually unbounded type parameter you have to do `@NullMarked class Foo<T extends @Nullable Object>`. That is awkward and is surprising. It is important to maintain the status quo that a plain type parameter is unbounded. In addition, IDEs like Eclipse have UIs that allow users to augment third-party code with extra annotations. In the case of `<T>`, there is no visible upper bound to annotate, and users will often want to annotate that upper bound.

**However,** if users have assumed that a plain type parameter always means it is unbounded, that has never even included nullness, so it's hard to say that introducing nullness will violate their assumption that those parameters can accomodate nullable types.

Since `class Foo<T>` and `class Foo<T extends Object>` are identical in bytecode, making this change would require JSpecify to treat even type parameters explicitly bounded by `Object` specially.

That would mean that unlike any other type parameter bound, `<T extends Object>` would have a nullable bound; you would have to do `<T extends @NonNull Object>` to get a non-null bound. That would also make JSpecify treat `Object` type usages differently when they appear as a type parameter bound, compared to all their other appearances.

Treating `Object` type parameter bounds specially (compared with other type parameter bounds and other type usages of `Object`) means this proposal complicates the JSpecify nullness model a lot, in a way that will affect lots of users. It will have to be carefully documented in the Javadoc, the specification, and other user documentation.

On the other hand, documenting the fact that plain type parameters are bounded by non-null `Object` is simpler, especially because it follows from the basic model of nullness.

The benefits of this special case are outweighed by the complexity costs.

**Timing**: This must be decided before version 1.0 of the jar.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.
