### ISSUE TITLE
Even smaller scopes for defaulting annotations: PARAMETER and TYPE_PARAMETER

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#128]
(This is not a priority at the moment. I just saw reference to it, so I wanted to capture it in an issue.)

I'm writing this issue under the assumption that defaulting annotations are likely to be permitted on _methods_ (#43) (though I suppose we could ask this issue's question regardless). This issue is about even smaller scopes that that.

Previously:

- https://github.com/jspecify/jspecify/issues/109#issuecomment-636291863 and https://github.com/jspecify/jspecify/issues/109#issuecomment-699726206 briefly mentioned the possibility of applying defaulting annotations to individual parameters.
- The following is not really the same thing, but: https://github.com/jspecify/jspecify/issues/87#issuecomment-682083940 suggested that a single annotation could act as both a defaulting annotation and a type annotation (though [I think that's probably not going to happen](https://github.com/jspecify/jspecify/issues/87#issuecomment-682089568)).

We could ask this question both about nullness specifically and about possible future annotation "domains." (But note that it makes sense only the case of _type_ annotations: Non-type annotations might well apply to `PARAMETER` or `TYPE_PARAMETER`, but I see them as a distinct case.)

I think the answer is probably "no" for `PARAMETER`. I think there's a more interesting case for `TYPE_PARAMETER`, so I wouldn't dismiss it out of hand. But it has downsides, too, and certainly I don't see it as a priority at the moment.

I had briefly been excited about `PARAMETER`: It seemed like a way to annotate an individual method parameter as "not nullable" without needing a `@NonNull` annotation. Sure, it's slightly inelegant (especially if the defaulting annotation has an awkward name) and slightly indirect, but it should pretty much do what people want. It's actually potentially nicer than `@NonNull` in some cases: First, you could write `@NullAware Map<Foo, Bar>`, and that would apply to all 3 components of the type. Second, you could write `@NullAware T`, and there wouldn't be a question of whether type that "projected" `T` to a non-nullable type or not.

But... I think this may lead users to think of the defaulting annotations as applying to a _type_ (well, really to a _tree_ of types). As a result, users might think they can put `@NullAware` on "the return type of" a method. \[edit: especially because many existing artifacts of nullness annotations use that location to apply to the return type!\] But in fact, `@NullAware` on a method is likely (#43) to apply to the entire method -- parameters included.

I think this is a good argument for putting defaulting annotations only on "scopes."

(A small part of me still wants to make an exception for `TYPE_PARAMETER`: It's much more distinct than the parameter-vs.-return case. And it's still potentially a handy way to annotate an individual type or two as non-nullable. But again, I don't know whether I'd want to push for this or not.)

**Comment by kevin1e100** [comment]
Ah yes, exempting a method parameter.  A related point here is that something like `Map<@NonNull String, @NullnessUnspecified List<@NonNull String>>` seems "weird": how could something inside an unspecified qualifier be specified?  I *think* it makes technical sense, though I'm unclear anyone would want to write this, or at least I'm unsure that's what they meant when they actually wrote:

```
@DefaultNonNull
void foo(Map<String, @NullnessUnspecified List<String>> bar) {...}
```

Did the author really mean for `List`'s type argument to be implicitly `@NonNull String`?  This is a reason why I have been liking the idea of not introducing `@NullnessUnspecified` as a type annotation, only relying on defaulting instead for that.

That is to say, assuming the author meant `@NullnessUnspecified List<@NullnessUnspecified String>`, it would arguably be clearer if the author had no choice but to write `@DefaultNullnessUnspecified List<String>` (modulo annotation name).

Still, allowing defaulting annotations in locations like that seems to run counter to the idea of allowing them on (some kinds of) "scopes": there is no scope in the Java scope nesting sense when using a default annotation as a type annotation.  Method parameters and type parameters likewise I don't believe constitute a scope, and because of a similar concern I believe we had tentatively ruled out default annotations on fields (where I see a stronger case personally).

**Comment by cpovirk** [comment]
Thanks for mentioning `FIELD`. That got me to look for the past issue about it. It was #50, and I see that it actually covered `PARAMETER`, too. Oops! It did at least conclude by suggesting that `FIELD` is best discussed in conjunction with `METHOD` and `CONSTRUCTOR` in #43, so maybe we'll take it back up then.

(Do we have an issue yet for "Should we have a `@NullnessUnspecified` annotation?" I know that we're figuring that we'll approach the remaining annotations more holistically, but we may want an issue, too, to at least start collecting history.)

**Comment by cpovirk** [comment]
As for `PARAMETER` itself: I just left [a related comment about Java's forthcoming "records" on #43](https://github.com/jspecify/jspecify/issues/43#issuecomment-700277489).

**Comment by kevinb9n** [comment]
I would very much like to have a clear line between type-use annotations and scope annotations.

`@NullMarked` should just be a scope annotation (module, package, class, method, constructor).
`@Nullable` should be just a type-use annotation.

What would it take for us to decide this?

**Comment by cpovirk** [comment]
It seems moderately unlikely that we would support these scopes. (I'm now thinking that `TYPE_PARAMETER` is _particularly_ unlikely, but it looks like I've gone back and forth on this.)

It seems overwhelmingly unlikely that we would support these scopes _until_ we support `METHOD` and `CONSTRUCTOR` scopes (#43).

But we should at least _consider_ `PARAMETER` scope _at the same time as_ we consider `METHOD` and `CONSTRUCTOR` scopes, given the discussion of record components.

Maybe that still lets us close this issue with the understanding that we may reopen it when we talk about #43? Again, I don't think anyone has been pushing for it to happen _before_ then.
