### ISSUE TITLE
Addressing cases like the AtomicReference zero-param constructor

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#145]
@wmdietlGC and I were talking about `AtomicReference`. We see ~3 ways to annotate it:

1. All APIs operate on `@Nullable T`. (Then, for the declaration of `T`, we employ whatever pattern we prefer for [parameters that want nothing to do with nullness](https://github.com/jspecify/jspecify/issues/78).)

2. All APIs operate on plain `T`. `T` is declared to be [definitely nullable](https://github.com/jspecify/jspecify/issues/85). "Definitely nullable" is a feature that JSpecify may not support, at least initially, so this option would require additional support from tools.

3. All APIs operate on plain `T`. `T` is declared to permit both nullable and non-nullable type arguments.

The problem with (3) is the no-arg `AtomicReference` constructor. It creates an instance whose value is null, even if `T` is a non-nullable type:

```java
AtomicReference<String> ref = new AtomicReference<>();
ref.get().hashCode(); // NPE
```

So we might end up going with (1) for now. But (1) is annoying because it provides _no way_ for JSpecify to know that `get()` returns a non-nullable value -- even if the user passed a non-null value to the constructor and never set the value to null.

So we might like (3). That could take the form of:

- banning that constructor entirely (requiring users to write `new AtomicReference<>(null)` if that's what they want)
- some way to restrict instantiations of a constructor (https://github.com/typetools/checker-framework/issues/1330) -- and perhaps of calls to a method, too (currently available in CF but not in our immediate plans for JSpecify)

(This problem does not exist with static factory methods, since we already provide a way to set bounds there.)

A "`@DoNotCall`" annotation is something that [we could do someday](https://docs.google.com/document/d/1n0YVmuQplIxf9FijKwVr_8MYPtshKCJ6hwFnV-d4pdA/edit#heading=h.51rkvyufkgmu) (and something we've found useful [in Error Prone](https://github.com/google/error-prone/blob/master/annotations/src/main/java/com/google/errorprone/annotations/DoNotCall.java)), so maybe this is just our first issue to request that. Or maybe there's something nullness-specific here that we'd want to do.

**Comment by cpovirk** [comment]
This could hypothetically be nice for Guava's [`UncheckedExecutionException`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/util/concurrent/UncheckedExecutionException.html): It would be nice if users could assume that `getCause()` returns a non-null value. But to guarantee that, we'd need to not only annotate the constructors' `cause` parameters as non-null but also ban usages of the constructors that don't accept a `cause`.

**Comment by kevinb9n** [comment]
I'm gonna treat this issue as being about The Interesting Case Of `AtomicReference`, rather than the general topic, if that's okay.

#3 seems worth trying for. The fact it at least stops you from actually _setting_ a nullable reference is useful: then if an unexpected null does happen, it's easier to conclude that the setting code probably never ran, instead of wondering whether maybe _that_ expression was itself unexpectedly null.

If our hypothetical API owner agreed with that, then ideally they could proceed to make a design choice between options like:

1. Null is the default value, so the read methods will all project to `@Nullable T` and all users will just have to deal with that case.
2. Null is the default value, but all those projections will be a pain for users so let's just lie instead. <-- I think we all agree that we should discourage this in strong terms.
3.  There should be no default value, so what the no-arg constructor really produces is an _uninitialized_ instance. We can't deprecate that, so this class becomes another example of an API with a sequencing contract ("must use at least one write operation (including 1-arg constructor) before any read operation").

The last one leads to an interesting question: suppose the user A _breaks_ the sequencing contract (for example because they don't have tools that know how to enforce it!), and user B uses the class correctly. The read methods can be annotated sensibly for user A (nullable) or user B (non-nullable), but we have to choose.

**Comment by kevin1e100** [comment]
FWIW another example for this is `ThreadLocal` I believe

**Comment by kevinb9n** [comment]
3B seems to kind of put AtomicReference itself into the same category as "fields" and "array components". All 3 have this initialization problem.

**Comment by kevinb9n** [comment]
So my proposal is that we use`AtomicReference<T extends @Nullable Object>` and we just add this class to the list of "things we have initialization concerns about". Does anyone feel we need to keep this open?

**Comment by kevinb9n** [comment]
Came across this again; wrote up https://github.com/jspecify/jspecify/wiki/nullness-borderline-cases#the-atomicreference-case
