### ISSUE TITLE
InstanceOfCheck.java sample

### ISSUE THREAD

**Issue by amaembo** [jspecify/jspecify#164]
I'm trying to check how samples behave in IntelliJ IDEA. I'm only at the beginning of this work and see tons of problems on the IDEA side, but this one looks dubious to me:

```java
  Object x1(@NullnessUnspecified Object o) {
    if (o instanceof Object) {
      return o;
    } else {
      // jspecify_nullness_not_enough_information
      return o;
    }
  }
```

Here, IDEA is smart enough to know that if `o instanceof Object` is false, then `o` is definitely `null`, so it reports `// jspecify_nullness_mismatch` instead of `// jspecify_nullness_not_enough_information` in the `else` branch. I would agree with IDEA here. If you want to assert that 'not instanceof' branch preserves original nullness, then it's probably better to check against a more specific type, not Object.

**Comment by cpovirk** [comment]
Thank you!

I am excited to hear that you're looking at JSpecify in IntelliJ. (One of these days, I want to write up a doc about why I think that IDE support is a huge benefit to JSpecify. I'd like to convince some people inside Google to take an interest in it, too.)

For this sample, I agree that we should switch to a more specific type. I will take care of that. I will also see if we have similar samples that exercise `x == null`. If we do, I will see if they expect a mismatch from dereferencing in that branch. If we don't have such samples, we probably should. And I should see what our own prototype checker does in that case, too.

**Comment by cpovirk** [comment]
Yes, there are other samples that I should update. For example:
https://github.com/jspecify/jspecify/blob/cafb9fc30d1689b37e0a85cedd0d71cbff834655/samples/NullCheck.java#L32-L37

I guess this raises questions about what to do with cases in which the object is already "known" to be non-null _before_ the null check. It's probably better to trust the result of the null check, since that definitely happens at runtime, rather than assuming that a "non-null" parameter is really non-null (since the caller might not run a null checker and thus might pass `null`).

**Comment by cpovirk** [comment]
Oddly enough, I have a sample just like the one above but with the cases switched (because we test `== null` instead of `!= null`). In that case, I do have the code written to expect a mismatch:

https://github.com/jspecify/jspecify/blob/cafb9fc30d1689b37e0a85cedd0d71cbff834655/samples/NullCheck.java#L58-L61

Certainly the two samples should be consistent :) And I should fix the prototype, which does not handle this correctly, to do so.

**Comment by amaembo** [comment]
Thank you for fixing this. It looks like InstanceOfMethodCheck has the same issue (IDEA knows semantics of Object.class.isInstance, so it understands that only null doens't pass this check).

**Comment by cpovirk** [comment]
Oh, thank you again. I'm surprised that I even added such a sample to the repo, since we're generally trying to avoid relying on knowledge of specific methods. (So usually, I keep such samples private for my own testing.) I'll remove it when I have a moment.
