### ISSUE TITLE
System.out nullness?

### ISSUE THREAD

**Issue by amaembo** [jspecify/jspecify#174]
`System.out` is a final field that is initialized to `null` by default. Also, it could be changed to `null` via `System.setOut(null)` call later, so having a check like `if (System.out == null)` in the code is not completely unreasonable. So should it be marked as 'unspecified' or 'not-null' by default? If 'unspecified', then every `System.out.println` call will be warned in strict mode.

**Comment by cpovirk** [comment]
I don't know that I'd realized that `setOut(null)` would actually overwrite the value of `System.out`. Fun :)

I have 3 thoughts:

- In [a post today on another question about a JDK method](https://github.com/jspecify/jspecify/issues/176#issuecomment-780138500), I said that I'm hoping we don't need to decide the nullness of any JDK APIs before 1.0. However, my post is far from the final word on that question. Plus, even if we do choose to wait to make a decision, I think it's perfectly fine to start discussions now\[*\]. That's especially true when those discussions illustrate larger issues, as your example does here. So I'll continue by talking about what I would envision we would do someday in the future:
- For `setOut(null)`, I think we can take the following position: Even though `setOut(null)` executes successfully at runtime, we would not want to allow it. This is similar to how we wouldn't want to allow users to add `null` to an `ArrayList` whose element type is "non-null string": Yes, the call would execute successfully at runtime (because `ArrayList` has no null check). But if our type system allowed the call, it would prevent us from offering a guarantee to users -- namely, the guarantee that they can have a type "`ArrayList` whose element type is non-null string," which is different from "`ArrayList` whose element type is _nullable_ string" because our type system keeps nulls out. (Yes, all guarantees go away if anyone suppresses nullness errors or just plain doesn't run a checker. That's an unavoidable problem, though I grant that it's worse for a static field like `System.out` that _anyone_ can access.)
- For `public static final PrintStream out = null;`, I don't have as clear a picture. I do think it's pretty clear that, as long as "normal users" can't ever see that null value, we'd want `out` to be treated as non-null. Sure, if someone were to run one of our checkers over `System.java`, then the checker might well require a suppression for that assignment. Ideally, the code would be restructured to call a `static native` method and assign the result of that directly (if possible). But sometimes a field is left `null` for longer, yet it's always filled in before "users" see it. Then it's less clear to me what to do. The place to get into those details is probably https://github.com/jspecify/jspecify/issues/39, to which I know you've contributed.

(And for what it's worth, the Checker Framework [considers `System.out` to be non-null](https://github.com/typetools/jdk/blob/a267c2766c87d8335a13f698f0dc80627c8e86cd/src/java.base/share/classes/java/lang/System.java#L154) and [does not let users call `setOut(null)`](https://github.com/typetools/jdk/blob/a267c2766c87d8335a13f698f0dc80627c8e86cd/src/java.base/share/classes/java/lang/System.java#L217).)

\[*\] If we start having a _lot_ of discussions about JDK APIs, then we should find a different place for them so that they don't overwhelm all the other discussions. But I don't think we've reached that point yet. If others disagree, though, please let me know. I haven't surveyed all our issues to see how many such discussions we've had.

**Comment by kevinb9n** [comment]
(I actually don't see this as a question about a JDK API; the API is just a case study to see whether our spec and guidelines are complete. So I think it does belong here, and "overwhelm" could be handled via labels if needed.)

First I will cop to having pleaded many times for the design anchor to be "these are just types, and we're just designing a type system." That would seem to argue that `System.out` _has to_ be nullable (like a number that could oh-so-rarely go up to 2^31 _has to_ be a `long`).

But it's just an anchor, anchors sometimes drag you down. The point of departure is that the Java type system's goal is soundness and ours explicitly isn't. We have some freedom to make pragmatic trade-offs.

Now that I think of it, this seems fairly similar to the `Object.toString` case. It _could_ be null, but if it is, we're always gonna complain and say that someone screwed up. So I still think we might as well write the "aspirational" type that the field intends to live up to, even knowing that it can sometimes fail.

**Comment by kevinb9n** [comment]
I think I'm gonna backpedal on that "EDIT" I just made. 

The gray area I'm pondering:

(1) It is technically *possible* that this method could return `null`, or reading this field could give `null`
(2) Yet in the general case of calling this method or reading this field, it is *wrong* for it to be `null`.

Since the beginning I've felt that the highest purpose for the annotations is to document *developer intent* -- because that is precisely the piece that cannot be observed any other way.

But that says to me that it is that *wrongness* of part (2) that is the important thing to capture. And wrongness involves a judgment call.

* If I feel "it really is wrong for someone to return `null` from an `Object.toString()` override", then I will want to not mark the `Object.toString()` return type nullable.
* If I feel "it's normal enough for `O.tS()` to return `null`, then perhaps I will.

Would this represent a failure of our specification?

**Comment by kevin1e100** [comment]
So for `System.out` we have the simple and consistent option to annotate
both it and `setOut` such that they use non-null output and input,
respectively.  That's internally consistent, should be safe, and
practical.  The Javadoc (
https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#setOut-java.io.PrintStream-)
doesn't seem to indicate whether null should be allowed or not, so even if
setting null doesn't break anything, there's no reason to think it's
intentionally allowed?

For `toString()` I feel that non-null is the "better" return type for it.
I'm sure there are existing `toString` implementations out there that
return null, but that's technically ok, since that will be in "unspecified
nullness" code.  However, if we wanted to allow null returns (i.e.,
annotate `Object.toString()`'s return type as `@Nullable` , I think that
would be doable too (especially since `@NullMarked` annotated subclasses
would still have to return a non-null string unless they repeat
`@Nullable`), and would have the advantage that any checker would force you
to null-check `toString` return values. I'm just not convinced that
returning null is an intended thing for `toString` implementations to do.
In any case, `Object.toString()`'s annotations are a question of intent; I
don't see a technical constraint that would force one way or the other.

**Comment by kevinb9n** [comment]
Wait a bit... have I just been confused? Now I'm thinking, if these two APIs are both straight up non-nullable:

* it's good that attempting to set System.out to null (by either means) will error
* it's good that trying to return null from toString() will error
* the unexpected runtime exception on read that I've been worried about.... that can only happen if there was some unanalyzed (or suppressed) code involved, right? And did we not agree a few times that we can't worry about those kinds of cases, they're "all bets are off"?

Okay. But now what am I missing *this* time? :-)

**Comment by kevin1e100** [comment]
I think that's right. By "exception on read" I believe you're referring to dereferencing `System.out` (or the return value of `toString()`) after it evaluated to `null`. And yes, assuming the JVM initializes that field to a non-`null` value, and assuming `setOut` is specified to require non-`null` arguments, then only unanalyzed or suppressed code calling `setOut(null)` can cause exceptions on read.  Those exceptions may unfortunately occur _later_ in _analyzed_ code, but that's universally the case, for better or worse. (Unless we had tooling that inserted "eager" null checks before unchecked `setOut()` call sites, as I believe the Kotlin compiler or something like @wmdietl's Granullar would.)

**Comment by kevinb9n** [comment]
(slight adjustment: even if the JVM doesn't initialize it non-null, if user code has no reasonable chance to observe it before it gets made non-null, that should be enough)

**Comment by kevinb9n** [comment]
I think (?) we've all been clear on what to do here for a while.

The intention that should be represented is that `out` is non-nullable.

Bad things can happen that break that expectation. But _they are bad_, and making it non-nullable makes that clear.

**Comment by netdpb** [comment]
**Current decision**: `System.out` can be marked non-null.

**Timing**: This decision is not required for JSpecify 1.0.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.
