### ISSUE TITLE
@MyFavoriteDefaults @ButNotThisOne

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#216]
Sorry, I haven't come up with a good title :) The title would be something like "Can I annotate a class with an annotation _and_ with an annotation that implies (among other things) its opposite?" But that sounds like a clear "no," so I'll elaborate, and maybe it will _still_ be a clear "no."

Background 1: "Clearly" the following is bogus: `@NullMarked @NotNullMarked class Foo {}` (somewhat related: https://github.com/jspecify/jspecify/issues/100, https://github.com/jspecify/jspecify/issues/101)

Background 2: Ideally the following is also bogus: `@NullMarked @MyAliasForNotNullMarked class Foo {}`

But: What if I want to annotate all my classes (or packages or modules) with `@MyFavoriteDefaults`, an annotation that [implies a bunch of my favorite annotations](https://github.com/jspecify/jspecify/issues/213): `@NullMarked`, ["`@NotVoidable`,"](https://github.com/jspecify/jspecify/issues/200) "`@PublishParameterNames`" -- all the finest annotations JSpecify 1.31.0 has to offer :) But sometimes I'll want to opt a class out of one or more of those: Maybe I didn't get around to fully annotating this class for nullness, or maybe that class legitimately has a lot of `@Voidable` methods, or it's (unlike most of my classes) a good class to mock with mocking frameworks, or it's one of my few mutable classes, or whatever.

(Previous example: [It could be convenient for a `@Generated` annotation to imply `@NotNullMarked`, but you might want a way to override that sometimes.](https://github.com/jspecify/jspecify/issues/34#issuecomment-767036960))

In this case, it _could_ be convenient to be able to say:

`@MyFavoriteDefaults @NotNullMarked class Foo { ... }`

My _guess_ is that we ultimately would frown upon this:

- I don't feel good about the rule "Non-aliases take priority over aliases": What if for some reason you have to use `@MyNotNullMarked` instead of `@NotNullMarked`?
- I don't feel good about the rule "'Single-meaning' annotations take priority over 'multi-meaning' aliases": Under it, the behavior of `@MyFavoriteDefaults` would change based on how many defaults I've chosen.
- I don't feel good about a scheme under which `@MyFavoriteDefaults` could be marked with some kind of `@CanBeCountermanded` annotation that gives it lower priority: This feels like a niche feature, and it raises questions of what happens with two `@CanBeCountermanded`-annotated annotations....

So mainly I'm filing this to make sure that no one is thinking "Aliases will be great because I can do `@MyFavoriteDefaults @ButNotThisOne`": If anyone is thinking that, we should talk more about whether it will actually be possible.

**Comment by Mooninaut** [comment]
Options:
* Annotate larger scopes with `@MyFavoriteDefaults` and smaller scopes with `@NoDefaultX` overrides.
* Have a `@ButNot{DefaultX.class}` off-switch annotation.
* Potentially adds a great deal of complexity, but `@MyFavoriteDefaults(defaultX = false)` might work.
* Omit `@MyFavoriteDefaults` from any class/package/module where you don't want those defaults and use individual annotations.
* `@MyFavoriteDefaultsExceptX`.
* We put up with explicitly importing everything at the top of every class because That's The Way Java Does It, and IDEs implement auto-import. Maybe some sort of tool-assistance for annotating that would let you declare what should be annotated as what, and the tool takes care of it for you?

**Comment by kevin1e100** [comment]
I think there's maybe also the option to say: actual or implied opt-out
annotations take precedence over actual and/or implied opt-in on the same
element, regardless of which one(s) are implied through aliases. Tools
could additionally be encouraged (but possibly not required) to warn if two
annotations straight-up offset each other and do nothing else.

**Comment by kevinb9n** [comment]
First, the context discussion about what it means for one annotation to "counteract" or "negate" another annotation is in #109. It talks about precedence of narrower containing scopes over wider ones. I went through some anomalies that can arise, in https://github.com/jspecify/jspecify/issues/109#issuecomment-946180275_, including a link here for this particular one.

But (this part is relevant to @kevin1e100's last comment) notably, it's not _actually_ negation; a set of exclusive annotations could have three or more members (and we might even need to do that for CRV). It's not always well-defined which is an "opt-in" and which is an "opt-out", and even when there are only 2 of them and we *could* make that arrangement I'm not inclined to think we should.

Anyway,

This issue seems to ask how that feature and the `@Implies` feature should interact with each other. The scenario is as given in the linked comment: `@_x` and `@_y` represent a set of mutually-exclusive annotations, `@_z` is marked as implying `@_y`, and now we have `@_x @_z` applied to some program element.

Option A: this is invalid / provides no usable information
Option B: any direct annotation takes precedence over any implied annotation; however, a single annotation can't simultaneously imply both of `@_x` and `@_y` at any depth.
Option C: B, and also an annotation is allowed to imply both `@_x` and `@_y`, where again direct would have precedence over indirect. (But if x and y are _both_ brought in indirectly, trying to set a precedence rule for this case feels like jumping the shark, at least absent a very compelling use case.)

I think I present "feel best" about C, because I think that it seems very clear/unambiguous what the user expected the result to be, and we can do that. This is something less than an argument-from-use-cases, though.

**Comment by cpovirk** [comment]
I guess we can hypothesize that, if we define positive meaning for the situation, tools are more likely to implement it than if we declare it as "meaningless" or "invalid," in which case they might all implement whichever behavior is most convenient for that particular tool. I'm not sure if I buy that hypothesis or not.

Overall, though, I do like the idea of not worrying about things until we have to. And when we aren't sure we're done defining our initial set of nullness annotations, we mostly haven't defined aliasing at all, and few tools have implementing anything, it may be more harmful than helpful to think this far ahead.

**Comment by netdpb** [comment]
I feel like we're trying to have our null cake and eat it too. If tools can do whatever they want no matter what JSpecify requires, then either (a) why bother specifying anything, let's go home; or (2) specify that tools must do XYZ, but accept the fact that we're a sign not a cop. Which gets maybe back to the idea of good conformance tests, so at least we can tell which tools are following our rules, and give those tools a cookie.

**Comment by Mooninaut** [comment]
Options A and B both make sense to me, but option C seems nonsensical. If @_x and @_y are mutually contradictory, @_z -> @_x & @_y is self-contradictory.

**Comment by kevinb9n** [comment]
> Options A and B both make sense to me, but option C seems nonsensical. If @_x and @_y are mutually contradictory, @_z -> @_x & @_y is self-contradictory.

Ouch: Option C was supposed to say `@_x` and `@_z`! Editing it now. Thanks, no one else spotted this.

You're right that there is no reasonable precedence rule to fix `@_x @_y`. Option C proposes a rule, "direct annotations take precedence over indirect annotations". And there is some sense in this. There would be things you can't do with a nested class `A.B` but which you _could_ do with `A.B.C`! (one level to bring in `@_x` and one level to bring in `@_y`; obviously there is already precedence defined for nesting).

**Comment by Mooninaut** [comment]
I don't think allowing contradictions makes sense. It would be _very_ confusing for someone not intimately familiar with JSpecify to see a class annotated with contradictory annotations and try to figure out what that means.

**Comment by kevinb9n** [comment]
I wouldn't describe what we're considering here as "allowing contradictions", only defining simple precedence rules.

We already have the idea that an annotation at a narrower enclosing scope has precedence over a wider-level one.

It seems at least half-reasonable to have a rule that an immediate annotation has precedence over an implied one. And if we don't, there might be shenanigans where the user makes an extra surrounding class to put the Implies-bearing annotation on, so that they can then legally contradict it at a narrower scope. Eww.

**Comment by kevinb9n** [comment]
(Note that this is targeted 1.0 because even if we don't want to support precedence we still have to figure out what to specify instead about how to handle that scenario.)

**Comment by kevinb9n** [comment]
Let's just show 8 variations of causing `@NullMarked` and `@NullUnmarked` to clash with each other.

```
@Implies(NullMarked.class) @interface Yup {}
@Implies(NullUnmarked.class) @interface Nope {}

@NullMarked @NullUnmarked
some_program_element1;

@NullMarked @Nope
some_program_element2;

@Yup @NullUnmarked
some_program_element3;

@Yup @Nope
some_program_element4;

// these 4 again, same order, but like `@Implies(Yup.class) @Implies(Nope.class)` on an annotation type instead
```

#242 addresses how to treat cases 1 and 5, and is the best we can do for 4 and 8 too. It says: if more than 1 is "recognized" then declare them ALL unrecognized. No precedence.

 I would assume there is one single decision to be made for all of 2367 as well. The choices are to do the exact same thing (#242), or to give precedence to the annotation that appears "directly".

I'm into the simplicity of saying let's just handle them all the same way, but I also have the feeling there's something here I haven't fully understood.

**Comment by cpovirk** [comment]
I don't feel like I have a handle on all the implications here, but FWIW, I think I like treating 2/3/6/7 like all the rest. That is, I don't think I'd want to give precedence to the "direct" annotation.

That's partially because I'd feel that aliases are second-class if `@org.jspecify.nullness.Nullable` and `@MyNullable` were treated differently. (It would also be a way for behavior to unexpectedly change when switching between an alias and the main annotation.) Granted, I have some fear that aliases will always be second-class [in at least some situations](https://github.com/jspecify/jspecify/issues/35#issuecomment-767170882), but we don't need to make that problem any worse than it needs to be.

If anything, the case I might want to make an exception for is when an annotation implies _multiple_ annotations, only one of which is in conflict with a direct annotation. (That's the `@MyFavoriteDefaults @NotNullMarked` case.) But that feels surprising in its own way: Who would expect this behavior to change when adding or removing an annotation from the `@Implies` clause of `@MyFavoriteDefaults`?

But I also hope that this is almost all academic: Most people aren't going to write code that contains anything that looks like a conflict, and if they do, it may well be by accident. So it would be nice to just be able to do whatever seems simplest. And I assume that the simplest thing is not to try to define precedence at all.

My main fear is that it _would_ come up with `@MyFavoriteDefaults @NotNullMarked`... but that might actually "work" in practice: If both annotations are ignored, then the code remains null-unmarked -- unless, of course, it's inside a package or module that is `@NullMarked`....

**Comment by kevinb9n** [comment]
@Mooninaut the explanation of that is https://github.com/jspecify/jspecify/issues/242#issuecomment-1075502805

To pass our tests a tool must be able to detect the conflict itself, but _otherwise_ behave as if neither annotation is present.

**Comment by kevinb9n** [comment]
As a "working decision" to get us to 0.3, we will not define a precedence. It will not be possible to imply some set of annotations while also negating or disregarding one of them.

**Comment by cpovirk** [comment]
(https://github.com/jspecify/jspecify/issues/259#issuecomment-1251250926 touches on this again. Maybe we'll come back here, or maybe we'll continue there.)

I did want to note that an actual concrete example of this came up in the context of CheckReturnValue discussions:

We've been discussing how it might be useful for a `@ReturnsThis` annotation to imply `@CheckReturnValue`: That would let us identify `new Foo().setBar(x).setBaz(y);` as suspect.

However, that rule is not _universally_ correct: Consider `new SomeTester().testWithValues(1, 2, 3).testWithValues(4, 5, 6);`. Thus, if we were to have a `@ReturnsThis` annotation someday, and if it were to imply a `@CheckReturnValue` annotation, then we would still need to provide users with a way to override its `@CheckReturnValue`-ness. Presumably they'd want to do that by writing `@ReturnsThis @CanIgnoreReturnValue`.

But under the rules here, `@ReturnsThis @CanIgnoreReturnValue` would result in tools' declaring that those annotations provide _no_ information about return-value-check-worthiness, since (taken together) they imply both CRV and CIRV. (And the rules in https://github.com/jspecify/jspecify/issues/259#issuecomment-1251596440 would go a step further and declare that tools have to ignore `@ReturnThis`, too!) That means that the method would get its return-value-check-worthiness from any default set in a larger scope. And if that default is `@CheckReturnValue`, that would make it impossible to override that default for a `@ReturnsThis` method.

I think my main takeaway from this is "Don't do that": `@Implies` isn't for cases in which one property of an API is _likely_ to be associated with another property. It's for cases in which the one property _definitely_ implies another. By that logic, we wouldn't want `@ReturnsThis` to imply `@CheckReturnValue`. That said, people might also choose to instead view this as an argument for "closest annotation wins" or at least "direct annotation wins" (which I think I'm still [somewhat against](https://github.com/jspecify/jspecify/issues/216#issuecomment-1089122371)).

**Comment by cgdecker** [comment]
Slightly off topic from the issue itself, but I never thought `@ReturnsThis` should imply `@CheckReturnValue` in any way. If _anything_, it would imply `@CanIgnoreReturnValue`. But that's not right either, it's just probably closer to right than `@CheckReturnValue`. I think `@ReturnsThis` (at least with a default assumption that it means that the method mutates the receiver and then returns `this`), implies a certain context in which ignoring the result is ok: when we know there is already some reference to the receiver and as such ignoring the result won't mean discarding the last reference.

This information should enable checks to (at least potentially) make more accurate decisions about when to report an error. Perhaps they could also be allowed to just treat it as if it meant `@CanIgnoreReturnValue`. But to me it feels like, unlike `@CRV` or `@CIRV`, it isn't an explicit statement about the ignorability of a method's result and that as such I'd expect it to be legal to also annotate a `@ReturnsThis` method with either `@CRV` or `@CIRV` and for those annotations, if present, to be authoritative in an ignorability decision.

This does mean we might need to more clearly define the version of `@CRV` that goes on enclosing elements to explicitly be a relatively weak signal that relevant information about a specific method (i.e. not _only_ the `@CIRV` annotation) may take precedence over, and not only because the `@CRV` annotation is further from the method.

**Comment by kevinb9n** [comment]
I think we agree that that's a misuse of `@Implies`. So I think there are no relevant takeaways for this issue or other `@Implies` issues, correct?

**Comment by cpovirk** [comment]
Agreed that that's the big takeaway.

cgdecker has elsewhere elaborated on the point (about which he may write a doc) that `@ReturnsThis` could still be _used_ by CheckReturnValue-style checkers, in ways that might both "override" and "be overridden by" annotations that are _directly_ part of "the CheckReturnValue system." A spec would need to provide wiggle room for this. Fortunately, I think that's in line with past discussions we've had about how JSpecify _nullness_ annotations are only _one_ source of information about nullness.

There may still be additional complexities around how to handle the CheckReturnValue "overriding" situations I described above, especially in cases in which `@ReturnsThis` and another annotation suggest different CheckReturnValue behavior (even assuming that `@ReturnThis` doesn't use `@Implies`). The result might be that a tool can't just "ask for 'the JSpecify CheckReturnValue status'" and _then_ "look for reasons to change that." Instead, it might have to intermix those steps. But again, I'd expect that to be in line with how we already see nullness working, in which a tool might look for other nullness annotations at the same time it looks for JSpecify nullness annotations.

**Comment by netdpb** [comment]
**Current decision**: Because we are not planing to support annotation implication in 1.0 (#35, #307), this issue is not relevant for 1.0.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.
