### ISSUE TITLE
Opportunistically generate Java 7 bytecode?

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#217]
We've long said that [we'll target Java 8](https://docs.google.com/document/d/1d5NgP4Pjk_ahkISpRa3nFb1FzPz9yS9luByiBj6qCsk/edit#bookmark=id.quqw86ttbcvo), and we _need_ to so that we can use `@Target(TYPE_USE)`. It _may_ turn out to be easy and helpful to generate Java 7 bytecode, though, and we could consider it.

Our jar would still contain references to Java 8 APIs: `@Nullable` would still be `@Target(TYPE_USE)`. So the advantages would be only that:

- The jar could _be on the classpath_ seen by a tool that strictly enforces what versions of bytecode (but apparently not APIs) it sees. ~I'm under the impression that [such enforcement is available to Gradle users.](https://github.com/google/truth/issues/882)~ I am wrong; see [below](https://github.com/jspecify/jspecify/issues/217#issuecomment-944892922).
- Libraries that target Java 7 could use `@NullMarked`, which does not refer to any Java 8 APIs. On the one hand, that's little use without `@Nullable`. On the other hand, they would probably find that tools support any _other_ `@Nullable` annotation just as well, including a declaration `@Nullable` annotation that is built for older JDKs (e.g., jsr305). (Of course this is of no help to them if they need to annotate type-use-only locations. But some libraries don't need to. For example, we recently annotated the protobuf util package ([example](201426796)), and we were able to do it only with declaration annotations (which included `@NullMarked`, though we didn't release that part publicly [yet](https://github.com/jspecify/jspecify/releases/tag/v0.2.0)).)

Besides possibly eventually helping protobuf (which isn't yet moving to Java 8, even though most Google libraries have), this [could help Facebook](https://docs.google.com/document/d/1hr8Ld9cRMFksvA_Uzh61o4bdiVMXl084AR5QAkokEn0/edit?disco=AAAAQ29h53w). @artempyanykh 

The main immediate downside is that I don't know enough Gradle to do this easily :) As best I can tell, the modularity plugin we're using [lets us set `--release`](https://github.com/jspecify/jspecify/blob/1962f5ff3f072dfccd0f29df3d454f3865ca7782/gradle/publish.gradle#L74) but doesn't let us set `-source`+`-target` (which we'd need to do, in combination with _not_ setting the bootclasspath). Presumably we can roll our own compilation actions to do whatever we want, including an alternative approach of using `--release 7` for `NullMarked` and `--release 8` for `Nullable`....

The long-term risk is that, once we support Java 7, someone will push for us to continue. And maybe we just _can_ continue. But just as JDKs have removed support for targeting Java 6, they will eventually do the same for Java 7. Also, there's a chance that we'll want to use Java 8 features (repeatable annotations, like [for `@Implies`](https://github.com/jspecify/jspecify/issues/215)?).

**Comment by tbroyer** [comment]
> * The jar could _be on the classpath_ seen by a tool that strictly enforces what versions of bytecode (but apparently not APIs) it sees. I'm under the impression that [such enforcement is available to Gradle users.](https://github.com/google/truth/issues/882)

Well, this is not how it works actually. Checker Framework's checker-qual is published with additional [Gradle Module Metadata](https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html) that Gradle will leverage in place of the POM file when available, to enable [variant-aware dependency resolution](https://docs.gradle.org/current/userguide/variant_model.html). This [Gradle Module Metadata for checker-qual](https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.13.0/checker-qual-3.13.0.module) indicates that it targets Java 8, and the GRPC build explicitly targets Java 7 (through [the `targetCompatibility = 1.7` in the build script](https://github.com/grpc/grpc-java/blob/e9b0c2e85178e459510c501cae0b28401a1e306c/build.gradle#L256)) so Gradle complains that it cannot find a compatible dependency variant.
Had the checker-qual not been publishing Gradle Module Metadata, or the GRPC build explicitly [disabling its use through `ignoreGradleMetadataRedirection()`](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:supported_metadata_sources), the build would have succeeded (same as if they had been using Maven, or Bazel probably, rather than Gradle)

Wrt this issue, we're in late 2021, JDK 7 is still supported by [a handful vendors](https://medium.com/@javachampions/java-is-still-free-3-0-0-ocrt-2021-bca75c88d23b) for a few months only, a couple years at best. Even Android moved to Java 8 for a few years now AFAIK, and even Java 11 nowadays, and has had support for "desugaring" for even longer (possibly using third-party backporting tools). When some libraries start to even require Java 11+, I'm not sure it's worth your time to create a Java 7-compatible version at that time. My 2¢ but I'm not a project member so feel free to disagree and ignore.

**Comment by kevinb9n** [comment]
barring that, closing
