### ISSUE TITLE
In `@Implies` javadoc, endorse the "transitive annotation" pattern as a fallback

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#218]
Suppose annotation type `A` wishes to allow other annotations to "imply" it, e.g. `@Implies(A.class) @interface B {}`, but it wants users to have an alternative for whatever reason (e.g. perhaps B with no parameters wants to imply A with a hardcoded argument value).

If the `@Implies` javadoc defines a "transitive annotation pattern" to use for this case [EDIT: that means, advise `A` to include the annotation-type target type and to specify that `@A @interface B {}` means the same as the `Implies` code above], then

(a) it can explain the intended meaning of the pattern relative to the `@Implies` spec itself, which establishes consistency between the two approaches and should also just save time
(b) `A` (as long as it does not already target annotation types!) can adopt that pattern, and has an easy way to explain that to its users just by linking to the `@Implies` javadoc (perhaps to where it is hosted somewhere online, requiring no local build-time dependency)
(c) We hope there will be libraries corresponding to each API we use to inquire about annotations today, which make those inquiries in an `@Implies`-aware way; the `@Implies` javadoc would set out the rules these wrapper libraries should follow, and it makes sense for it to cover the transitive-annotation case at the same time.

(In fact, even if `A` has required parameters and _can't_ be used with `@Implies` this still works.)

Now, it is _irregular_ to be linking to `@Implies` to address a case where `@Implies` is not literally involved at all, but I'm not sure that's really a problem.

Not sure whether to tag this 1.0 or not, so when in doubt, I do.

**Comment by kevinb9n** [comment]
David asked if this could be postponed past 1.0, but I literally think it is only some advice in the javadoc. Nothing to even test.

**Comment by cpovirk** [comment]
I was thinking more about the possibility of accidental implication when `@Implies` supports non-JSpecify annotations (#182).

Here's one of our annotations in `com.google.common.annotations` (not part of Guava, though):

```java
@Documented
@GoogleInternal
@GwtCompatible
@IncompatibleModifiers(PUBLIC)
@Retention(CLASS)
@Target(CONSTRUCTOR)
public @interface DefaultConstructorForGwt {}
```

I think what we're saying is that `@DefaultConstructorForGwt` _doesn't_ imply _those_ annotations because _those_ annotations _don't_ document that they support the "transitive annotation" pattern. But how do tools know which annotations work that way and which ones don't? This sounds like it may be another reason to require putting `@Implies` on the annotation in order for it to imply anything, not for it to imply annotations it's annotated with automatically.

(Alternatively, we could have _another_ meta-annotation for `@SupportsTransitiveAnnotationPattern`. But that isn't an option for JDK annotations. Or we could trigger the behavior based on the presence of `@Target(ANNOTATION_TYPE)`... except that that would do exactly the wrong thing for `@Documented` and friends, so we'd need to hope that we can make a list of `@Documented` and all the annotations that _shouldn't_ trigger this behavior :))

**Comment by cpovirk** [comment]
I continue to think that we'd get into trouble if we tried to define a mechanism that behaves like implication but avoids using `@Implies`.

If we were to define such a mechanism anyway, I think that implementations would need to be careful in order to avoid sometimes introducing problems at runtime, even for people who don't use the mechanism.

Consider a tool like [Guice](https://github.com/google/guice) that reads annotations at runtime. When it sees a [`@Provides` method](https://github.com/google/guice/wiki/ProvidesMethods), it needs to see if any of the method's annotations imply `@Nullable`.

To do so, it has to call `getAnnotations()` on the method. If some the annotations are missing at runtime, `getAnnotations()` should omit them gracefully. But it's possible for some more complex problems to lead to exceptions ([JDK-8247797](https://bugs.openjdk.java.net/browse/JDK-8247797)), like if [the enum value for an annotation element is missing](https://github.com/jspecify/jspecify/pull/246/files#diff-6a22a6ede57062df5613483ebcc3fd278316078440bc35c7bf253ef49e89ee12R58). (Yes, we can hope that that JDK bug will be fixed someday, and maybe we could even try to help with it someday. But I wouldn't want to rely on anything anytime soon.)

I think that today Guice also needs to call `getAnnotations()` on the class _of each annotation_ (in order to check if it's a scoping annotation or qualifier annotation):

- https://github.com/google/guice/blob/2098d6ad4e33bb92e28d83eb6f52bf3497180985/core/src/com/google/inject/internal/ProviderMethodsModule.java#L322
- https://github.com/google/guice/blob/2098d6ad4e33bb92e28d83eb6f52bf3497180985/core/src/com/google/inject/internal/Annotations.java#L186-L192

That, too, should omit problem annotations gracefully in most cases but not necessarily in general.

The part that would change with the feature we're discussing here is that Guice would thereafter need to explore the entire meta-annotation graph. (Note that even plain `@Implies` could increase how much of the graph it would need to explore, though at least it would be limited to the edges explicitly requested by `@Implies`.) That increases the chances that it will encounter an annotation that actually leads to an exception. For example, the Java 8 implementation of `getAnnotations` [throws an exception](https://github.com/jspecify/jspecify/pull/246/files#diff-6a22a6ede57062df5613483ebcc3fd278316078440bc35c7bf253ef49e89ee12R58) when it tries to look up the annotations on an annotation that has `@Target({..., MODULE})`.

This should mostly be solvable by catching the exception. That does still leaves the feature slightly less reliable. (And it probably would lead Guice to either log a bunch of warnings or else ignore annotations silently, yuck. In contrast, it would seem more defensible for Guice to actually fail _if it encountered an annotation that was explicitly annotated with `@Implies`_, since `@Implies` suggests that the annotation author thinks it's important for tools to follow the link.) That said, implication in general may already end up being somewhat [second-class](https://github.com/jspecify/jspecify/issues/216#issuecomment-1089122371), if only in the case of [incomplete classpaths](https://github.com/jspecify/jspecify/issues/35#issuecomment-767170882) (which is _one_ of the possible causes of the issue I'm discussing here).

Again, it's worth reemphasizing that the fundamental problem (a) exists today and (b) gets bigger with plain `@Implies`, just not _as_ big as it gets with "implication without `@Implies`."
