### ISSUE TITLE
Position on types (in APIs) that observably include null only when "something has gone wrong"

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#225]
A type has "lifecycle" if a constructed instance may be observed in either a pre-initialized or post-invalidation state, in addition to its regular "alive" state. Ideally, methods called in inappropriate states would always throw `IllegalStateException` (we can't rely on this).

Here is just a simplistic example.

```
public class SoAlive {
  private State state = State.PRE;
  private Foo foo = null;

  public void init() {
    checkState(state == State.PRE);
    foo = somethingNonNull();
    state = State.ALIVE;
  }

  /** Throws if you haven't called init() or have called invalidate(). */
  public /* @Nullable or not? */ Foo regularMethod() {
    checkState(state == State.ALIVE);
    return foo;
  }

  public void invalidate() {
    checkState(state == State.ALIVE);

    @SuppressWarnings("nullness") // safe because all methods should throw ISE now
    foo = null; // it shouldn't nec. have to do this, but say it does
    state = State.POST;
  }

  private enum State { PRE, ALIVE, POST }
}
```

I believe it's important to null-annotated these members with the "alive" state in mind. So, I would *not* put `@Nullable` on the `regularMethod` return type.

Why: Since most APIs are invoke-mostly (not override-mostly), we prioritize the needs of the consumer over the implementor. That consumer's need is for accurate information about valid instances. If they try to use an invalid instance, "all bets are off" (of course we could explore solutions for helping them not do that, but that's separate). So there's no compelling reason to give up accurate/useful information about the alive state.

But this has a few advantages for the implementor as well:

* It's good that we'd get a warning in `init` if `somethingNonNull` is nullable
* It's good that we have to suppress a warning in `invalidate`
* I think it's probably even good that a tool might give a warning on the constructor saying that not all non-nullable fields were set; it's just slightly unfortunate that that would have to be suppressed once-and-for-all on the whole constructor.

Problems caused or remaining:

* If `init` forgets to set `foo`, can we even catch that bug?
* If someone is doing runtime-check injection based on this, it could break. This is a slightly more general problem though. If it becomes important, we'll need to have ways to indicate that a certain check should be skipped.

Unclear:

* It seems debatable whether the lack of a warning where `foo` is used as non-nullable in `regularMethod` is a good thing or not. I think the real concern would be making sure `state` is always checked, which is nullness-agnostic, and which we could look into to the extent it starts to feel important.

(split from #39)

**Comment by kevin1e100** [comment]
The above example appears to have the property that `foo` is non-null _whenever it is read_. That is, there is no execution where `foo` is read and `null`, simply because all field reads are guarded by state checks. Is that intentional or just happenstance in this example? fwiw I feel that that could be a possible, maybe even reasonable way of defining what a non-null field should mean (though it's not completely practical, but I'll hold that back for the moment).

**Comment by cpovirk** [comment]
I'd be very interesting in the details of "not completely practical" :) My personal feeling is that non-null fields should never have `null` read from them _nor_ written to them. I'd be interested in hearing whether that makes the idea more practical in your mind or less.

(Actual response to kevinb9n's points to come soon, I hope...)

**Comment by cpovirk** [comment]
As kevinb9n says, there is history in #39. The biggest remaining practical difference between the two of us seems to be that I'm opposed to writing `null` to a non-nullable field, and kevinb9n is OK with it if there's a suppression.

I tend to view this as a fundamental question of what types are: They're the set of values that reads and writes of a variable can use, so if that set doesn't contain `null`, then neither can reads and writes of the variable use that value.

I do appreciate that `private @Nullable State state` can be pretty thoroughly inconvenient to the implementer of the class. However:

- My _hope_ is that the case of nulling out a field _after usage_ is _relatively_ uncommon. (kevinb9n are both fine with having fields that _start out_ `null` but are always "properly initialized" before they're read.) It will come up for sure, but I wouldn't want to go to too much effort to make it go more smoothly unless we know that it will come up a lot.
- _If_ implementers are actually going to the trouble of inserting state checks like in the example code above, then it's probably typically sufficient to change `checkState(state == State.PRE)` to `checkState(foo != null)`. That gives the null check "for free." Yes, that means that we lose the distinction between `PRE` and `POST`. But my guess is that that distinction is needed in only a subset of the "lifecycle" cases we're talking about.
- But in the end, I fundamentally feel that convenience is a good reason for _more features_ but not a reason to _change what types mean_, and I feel that this is "changing what types mean." I think it's different in _degree_ but not in _kind_ from other cases we've discussed -- most notably, how some people would like `Map.get` not to return a `@Nullable` value because that loses the information that the value really is non-null in most cases. Just as we expect to address `Map.get` by annotating it with `@Nullable` and then doing work to refine that in some cases, so too would I expect us to annotate the field with `@Nullable` and then do work (other annotations? heuristics based on where `foo` is assigned?) to refine that.

**Comment by cpovirk** [comment]
Thanks.

It's certainly true that we can't prevent people from reading null from fields. I've been kind of uncomfortable with some past attempts to address this more abstractly. Here are a couple examples of more abstract answers that I think we've discussed:
- A "valid execution" should never read null from a field.
- When null, a field should never be exposed to "external code."

I prefer the more concrete idea that a tool _could_ choose to insert null checks on reads from the field, and so you should code as if that might happen. Of course, people are unlikely to use such tools -- not least because those null checks might change behavior :) But at least it's a concrete principle that we can define, and it's one that matches Kotlin's handling of Java code.

Under that model, any class that actually _wants_ to read null from its fields, even if only during initialization, should annotate them with `@Nullable`. (If it wants to read _non-null_ values from its fields during initialization, that's fine with me, and I don't see a need for `@Nullable`. But as you note, it can be challenging for a checker to statically prove that that's being done safely.)

But you raise an interesting point about assertions, which don't exactly "want" to read null from the fields but would prefer that to an _automatic_ NPE: They don't want a tool to insert code to throw `NullPointerException` because they want their `checkState(foo != null, ...)` call to throw a more detailed `IllegalStateException`. A tool that inserts null checks would change behavior. I think that's a tolerable risk, if only because I like the other options less :)

The possibly even more interesting case is a combination of your point and kevinb9n's example, in which an `init` method contains `checkState(foo == null)` -- that is, a check that the field _is_ null, i.e., that the object has _not_ already been initialized. My suspicion is that most code doesn't do that kind of checking, but maybe it comes up more than I think. The workaround would be to write the code as kevinb9n has it, with a separate `state` field, thus avoiding the need to read `foo` itself.

**Comment by kevin1e100** [comment]
I was thinking about this a bit more as well and I think I agree: while uninitialized fields are certainly observable, one might still argue they shouldn't be read while they're uninitialized (which I _believe_ is Scala 3's approach as well). Or put another way, reading them before initializing seems like it would usually be unintentional aka a bug. So the idea that `@NonNull` fields should never be `null` when read would still hold.

Granted initialization issues hopefully typically aren't a concern from an API perspective. But they can be a concern for subclasses, so this could be relevant for APIs that provide non-final classes for the purpose of subtyping. `java.io`'s `PipedInputStream/PipedOutputStream` may be an interesting example for all this: they have a lifecycle, and they also define protected fields.

Regarding explicitly written nullness assertions on fields, I suppose one might argue these fields can and should be annotated `@Nullable`, not least since checkers would otherwise consider these checks pointless.

**Comment by kevinb9n** [comment]
> The above example appears to have the property that `foo` is non-null _whenever it is read_.

Ah, no, not an intentional assumption. I *might* read it from `init()` and it's on *me* to worry about null-pollution if I do. I'll still try to persuade us that this is much better classified as initialization issue than a nullness issue. It isn't specific to nullness. Classes with complex initialization have to exist in states where *any* of their invariants might not be on-line yet.

**Comment by kevinb9n** [comment]
> The biggest remaining practical difference between the two of us seems to be that I'm opposed to writing `null` to a non-nullable field, whereas kevinb9n is OK with it if there's a suppression.

That sounds like the "difference that makes no difference", because of course users WILL suppress when they want to. Are we just arguing over what to "condone" or not?
 
We're discussing examples where the field will always be non-null when the object is in its usable state. Your position seems to amount to forcing that field to be `@Nullable`, and I'm just arguing that sacrifices so much for too little benefit.


> I tend to view this as a fundamental question of what types are:

No, I think we agree on that fundamental question.

I'm claiming only that these types are in practice like Java's parameterized types: erasure happens, heap pollution happens, and sometimes this gives users useful escape-valves they need (I suspect _more_ commonly needed in the nullness world). Your argument is appealing to making them more like the base unerased types like `List` itself -- stark constraints that I just don't see being realistic.


> _If_ implementers are actually going to the trouble of inserting state checks like in the example code above, then it's probably typically sufficient to change `checkState(state == State.PRE)` to `checkState(foo != null)`. That gives the null check "for free."

It's a pared down example for pasting into a bug not meant to look like real world code. There could be one state bit and a dozen nullable fields, for example.


> Just as we expect to address `Map.get` by annotating it with `@Nullable` and then doing work to refine that in some cases, so too would I expect us to annotate the field with `@Nullable` and then do work (other annotations? heuristics based on where `foo` is assigned?) to refine that.

I'll acknowledge that the side I'm arguing here and how I've been arguing that *seem* fully contradictory. I'll explain why they're actually aligned in my mind, but it might take a bit of time.

**Comment by cpovirk** [comment]
Thanks, the discussion of the seeming contradiction should be helpful. I think that's half of my concern about this.

The other half of my concern is Kotlin (and hypothetical "similar tools"). We can write something like this:

```java
@NullMarked
interface ProgressReport<T> {
  /**
   * Reports that the job is currently processing {@code t}.
   *
   * <p>When the job is done processing all inputs [i.e., when its lifecycle is
   * "over"], then the caller should invoke {@code
   * reportCurrentlyProcessing(null)} to free retained memory. This may
   * require suppressing a nullness warning.
   */
  void reportCurrentlyProcessing(T t);
}
```

But Kotlin _will not let_ callers make that call: It will prevent it through a combination of compile-time and runtime checks.

So, if we're saying "just suppress," we are (currently!) saying "Annotate in a way that will work for some tools but not for others." Now, if I'm remembering past discussions correctly, I think your proposal is to get Kotlin to stop performing those checks. That way, tool authors can annotate in a way that works for all tools, as hoped. But I think that Kotlin proposal is likely to be a non-starter. I could be wrong, but I think the discussion we'd need to have is with the Kotlin people.

(My suspicion is that the best practical way forward is going to be a `@NullableButNotDuringItsLifetime` annotation that `@Implies(Nullable.class)`, as discussed at one point. I should think more about that at some point. For now, I bring it up mainly to emphasize that users aren't dooooooomed if Kotlin keeps its current behavior.)

**Comment by cpovirk** [comment]
Oh, and I forgot to say:

> > I tend to view this as a fundamental question of what types are:
>
> No, I think we agree on that fundamental question.

Yeah, I think there's some disagreement here, but it's probably not over "what types are," sorry. It may be more about ["super erased,"](https://github.com/jspecify/jspecify/issues/65#issuecomment-1030123674) as you touched on again above.

**Comment by kevinb9n** [comment]
The code example is strange. I hope you haven't truly been under the impression that I've been talking about anything even remotely like this. 

If that method is still happily serving callers, then the object is alive. In that alive state it welcomes null input, so it should put `@Nullable` on the parameter, as any reasonable person would do.

Obviously it's the out-types of the API that are the far more likely examples here; they might risk producing null before the object has been fully initialized.


> Now, if I'm remembering past discussions correctly, I think your proposal is to get Kotlin to stop performing those checks.

I don't recall having such a definite opinion.


> (My suspicion is that the best practical way forward is going to be a `@NullableButNotDuringItsLifetime` annotation that `@Implies(Nullable.class)`

Well, this is more or less my picture of "epic failure".

**Comment by cpovirk** [comment]
OK, I am definitely confused, then :( My initial reaction to your latest post is that it sounds like an argument that fields _are_ ["special."](https://github.com/jspecify/jspecify/issues/39#issuecomment-1030464502)

Here's an expanded version of the class from my previous post:

```java
@NullMarked
class ProgressReport<T> {
  T currentWork;

  ProgressReport(T initialWork) {
    this.currentWork = checkNotNull(initialWork);
  }

  void checkAlive() {
    if (currentWork == null) {
      throw new IllegalStateException();
    }
  }

  void reportCurrentlyProcessing(T currentWork) {
    checkAlive();
    this.currentWork = currentWork;
  }

  void close() {
    checkAlive();
    this.currentWork = null;
  }
}
```

It's written with an explicit `close()` method (whose implementation would have to suppress a warning). Users can call that to invalidate the object (internally implemented by assigning `null` to `currentWork`). I think that's one of the cases we're discussing, similar to your original post on this thread.

But I've also written the class to show an alternative/additional API we could offer: Instead of (or in addition to) offering `close()`, we could ask users to invalidate the object by calling `reportCurrentlyProcessing(null)` (likewise internally implemented by assigning `null` to `currentWork`). My previous understanding had been that that was an API that you would endorse because `null` passes through the API only when the object's lifecycle is ending. But that seems not to have been the case.

So I'm trying to square that with `close()`, which I'm _more_ confident is an API that you would endorse: It, too, has `null` pass to `T currentWork` only when the object's lifecycle is ending. At first glance, the difference seems to be tied up in whether `T currentWork` is just a field or also a method parameter.

**Comment by cpovirk** [comment]
Between that and your note about Kotlin, I'm wondering if the terms you're thinking in aren't so much _lifecycle_ (dead vs. alive) as _visibility_ (internal vs. user-facing).

Here's an example of a compromise that a class might make internally -- in this example, a class that implements a tree. All its "real" node objects would always store a non-null value. But a special (sentinel/header) node (which is never exposed to "users") might store `null` -- not just "during initialization" or "after it's closed" but _permanently_.

I ([not hypothetically](https://github.com/google/guava/blob/a5eb7fd6fbc3e5fdebe65f90dc6c41729f17b7b0/guava/src/com/google/common/collect/TreeMultiset.java#L586-L596) :)) would annotate the value field as `@Nullable`. I suspect that you would not.

The rule, then, is essentially:

- If a section of code is "internal enough" that you can restrict which tools will see it (e.g., Checker Framework but not Kotlin), then you can do things that might be seen as type errors but that you know will work well with the tools you're using.
- But the situation is different if a section of code might be processed by arbitrary users' tools. (Maybe that's Kotlin. Maybe it's some runtime instrumentation that tries to identify places to add `@Nullable` annotations automatically for a whole app. Maybe it's even a hypothetical future version of Java that inserts null checks, as I got the impression they might want to do if nullness became part of the language!) In that case, you'll have to take care not to require a `@Nullable T` to fit through a `T`-shaped gateway in such code.

Does that sound any closer to a correct characterization of your view?

**Comment by kevinb9n** [comment]
> Between that and your note about Kotlin, I'm wondering if the terms you're thinking in aren't so much _lifecycle_ (dead vs. alive) as _visibility_ (internal vs. user-facing).

The topic has branched out to cover more than just lifecycle, yes. If you want to make it fully general, maybe it's something like:

"Because my code is guaranteeing XYZ will never happen, and because doing this WRONG THING I'm about to do can only lead to an actual problem in case XYZ, therefore I have the right to cheat and do the WRONG THING and suppress a warning."

I think we have no way of taking that right away from users even if we wanted to, so I haven't understood why we've had as much handwringing over it as we have.

 
> Here's an example of a compromise that a class might make internally -- in this example, a class that implements a tree. All its "real" node objects would always store a non-null value. But a special (sentinel/header) node (which is never exposed to "users") might store `null` -- not just "during initialization" or "after it's closed" but _permanently_.
> 
> I ([not hypothetically](https://github.com/google/guava/blob/a5eb7fd6fbc3e5fdebe65f90dc6c41729f17b7b0/guava/src/com/google/common/collect/TreeMultiset.java#L586-L596) :)) would annotate the value field as `@Nullable`. I suspect that you would not.

Thanks for the example!
We're just debating between two different "cheats", right? Either way we're just "hoping" no one will call getElement() on the root node? (The cheat is presumably only necessary because this is rare data structure implementation code that needs to be tightly optimized, and *most* people in cases like this should refactor.)

This resembles the question of whether an ArrayList<E> should store elements in an E[] or an Object[], doesn't it? There again, it's gotta cheat on the way in, or cheat on the way out. 

> * But the situation is different if a section of code might be processed by arbitrary users' tools. (Maybe that's Kotlin. Maybe it's some runtime instrumentation that tries to identify places to add `@Nullable` annotations automatically for a whole app. Maybe it's even a hypothetical future version of Java that inserts null checks, as I got the impression they might want to do if nullness became part of the language!) In that case, you'll have to take care not to require a `@Nullable T` to fit through a `T`-shaped gateway in such code.

Maybe we should assume that those tools will solve this problem themselves if it comes up, and IF they are telling us that they want a standardized solution THEN we have to continue this discussion? (Two possible flavors of solution that have popped into my head are "when setting `nonNullableField = null` AND you want to use FooTool, then you have to wrap that in `catch (NPE)` because we instrument assignments like that automatically", and "when suppressing a nullness warning AND you want to use FooTool you need use our special suppression annotation that has class visibility, so we'll avoid instrumenting that code".  But I don't want to get deep into solving this.

**Comment by cpovirk** [comment]
(trying to dice my reply up into separable posts)

It might be that my main goal has been to push for specificity in what the values of XYZ are. I don't meant that we need to stop and produce an exhaustive list right now, just that those are the questions that I'd want users to be asking themselves. That said, the list is probably extremely short:

Suppose that I'm declaring this parameter as non-nullable, but sometimes I call the method with a null argument. That's OK because:

- I know the method will never be called from Kotlin. (Maybe it's a `private` method, or maybe we are OK assuming that we won't use Kotlin in this codebase for a while.)
- As far as we know, _no one in the world_ has yet written a bytecode rewriter that automatically inserts runtime null checks on parameters/arguments that are supposed to be non-null. So clearly we're not using one of those. And if someone writes one and we start using it, _then_ we'll figure out the solutions to the problems it creates (as you said).

From this perspective, I'm declaring that the parameter is non-nullable as a way of saying "Tools, keep `null` out!" As part of making that decision, I'm recognizing that what I really mean in my particular case is "Tools, keep `null` out at compile time (in a way that's suppressible), and keep it out at runtime only in circumstances that don't apply here."

I personally don't absolutely 100% love that (in comparison to a model in which we pretend that every method call or field read/write performs runtime null checks around its non-nullable "gateways"). But it's very true that we can't keep users from doing it. And so I think it's good for us to focus on making users ask themselves the right questions, rather than pushing for a level of purity that won't make a practical difference in how users behave.

**Comment by cpovirk** [comment]
> We're just debating between two different "cheats", right? Either way we're just "hoping" no one will call getElement() on the root node?

I see 2 different "levels" of cheating.

Now, by this point, I've pretty much given up on trying to get people to stick to the lower level :) (See my post from a few minutes ago.)

But the distinction I had been going for was the one in which we imagine rewriting bytecode to perform runtime checks around every "gateway": In the current code, no one ever inserts a `null` into a non-nullable field. In a version of the code _without_ the `@Nullable` annotation on the field, then the one constructor _would_ insert `null` into a non-nullable field. This would produce NPE under the hypothetical bytecode rewriter.

Yes, in both cases, there could be trouble if someone called `getElement()` on the header. But the code does not do that, so the current code does not _rely_ on the ability to get `null` through a non-nullable gateway. That, to reiterate, is the difference: The version of the code _without_ the `@Nullable` annotation on the field _would_ be relying on that.

Again, though: By this point, I've pretty much given up on trying to get people to stick to the lower level.

> (The cheat is presumably only necessary because this is rare data structure implementation code that needs to be tightly optimized, and _most_ people in cases like this should refactor.)

Definitely agreed on that.

**Comment by cpovirk** [comment]
> This resembles the question of whether an ArrayList should store elements in an E[] or an Object[], doesn't it? There again, it's gotta cheat on the way in, or cheat on the way out.

Using E[] is probably a reasonable analogy for what we're doing here.

Using Object[] _doesn't_ strike me as "cheating" in the way we're discussing here: Everything we put in is an `Object`, and every time we return something from a method that claims to return an `E`, we return an `E`. (Here, I'm ignoring what _callers_ could do with raw types or suppressions.) It's true that we need to do things that are _unchecked_ (specifically, the cast to `E`), but we never put the "wrong" type through a gateway the way that we do when putting a `null` through a non-nullable gateway.

**Comment by cpovirk** [comment]
> That said, the list \[of when putting `null` into a non-nullable field (for example) could cause trouble\] is probably extremely short:

OK, I'm now a little sheepish to realize that I forgot some of the other tools that process Guava, including [j2cl](https://github.com/google/j2cl) and [J2ObjC](https://developers.google.com/j2objc).

Their compilers differ from Kotlin in a significant way: They compile not just _users_ of Guava but also _Guava itself_. The result is Objective-C or Closure-typed JavaScript for _our_ code. That can mean that even our internal helper methods can fail to compile if they have nullness errors.

Conveniently, J2ObjC currently respects `@ParametersAreNonnullByDefault` -- support for `@NullMarked` remains a TODO, IIRC -- only when looking at calls made to methods that are at least package-private (I think). So calls to `private` methods can pass whatever they want. Of course, we should still be a little nervous: Some internal APIs need to be package-private, and we make others package-private so that we don't require synthetic accessors (in the pre-nestmates days). And it's just fragile that a change to make a package-private method `private` could possibly break our users. (Quite possibly J2ObjC would someday like to check _all_ methods but stuck to non-`private` methods initially as a compromise. We could talk more to the team about this.)

(As for j2cl, the last comment I remember is "jscompiler does not typecheck J2CL produced code w.r.t nullability." So we are probably fine there for now.)

The simplest fix, presumably, is for tools like these to see `@SuppressWarnings("nullness")` and conclude that they should also generate suppressions in the languages that they compile to. (This requires that the tools process source code, where `@SuppressWarnings` is visible, rather than bytecode. But that's fine for the tools I'm aware of.) My concern then would be whether all such languages _have_ suppressions. We've been discussion how Kotlin doesn't, but does the compiler we're using for Objective-C? I would imagine probably.

But we'll want to keep this in mind as we see Guava transpiled to more languages.

**Comment by kevinb9n** [comment]
With #283 written up now, would this be an acceptable resolution for this issue?

"Your goal would typically be to annotate for the states that consumers of your API are actually expected to encounter; however you should be aware of the risks of null pollution (link)."

**Comment by kevinb9n** [comment]
Welp, I couldn't leave well enough alone. I wanted to think through two different sub-cases more carefully. Here's a longish analysis with a simple proposed conclusion. The longish part should mostly become useful documentation at some point.

## Restating the scenario

This issue report was appealing to “lifecycle”, but is really a bit more general. The interesting case is:

* A type usage in a library’s API is strictly technically nullable.
* Yet it includes null only in *exceptional* scenarios that the library’s clients *should* never find themselves in (according to the API's broader contract, whether enforceable or not).

In these “exceptional” cases, “something has already gone wrong” (it might not be this client’s fault, but it doesn’t matter). Notice this is *not* the “[Map.get case](71)”.

Now if this were an analogous question of choosing a *root type*, there is no freedom; javac forces us to use the more general type. But our case is much more like parameterized types; we do have the flexibility to decide between the lesser of two evils:

* The type can be **technically over-specific** (non-null).
* The type can be **over-general in practice** (nullable).

## Splitting the cases

These options have different consequences on **provided types** (where values flow out from a library to its clients) vs. **accepted types** (where values flow into a library from its clients). (I’ll disregard “inout” types, which are rare and already have much bigger problems.)

### Case 1: provided type

Should the API owner make this provided type:

* "technically over-specific"? (non-null)
    * General consequence: in the errant case, can cause [null pollution](283) in the client. An immediate defensive null check would catch it, but nothing would prompt the user to do that.
    * Consequence to Kotlin client: in the errant case, at least that runtime null check will happen, so we “fail faster” and more consistently.
* "over-general in practice"? (nullable)
    * General consequence: well-behaved clients suffer “type dullening” (like happens when calling a polynull method without polynull support). To recover the knowledge of non-nullness they must suppress a finding, or make an unnecessary-feeling runtime check.
    * Consequence to Kotlin client: same, but that first remedy is impossible; happily, the second remedy is super easy!

### Case 2: accepted type

Should the API owner make this accepted type:

* "technically over-specific"? (non-null)
    * General consequence: in the errant case, the client would have to suppress a finding in order to pass `null` to the library.
    * Consequence to Kotlin client: that's impossible, so there is simply no way to do this, short of altering the library jar!
* "over-general in practice"? (nullable)
    * General consequence: well-behaved clients may *accidentally* send `null`, which we can only hope is rebuffed at runtime.
    * Consequence to Kotlin client: same

## … So what?

I claim that in both cases, both options are viable; therefore I suggest that we should elevate neither one as the correct approach.

Much of the text above should find its way to the appropriate "recipe book" entry, FAQ, etc. so that users have the guidance they need.

**Comment by kevinb9n** [comment]
I mentioned "future doc material" and hey, I really did copy this to http://github.com/jspecify/jspecify/wiki/borderline-cases
