### ISSUE TITLE
How to handle recursive `@Implies`?

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#237]
_Originally posted by @Mooninaut in https://github.com/jspecify/jspecify/issues/213#issuecomment-1060777282_

[Quoted text was from me; unquoted from @Mooninaut]

> When it comes to `@Implies` it seems like you have a highly developed view of what you count as "sophisticated".
> 
> But from my point of view, by the time the hard part is done of speaking to all the different scenarios that can happen, then handling those scenarios in a slightly more useful way doesn't seem that much harder/riskier. IOW punting doesn't even get us out of that much imho.
> 
> The way I see it `@Implies` just simply doesn't give a crap whether the same annotation it's applied to also wants to imply other things too. It's not trying to "own" the whole picture of what this annotation does. It's just expressing one aspect, and another `@Implies` ought to be able to express another.

I think recursive `@Implies` should be forbidden initially. I suspect allowing recursive `@Implies` will add complexity to the spec and test suite, to implementations, and for users, with _very_ little benefit to real projects.

### High specification and implementation cost
* Recursively defined annotations require implementations to detect infinite loops.
* Recursive annotations require implementations to resolve potentially large nested trees.
* Recursive annotations will bloat the specification, test suite, and implementations with priority rules, conflict resolution rules, and edge case handling.

### Low (potentially negative) user benefit
* The more complex an annotation is, the harder it is to use correctly.
* Any project should define its aliases in one place, which makes keeping them in sync straightforward.
* Projects shouldn't define more than a handful of default sets, or the benefits of consistent defaults disappear and they might as well use individual annotations.
* Defaults shouldn't change often, or again, the benefits of consistency disappear.
* Recursive annotations create enormous potential for "action-at-a-distance" bugs where a change in one place breaks things far away.
* If recursive annotations can never change without widespread breakage (see previous points), you can flatten any recursive annotation into a non-recursive annotation with the same semantics, which is now self-documenting.
* [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it). Forbid recursion at first and add it **if** a hugely compelling real-world use-case turns up.

> The one caveat to that is that yeah, it may represent just one additional small wrinkle to speak to when we define how precedence works in general for Implies (including if we define how it _doesn't_ work). If this somehow turns into a disaster we can reevaluate.

I'd rather head off an easily-foreseen boondoggle than wait for it to happen and then reevaluate.

**Comment by kevinb9n** [comment]
Thanks for this, Clement! We'll continue lightly sketching out the "theory" behind `@Implies`, but note that actually *doing* much about it has been on hold, waiting to be strongly use-case driven.

Let's use this example:

```
public @interface One {}

@Implies(One.class)
public @interface Two {}

@Implies(Two.class)
public @interface Three {}

@Three some_program_element

LibraryDescribedInIssue220.get("some_program_element").hasAnnotation(One.class)
```

We're slowly trying to order our thought processes along lines like this:

* First, we focus only on what the annotation *means.* I think it's clear that this arrangement *means* that the `hasAnnotation` query would both logically and by expectation return `true`.
* That library described won't exist for a while, but we rely on adding a conformance test (#232 and linked issues).
* We don't expect that many tools will pass the entire conformance suite anytime super soon. We might get to a point where we group the tests into categories of importance.
* We can't really "forbid" anything. We can define situations in which our annotations *carry no meaning*. I don't readily see how to apply that in this case.

Soon I'll reply to some of your individual points.

**Comment by kevinb9n** [comment]
The points you're making feel relatively minor overall, but I've taken each one seriously:


> * Recursively defined annotations require implementations to detect infinite loops.

This one just seems like a small matter of programming. #220 would handle it, or they could use/copy a method from Guava or whatever.


> * Recursive annotations require implementations to resolve potentially large nested trees.

Large seems unlikely?


> * Recursive annotations will bloat the specification, test suite, and implementations with priority rules, conflict resolution rules, and edge case handling.

In the issue where we discuss conflict resolution there is a little bit that's brought in by this, yes.


> * The more complex an annotation is, the harder it is to use correctly.

I don't think this is actually a useful principle. What constitutes complexity is subjective: to me, the proposal in https://github.com/jspecify/jspecify/issues/35#issuecomment-625969158 is simple. But to make it *not* work recursively would require adding complexity. We'd have to add special cases to chip away at its basic meaning.

This may be an underlying difference between us here. To you this looks like an advanced feature, but to me implication simply _is_ transitive and trying to fight against that is what's more advanced.


> * Any project should define its aliases in one place, which makes keeping them in sync straightforward.
> * Projects shouldn't define more than a handful of default sets, or the benefits of consistent defaults disappear and they might as well use individual annotations.
> * Defaults shouldn't change often, or again, the benefits of consistency disappear.

I don't think we can be so sure yet what the "shoulds" surrounding use of this annotation are. It just means what it means and people will use it in ways we can't predict. 


> * Recursive annotations create enormous potential for "action-at-a-distance" bugs where a change in one place breaks things far away.

More generally, adding `@Implies(One.class)` to `Two` (or upgrading a library that made that change) is already an unprecedented way to apply `@One` to a large number of call sites all at once. Anyone doing that should reanalyze those files and tweaks might be needed. This just seems like how changing a library works. To make a more graceful path we need to get back to topics like #26.

With recursion, those call sites can be a mix of some that say literally `@Two` and some `@Three`, but does this really change matters much?


> If recursive annotations can never change without widespread breakage (see previous points)

For now I consider this an "n/a" (as just covered)


> * [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it). Forbid recursion at first and add it **if** a hugely compelling real-world use-case turns up.

This is trying to wield YAGNI like a blunt hammer. It's a guideline that applies where it applies and doesn't where it doesn't. Here's a partial list (without regard to which apply to this particular decision):

* "It" should actually be a binary decision
* "It" must actually be harder to do (or more unstable) than not doing "It" now
* "It" must be clearly safe to add later compatibly (we have to think through that transition cleanly; it's sometimes not enough to just throw up a wall saying "just forbid now")
* There are wants as well as needs. Features that help adoption happen more smoothly or make more users want to adopt are strong wants.

Is there any particular personal stake you have in which way we go here? Does this decision have some impact on you that we don't know? If so, could we please just talk about that? Respectfully, the strength of your arguing ("hugely compelling real-world use-case") just seems disproportionate to the strength of your arguments so far.

**Comment by kevinb9n** [comment]
Didn't find the argument convincing, and no response so far. Closing for now.

The idea of "implies" is transitive by basic logic. We would have to go out of our way to prevent it from being so.

**Comment by Mooninaut** [comment]
> The points you're making feel relatively minor overall, but I've taken each one seriously:
> 
> > * Recursively defined annotations require implementations to detect infinite loops.
> 
> This one just seems like a small matter of programming. #220 would handle it, or they could use/copy a method from Guava or whatever.

I agree with this point.

> > * Recursive annotations require implementations to resolve potentially large nested trees.
> 
> Large seems unlikely?

If the trees *aren't* large then there's no use case for transitive implication in the first place. One can trivially flatten a shallow tree by directly naming the implied annotations.

> > * Recursive annotations will bloat the specification, test suite, and implementations with priority rules, conflict resolution rules, and edge case handling.
> 
> In the issue where we discuss conflict resolution there is a little bit that's brought in by this, yes.

I foresee more than a little bit of complexity here. Unless, again, the actual use cases are so simple that there's no need for transitivity.

> > * The more complex an annotation is, the harder it is to use correctly.
> 
> I don't think this is actually a useful principle. What constitutes complexity is subjective: to me, the proposal in [#35 (comment)](https://github.com/jspecify/jspecify/issues/35#issuecomment-625969158) is simple. But to make it _not_ work recursively would require adding complexity. We'd have to add special cases to chip away at its basic meaning.

It's an extremely useful principle. Keep everything as simple as possible, but no simpler. The question at hand is whether non-transitive implication is *too* simple. I haven't (yet) seen a compelling argument that it is.

Stating that `@Implies` directly includes the listed annotations and stops is not adding complexity. The implementation would be a non-recursive iteration over a list, checking for contradictions. A recursive implementation with a priority resolution algorithm would necessarily be more complex.

> This may be an underlying difference between us here. To you this looks like an advanced feature, but to me implication simply _is_ transitive and trying to fight against that is what's more advanced.

When I look at transitivity, I don't see an "advanced feature", I see a "feature with potentially negative net cost-benefit". I hope you can see that "implication simply _is_ transitive" is a personal opinion, not an objective fact.

This is a practical, not ideological matter for me. I do not offer any opinion whether implication _is_ or _is not_ inherently transitive, nor do I think answering that question is necessary to determine whether the _initial release_ of JSpecify should have transitive implication. By all means, if there's demand for it, add transitivity later, once there's time to see how JSpecify is used by real-world projects of varying size, organization and complexity.

I think there is a purely practical issue, which is that transitive implication is likely to be a  boondoggle, *especially* for a project so reluctant to prescriptively define tool behavior. Over-complicated and under-specified features are a recipe for incompatibility, confusion, and bugs.

> > * Any project should define its aliases in one place, which makes keeping them in sync straightforward.
> > * Projects shouldn't define more than a handful of default sets, or the benefits of consistent defaults disappear and they might as well use individual annotations.
> > * Defaults shouldn't change often, or again, the benefits of consistency disappear.
> 
> I don't think we can be so sure yet what the "shoulds" surrounding use of this annotation are. It just means what it means and people will use it in ways we can't predict.

Saying "it just means what it means" seems premature in a discussion of precisely _what_ something means. Why define transitivity at all (especially when it can be added later) right now, when the use cases for it are so unclear?

Consider a project that defines dozens of implication annotations in varying places that change frequently. One of two things is either going to happen: Massive confusion and bugs, or the annotations are highly localized in scope. If they're highly localized, they can be defined explicitly and don't need to be transitive.

> > * Recursive annotations create enormous potential for "action-at-a-distance" bugs where a change in one place breaks things far away.
> 
> More generally, adding `@Implies(One.class)` to `Two` (or upgrading a library that made that change) is already an unprecedented way to apply `@One` to a large number of call sites all at once. Anyone doing that should reanalyze those files and tweaks might be needed. This just seems like how changing a library works. To make a more graceful path we need to get back to topics like #26.

I agree with this statement, not only because it reinforces my concern that transitivity will not be useful in practice. If an annotation has a fixed set of implications which do not change, then those implications can be listed explicitly with no loss of functionality.

> With recursion, those call sites can be a mix of some that say literally `@Two` and some `@Three`, but does this really change matters much?
> 
> > If recursive annotations can never change without widespread breakage (see previous points)
> 
> For now I consider this an "n/a" (as just covered)
> 
> > * [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it). Forbid recursion at first and add it **if** a hugely compelling real-world use-case turns up.
> 
> This is trying to wield YAGNI like a blunt hammer. It's a guideline that applies where it applies and doesn't where it doesn't. Without regard to this particular decision, here are some criteria for when it applies:

It's a general principle that helps reduce scope creep. Yes, it can be taken too far. I don't think being reasonably cautious in the design of a public API that is intended to be used throughout the Java ecosystem is taking it too far.

>     * It's really a binary decision
> 
>     * The "It" is actually harder to do than not do
> 
>     * It's clearly safe to add later compatibly (we have to think through that transition cleanly; it's sometimes not enough to just throw up a wall saying "just forbid now")

All of these things are true of transitivity. It's a binary decision, it's harder to do than not do (in terms of specification, implementation, and documentation work required), and it's safe to add later compatibly. Absolutely nothing changes when transitivity is introduced until someone creates and uses a transitive annotation, which can be done incrementally.

The only risk I see is that there's such enormous demand for transitive annotations that multiple incompatible implementations will appear before JSpecify can add them. Do you think that's particularly likely?

> 
> And there are wants as well as "needs". Features that help adoption happen more smoothly or make more users want to adopt are strong wants.

I agree fully.

> Is there any particular stake you have in which way we go here? Does this decision have some impact on you that we don't know? If so, could we talk about that? Respectfully, the strength of your arguing ("hugely compelling real-world use-case") just seems disproportionate to the strength of your arguments, so far.

Yes. Simplicity and usability are my strong wants. I want JSpecify to be simple and usable enough for everyone, not a hodgepodge of half-baked features, each of which _might_ be useful to someone. I don't think anyone wants to adopt the C++ approach of "implement every idea, some of them will turn out to be good" which results in every project having a long list of prohibited features and APIs.

Hypothetically, if I were in charge of a project that used JSpecify, and JSpecify had transitive inclusion, then I'd create such a list for my project in order to prohibit transitive inclusion. A step in the wrong direction, in my opinion.

**Comment by cpovirk** [comment]
A way that I was thinking about this discussion was "Implication is transitive, but who says that the feature users need is 'implication' as opposed to something else?"

My feeling is that transitivity makes sense for the specific use cases we've had in mind, but I grant that this feature has been _relatively_ hypothetical in comparison to many others.

An example use case I think of is this: We define Nullable. Maybe another library defines PolyNull, declaring that it implies Nullable. Then someone else defines a _declaration_ version of PolyNull that implies the main one (because they can't use type-use annotations). They'd like for tools that don't understand PolyNull to still treat it like plain old Nullable.

If the use cases we _actually_ see are more like the monstrosities I've been dreaming up on some of these threads, that would be unfortunate.

**Comment by Mooninaut** [comment]
@cpovirk I think that's a great example. In my vision, there are two kinds of annotations. There are _semantic_ annotations that mean things in and of themselves, and there are _grouping_ annotations that simply group semantic annotations and have no meaning other than what they imply.

So you can have (names are extra-verbose for clarity) `@interface @NonNullSemantics`, `@interface @PolyNullSemantics`, and `@Semantics(NonNullSemantics.class, PolyNullSemantics.class) @interface @PolyNull`.

Yes, there is an extra @PolyNullSemantics class compared to the transitive `@interface @NonNull`, `@Implies(NonNull.class) @interface @PolyNull`. But I think that's a relatively minor cost for the additional clarity, orthogonality, simplicity of implementation, and self-documenting quality that a flat structure brings.

No need for transitivity. Where you would use a transitive `@Implies`, pull the list of arguments from the parent.

**Comment by Mooninaut** [comment]
So they could write annotate their `@Nullable` with `@Semantic`, couldn't they?

```java
package org.existing.api;

@Semantic(extend = dev.jspecify.Nullable)
public @interface Nullable { }
```

I don't want to beat a dead horse, but I still haven't seen a concrete example that requires full transitive multiple inheritance/implication.

**Comment by netdpb** [comment]
OK. Would this be an error, in your thinking?

```
@interface A {}

@Semantic(extend = A.class)
@interface B {}

@Semantic(extend = B.class)
@interface C {}
```

That is, would `@Semantic` disallow multiple levels?

**Comment by Mooninaut** [comment]
@netdpb That would not be an error.

I have settled on there being one transitive but single-inheritance annotation and one multiple-inheritance but non-transitive annotation. I think that provides a good balance of power without inviting the potential chaos that a multiple-transitive annotation could bring.

**Comment by netdpb** [comment]
**Current decision**: Because we are not planing to support annotation implication in 1.0 (#35, #307), this issue is not relevant for 1.0.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.
