### ISSUE TITLE
How to address the `@Nullable @NonNull` problem [working decision: no precedence]

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#242]
We might discover both `@Nullable` and `@NonNull` on the same API element. (I am not including other cases like `@Nullable int` or when these two annotations get pulled in by `@Implies` here.)

I think we said "we don't care what happens" in #100. But ideally its meaning would be deterministic. Then:

- if this is found in a _dependency_, a tool knows what it communicates
- If this is found in code under _analysis_, a tool knows what fix to suggest to preserve behavior

Here's a weak sauce proposal:

**When seen in analyzed code**

- Determine whether either or both is "unrecognized", without regard to the other. If so, we're done.
- If one of them is determined "redundant", upgrade that to "unrecognized".
- Otherwise deem them both unrecognized.

**When seen in a dependency API**

- As always, just ignore anything that's unrecognized? (according to the recipe just above)

By spelling it out like this I may have made it look more complex than it is?

Thoughts?

(If nay on #230 then this issue goes away.)

**Comment by cpovirk** [comment]
> By spelling it out like this I may have made it look more complex than it is?

That... is possible :)

> - Determine whether either or both is "unrecognized", without regard to the other. If so, we're done.

i.e., only the "recognized" one matters; "drop" the other. Not sure if we have a concrete example of this (where an annotation is applicable in a location but its "inverse" is not?), but it seems fair to say that anything unrecognized would have no effect.

> - If one of them is determined "redundant", upgrade that to "unrecognized".

i.e., if you see `@Nullable @NonNull Object o;` inside `@NullMarked`, then "drop" `@NonNull`, leaving `@Nullable`?

Observation: _not_ true of `@Nullable @NonNull T t;` inside `@NullMarked`, since `@NonNull` is not redundant there... unless `T` is defined to be bounded to non-nullable types, in which case it _is_ redundant and so the rule _would_ apply.

Hmm, that makes this whole bullet feel like a non-starter to me: If we need to look at the bound of `T` in order to understand _what an annotation on `T t` means_, then I worry that we don't have clear "levels" in our system: I would like to think that we could know what all the annotations "mean" before we get as far as looking at bounds. (Maybe my hope is naive, thanks to Valhalla or something?)

> - Now deem them both unrecognized?

i.e., `@Nullable @NonNull Object o;` has unspecified nullness inside unmarked code and is non-nullable inside marked code

---

As discussed elsewhere, though, I do think I'm a fan of specifying how to interpret "contradictions." I'm mainly nervous about that second bullet.

**Comment by cpovirk** [comment]
As a counterproposal, I would keep:

> - Determine whether either or both is "unrecognized", without regard to the other. If so, we're done.

And then I could see either having the only remaining step be...

> - Now deem them both unrecognized?

...or else establishing a priority order among each "set" of annotations. But that latter option sounds like work, so I think I'd stick with "both unrecognized."

**Comment by kevinb9n** [comment]
Consider the proposal so revised!

So this seems pretty simple now. No precedence, so if two or more remain, they all have to go.

On the handling of "unrecognized" in general (which doesn't really belong here, but just to check that we're thinking similarly): A tool should draw no conclusion from the presence of an unrecognized annotation except just "there is an unrecognized annotation here". That leaves it free to error/warning/do-nothing in the analyzed-code case and in the dependency case, and I think that's good. (We certainly would _like_ it to at least warn for analyzed code.)

From my perspective this would resolve this issue.

**Comment by kevinb9n** [comment]
We agree! Since this is a pretty fine-grained unimportant issue I'm gonna just optimistically close it.

**Comment by kevinb9n** [comment]
Needs a very careful review. Reopening.

### Detailed proposal

Defined only for the case of N=2 conflicting annotations.

* First, any individual annotation might be deemed "unrecognized" on its own demerits, disregarding other colocated annotations. Such cases should be addressed as usual.
* Next, if *neither* conflicting annotation was dropped from consideration (deemed "unrecognized") in the first stage, then *both* are now deemed unrecognized (same as if they had failed the first stage).
* Those rules, as they apply to our annotation `@X`, apply equally to an annotation `@ImpliesX` (which, of course, implies `X.class` directly or indirectly via `@Implies`).
* The concept of redundancy applies only to recognized annotations, and only to specific annotations it is defined for (not to annotations that imply those annotations).
    * (If #233, then redundancy does apply selectively: iff `@ImpliesX` (and every intermediate implied annotation until `@X`) is marked as a pure alias.)
* An unrecognized or redundant annotation carries no (new) nullness information, so it has no effect beyond those discussed above. For example, when null-analyzing dependent code, it is as though the annotation was simply not there.
* (If, in the future, there is a meta-annotation `@Negates(X.class)` or `@DisjointWith(X.class)`, these rules would apply to any pair of annotations so linked.)

### Code examples/expectations

```
// Anywhere, @X can instead be @ImpliesX; same effect except no "redundant" findings

@NullMarked class Marked<T extends /*bound of either nullness*/> {

  @Nullable int i1; // unrecognized because language wins (redundancy N/A)
  @NonNull int i2; // recognized; redundant
  @Nullable @NonNull int i3; // (ignoring order) @Nullable unrecognized; @NonNull recognized/redundant

  @Nullable String s1; // recognized; not redundant
  @NonNull String s2; // recognized; redundant because null-marked context
  @Nullable @NonNull String s3; // both unrecognized (redundancy N/A); s3 is non-null

  @Nullable T t1; // recognized; not redundant
  @NonNull T t2; // recognized; redundant *iff* T is non-null-bounded
  @Nullable @NonNull T t3; // both unrecognized (redundancy N/A); t3 is unprojected

  @NullUnmarked nested1; // recognized; not redundant
  @NullMarked nested2; // recognized; redundant
  @NullUnmarked @NullMarked nested3; // both unrecognized; nested_element3 is null-marked
}
```

**Comment by netdpb** [comment]
> The concept of redundancy applies only to recognized annotations, and only to specific annotations it is defined for (not to annotations that imply those annotations).

This issue is about conflicting annotations, not redundant ones. Why is "the concept of redundancy" relevant in this bullet? Can the example code be simpler by dropping references to redundancy, and dropping APIs without conflicting annotations?

```
@NullMarked class Marked<T extends /*bound of either nullness*/> {
  @Nullable @NonNull int i; // @Nullable unrecognized; @NonNull recognized
  @Nullable @NonNull String s; // both unrecognized; s is non-null
  @Nullable @NonNull T t; // both unrecognized; t is unprojected
  @NullUnmarked @NullMarked nested; // both unrecognized; nested is null-marked
}

@NullUnmarked class Unmarked<T> {
  @Nullable @NonNull int i; // @Nullable unrecognized; @NonNull recognized
  @Nullable @NonNull String s; // both unrecognized; s is unspecified
  @Nullable @NonNull T t; // both unrecognized; t is unprojected
  @NullUnmarked @NullMarked nested; // both unrecognized; nested is null-unmarked
}
```

**Comment by kevinb9n** [comment]
I'm simply trying to be generous with context, so everything is abundantly clear. If anyone raises *issues* about those things we'll peel them off.

**Comment by cpovirk** [comment]
> * Those rules, as they apply to our annotation `@X`, apply equally to an annotation `@ImpliesX` (which, of course, implies `X.class` directly or indirectly via `@Implies`).

That phrasing suggests to me that, if I annotate something with `@NotX @ImpliesXAndY`, then we see a conflict between those two annotations and drop them both.

I had been thinking of a model more like this: A checker first "expands" `@NotX @ImpliesXAndY` into `@NotX @ImpliesXAndY @X @Y`. _Then_ it starts trying to resolve the conflicts. The result is that it drops `@NotX` and `@X`, leaving `@ImpliesXAndY @Y`.

Is either of those models similar to how you're thinking about it?

**Comment by netdpb** [comment]
> I had been thinking of a model more like this: A checker first "expands" `@NotX @ImpliesXAndY` into `@NotX @ImpliesXAndY @X @Y`. _Then_ it starts trying to resolve the conflicts. The result is that it drops `@NotX` and `@X`, leaving `@ImpliesXAndY @Y`.

The problem with that is that `@ImpliesXAndY` still imples `@X`.

Perhaps instead of talking about conflicts between _annotations_, we should talk about conflicts between _nullness operations_.

1. After dropping unrecognized annotations, you're left with a few.
2. From each one you derive either `UNION_NULL` or `MINUS_NULL` (or neither; or both could be implied by one annotation).
3. Now you have a set of operators to apply to the type component.
4. If the set of operators includes both `UNION_NULL` and `MINUS_NULL`, then you have a conflict and you ignore both operators.
5. If you report a problem, you can report all the annotations that contribute either operator.

**Comment by cpovirk** [comment]
> The problem with that is that `@ImpliesXAndY` still implies `@X`.

Right, that kind of thing, generalized than nullness operators. We need to formalize the concept of "If a tool asks 'Is `@X` applied at this location?' then what do I say?" So, to restate the steps more precisely, or at least _way_ more verbosely:

1. `@NotX @ImpliesXAndY` is what is written in the source code.
2. `non-transitive-meaning-of-@NotX non-transitive-meaning-of-@ImpliesXAndY non-transitive-meaning-of-@X non-transitive-meaning-of-@Y` is the transitive closure of that.
3. `non-transitive-meaning-of-@ImpliesXAndY non-transitive-meaning-of-@Y` is what we get after discarding conflicts.

Then, the answer to whether `@X` applies at that location would be "no," since `non-transitive-meaning-of-@X` is not part of that last line.

We'd need tools to consistently follow this model: They should never ask "Is `@ImpliesX` applied at this location?" and then conclude based on that that `@X` is applied, too.

There's obvious potential for trouble here if tools do it themselves and do it wrong. But I'm not sure there's any _less_ potential for trouble if we pick a _different_ model and tools try to do _that_ one themselves. That may be the best we can hope for :)

(We could use some better terminology around all this.)

Anyway... the other half of the question I was trying to get at is whether **`@Y`** is considered to be applied in my example: If `@ImpliesXAndY` as a whole is "cancelled" by `@NotX`, then no; if only the `X` aspects of `@ImpliesXAndY` are cancelled, then yes.

**Comment by netdpb** [comment]
Hmm. Are we trying to address the general problem of conflicting annotations in the presence of `@Implies` across all potential annotations and their semantics? Or are we trying to address the specific null/non-null and null-marked/null-unmarked problem?

Or do we think any valid solution to the latter will also solve the former?

**Comment by netdpb** [comment]
But I think I agree with how you're thinking about it: If "the nontransitive meaning of `@ImpliesXAndY`" is anything at all, it's what applies. And practically, you could model a tool as saying that normally `@ImpliesXAndY foo` is observed as `@ImpliesXAndY @X @Y foo`, and in the case of `@NotX @ImpliesXAndY bar` it's observed instead as `@ImpliesXAndY @Y bar`; and in both cases tools should not impute `@X`-ness or `@Y`-ness to `foo` or `bar` only because of the presence of `@ImpliesXAndY`.

**Comment by kevinb9n** [comment]
> I'm simply trying to be generous with context, so everything is abundantly clear. If anyone raises _issues_ about those things we'll peel them off.

Well, then a discussion flared quickly before I could get back here and say "let's peel off the issue with `@Implies`."

But let's do that now.

**Comment by kevinb9n** [comment]
The only discussion since my proposal has been about `@Implies`, which I peeled off, so I think we're good here, decision-wise.

**Comment by netdpb** [comment]
**Current decision**: Disregarding implied annotations, if two contradictory annotations annotate the same type usage (`@Nullable @NonNull Foo`), then both are ignored as irrelevant.

**Argument for changing**: No strong case.

**Timing**: This must be decided before version 1.0 of the spec.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by kevinb9n** [comment]
To be clear, we mean when analyzing *dependents* of the errant API the annotations are classified as irrelevant/unrecognized/meaningless*. When that signature itself is being analyzed it would certainly produce an inference.

* what word _did_ we decide on...

**Comment by netdpb** [comment]
> To be clear, we mean when analyzing _dependents_ of the errant API the annotations are classified as irrelevant/unrecognized/meaningless*. When that signature itself is being analyzed it would certainly produce an inference.

I don't think we need to distinguish at this point. Our conformance tests will check an assertion on source that contains unrecognized annotations, and they will check assertions about usages of symbols with such annotations as well.

**Comment by netdpb** [comment]
**Decision**: Disregarding implied annotations, if two contradictory annotations annotate the same type usage (`@Nullable @NonNull Foo`), then both are unrecognized.

**Comment by kevinb9n** [comment]
That is fine but we do need a definition of "unrecognized" somewhere. The idea is that an unrecognized annotation should be completely ignored... except for the purpose of reporting "there is an unrecognized annotation here"!
