### ISSUE TITLE
`@NonNull` on local variable root type? (yes/no/checker-dependent)

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#251]
BACKGROUND

This assumes our current approach toward local variables: because a checker can and should track the changing nullness of a local variable flow-sensitively, <insert explanation 1 or 2 here>

(1) the local variable's root _type_, being a mere static type, has to be the more general one: nullable. What the flow analysis does is explained as "type sharpening" (like "smart casts") which is general to more than just local vars.

OR

(2) the local variable's root _type_, being a mere static type, is unchangeable while the variable itself may go through different nullness states, so the _type_ doesn't benefit from declarative nullness and so doesn't participate in it.

That being established,

FEATURE REQUEST

It is reasonable to want to apply `@NonNull` to a local variable root type, so that you can get a warning *right away* any time a nullable expression is assigned to it.

Without this, a checker will just infer the type to be nullable, and you'll still get a warning if and only if you try to _use_ its value for some non-nullable purpose. That is, this FR isn't about preventing a bug, just reporting it closer to where it happened based on extra "hints/assertions" from the developer.

[EDIT: msridhar discusses a possible second use case below.]

THE QUESTION

Will our specification _require_, _permit_, or _prohibit_ a checker to support this usage?

REQUIRE?

I don't see a strong case for this. Making sure that impl code is portable when moving from one checker to another has always been an explicit non-priority compared to the importance of nailing down APIs. Tenatively assuming we're not going with this option then I'll contrast the other two.

PROHIBIT?

One reason to prohibit would be if we thought different checkers might actually assign different meanings to this same usage, but I can't really see that happening here.

My bigger concern is that even just permitting this usage somewhat forces us into explanation (1) above and forces us to say "nullable _by default_ but you can override it", and the massive problem with that is it's completely _backwards_ to how things work for API types. So, prohibiting this *might* help us maintain conceptual simplicity of the overall model. (That said, Chris prefers (1) anyway?)

The impact on e.g. eisop users would be that when they want to use this pattern they will have to revert to a tool-specific `@NonNull` annotation. That's... not pretty but maybe livable. (Hopefully theirs would at least `@Implies` ours so that a file never strictly needs to mix both.)

PERMIT?

I don't love this option, but we could do it especially if >= 2 tools want to support this.

A problem I have with it is: what does the `@NonNull` javadoc say, then? It really wants to say definitive things like "means X in Y situation, has no meaning in Z situation", but it's awkward to say "it might have meaning or it might not". Particularly because I doubt we could get away with _categorically_ saying that about all implementation-code concerns.

Also, as mentioned, even just permitting it somewhat undercuts our ability to lean on explanation (2) at top.

Also, now there'd be a decision users have to make, and have to debate with reviewers: when exactly is it worth using this? Some users might want to always use it; some maybe only if the var is non-final, or only if it's assigned at least 3.4 times, etc. etc. All over what seems like a very slight benefit. I'd kind of rather spare people from this.

**Comment by kevinb9n** [comment]
Soliciting thoughts from tool owners @artempyanykh @msridhar @lazaroclapp @wmdietl @akozlova; seems pretty related to the other issue #252 .

**Comment by msridhar** [comment]
Coincidentally I opened https://github.com/uber/NullAway/issues/561 a few months ago.  Interestingly, the motivation there was different (allowing for a more localized warning suppression in some cases).  Choosing "permit" does raise some questions, but I would like to keep the option open to support `@NonNull` on locals in NullAway in the future.

**Comment by cpovirk** [comment]
Thanks, @msridhar, that's interesting.

In Guava, I've used the approach of extracting a method that returns `null` as a member of any type. That lets me suppress the warning at the level of that one-statement method, after which code can write something like "`unsafeNull()`" without further ceremony:

- https://github.com/google/guava/blob/e06a8cec65815599e510d7f9c1ea9d2a8eaa438a/guava/src/com/google/common/util/concurrent/AbstractFuture.java#L593
- https://github.com/google/guava/blob/e06a8cec65815599e510d7f9c1ea9d2a8eaa438a/guava/src/com/google/common/collect/CompactHashMap.java#L949

One thing that I don't love about my approach is that the `null` has to cross method boundaries: In my dreams, I still want to make it possible for at least some users to use a bytecode rewriter that checks at runtime that methods never return `null` when they shouldn't—and of course `unsafeNull` could run afoul of that. But if such a tool were ever to exist, it would surely need to make a zillion exceptions, anyway. In fact, it would need to make an exception in an example similar to yours, in which a caller wants to pass `null` to a method that is declared not to accept it. And that exception needs to exist regardless of whether the caller uses `unsafeNull` or `@NonNull Foo foo = ...`.

One thing that I do like about the approach of a separate method is that it can be used to "cast" type-variable usages from `@Nullable E` to plain `E`. In that case, it's not quite right to write `@NonNull E e = ...` because the value might not actually be non-null. Then again, `@NonNull E e = ...` is likely to be harmless, especially since the hack doesn't cross method boundaries like mine does.

(Besides the `@NonNull Foo foo = ...` approach and the `unsafeNull()` approach, there's also the `(@NonNull Foo)` cast approach that @kevinb9n mentioned [above](https://github.com/jspecify/jspecify/issues/251#issuecomment-1205405260).)

**Comment by msridhar** [comment]
@cpovirk that's a nice trick!  Is there a reason you used [`unsafeNull`](https://github.com/google/guava/blob/e06a8cec65815599e510d7f9c1ea9d2a8eaa438a/guava/src/com/google/common/collect/NullnessCasts.java#L63) as the name for the method in one place and [`uncheckedNull`](https://github.com/google/guava/blob/e06a8cec65815599e510d7f9c1ea9d2a8eaa438a/guava/src/com/google/common/util/concurrent/NullnessCasts.java#L71) in the other?  In any case, I'm open to the argument that the `unsafeNull()` method is a better way to do the targeted suppression ([this comment](https://github.com/google/guava/blob/e06a8cec65815599e510d7f9c1ea9d2a8eaa438a/guava/src/com/google/common/collect/NullnessCasts.java#L42-L51) nails it), so maybe that's not such a great motivator for `@NonNull` on locals.

**Comment by cpovirk** [comment]
I think the idea was that [the usage of `uncheckedNull`](https://github.com/google/guava/blob/e06a8cec65815599e510d7f9c1ea9d2a8eaa438a/guava/src/com/google/common/util/concurrent/AbstractFuture.java#L593) was always actually "correct": `getDoneValue` would return `null` only for an `AbstractFuture<@Nullable Something>`. However, [the usage of `unsafeNull`](https://github.com/google/guava/blob/e06a8cec65815599e510d7f9c1ea9d2a8eaa438a/guava/src/com/google/common/collect/CompactHashMap.java#L936) (oops, I should have linked a different usage above—now fixed) could actually return `null` from an `Entry<K, @NonNull Foo>` (albeit only in case of "undefined behavior"). It is a picky distinction that is unlikely to matter to anyone ever :)

I should note that I don't have a strong opinion about `@NonNull` on local-variable root types, or if I do, I can't remember what that opinion is :)

**Comment by artempyanykh** [comment]
We don't support root nullness annotations on locals in Nullsafe. For localized suppressions we use:
1. methods a-la checkNotNull(...) that assert nullness,
2. methods a-la assumeNotNull(...) iow. an unchecked type-cast,
3. magic comments of the form `// NULLSAFE_FIXME[<issue_types>]: <explanation>` which work in situations where the required suppression isn't on an expression level.

A more localized error detection is nice but allowing `@NotNull` on locals opens a new can of worms and I'm not sure it's worth the hassle. So, far we have only a handful of `@NotNull` in the codebase and will likely keep it this way.

**Comment by kevinb9n** [comment]
Good; I'd like to rule out "REQUIRE" and focus on the decision between "PERMIT" and "PROHIBIT".

And I'll propose we resolve for "PROHIBIT":

First a reminder that "PROHIBIT" really means that if you want to support it then the user has to drop down to a checker-specific annotation (which should have `@Implies(org.jspecify.nullness.NonNull.class)`). And I do recognize some downsides to this:

* To the user who values this use case highly, this arrangement would feel quite unfortunate.
* If a tool ends up preserving their own custom `@NonNull` annotation in perpetuity for this reason alone, that also feels quite unfortunate.

However, I think it buys us a lot:

* A user can learn JSpecify fully without having to deal with this particular feature. It lets JSpecify be both simpler and more precise.
* When encountering a usage of this particular feature, the user can view the annotation's javadoc and actually expect to find an explanation. This is the kind of firm bond between annotation and semantics we are trying to achieve in this project.
* It would be much easier to switch to PERMIT later than the other way around.
* It's cleaner to have a single list of all the circumstances where both jspecify `@Nullable` and jspecify `@NonNull` are "inapplicable" / "have no defined meaning".

In fact, the current docs I've written do have that single shared list, and I'm proposing to keep them that way by resolving this for "PROHIBIT".

Being merely a "working decision" I'll close this if I don't hear from anyone soon.

**Comment by cpovirk** [comment]
I think that's fine but would highlight one thing for the record: To get the _full_ benefits here, what we need is not just for JSpecify to prohibit annotations on local-variable root types but _for tools to implement that prohibition_. Otherwise, we end up with a scenario in which, from the perspective of users, `@NonNull` _does_ (to _some_ tools!) apparently have semantics, which are undocumented. That's a lot like "permit" but in some ways worse.

Really, my point is just the usual one that "prohibit" means only so much when tool authors are the ones implementing the prohibiting or permitting. And _some_ tools already permit annotations on local-variable root types, and they're not necessarily going to go to the effort of making an exception for JSpecify annotations. We can of course encourage them to! And it's a _big_ help that at least a couple tools _don't_ currently permit annotations on local-variable root types (or at least don't do anything with them if they see them?). Plus, another tool, Kotlin, doesn't look at the nullness of Java local variables to begin with.

_If_ we found ourselves in a position in which many tools already supported JSpecify nullness annotations in a location where we'd prefer they not support them, _then_ we'd have a more interesting decision. For example, I might want to prioritize pushing tool authors to stop recognizing `class Foo<@Nullable T>` before pushing them to stop recognizing `@Nullable` on local variables. But given that there aren't a huge number of tools that support annotations on local-variable root types already, _and_ given that we're talking about local variables (not APIs), _and_ given that annotations on local-variable root types are relatively rare in existing code anyway, I don't think we need to be too worried here.

**Comment by kevinb9n** [comment]
I'm hoping the test suites help. We should apply ongoing gentle pressure toward passing them. And to do so a tool will have to have *some* code path that correctly demonstrates that `Foo<@Nullable T>` has no apparent effect except for a finding about the annotation being out of place. Then for the tool to keep respecting that anyway, at least it should have to do something fairly hacky to get there. That's a start. To the extent we find out such hacks exist, we can continue with the ongoing pressure thing.

It's worth noting that we'll have much more motivation to push on such issues for `Foo<@Nullable T>` than for anything API-invisible like this issue describes. The API cases go against the stated objective we've had since the beginning (API owners have one tool-neutral way to annotate their code). This... well, I feel like as long as our specs can provide a clear unambiguous "yeah they're not supposed to do that", then we've done our job, and I won't lose too much sleep over those that are doing it anyway.

**Comment by kevinb9n** [comment]
"PROHIBIT" might be the wrong word, compared to, like "DENIGRATE"...

**Comment by kevinb9n** [comment]
I think it's fair to make a working-decision that JSpecify declare `@NonNull` to have no meaning in these locations just like `@Nullable`. It can always be reopened by a motivated party.

**Comment by cpovirk** [comment]
(I started to claim to someone today that an explicit _`@Nullable`_ could be useful to tell a checker "While I'm initializing this variable to a value with unspecified nullness, I want you to treat it as nullable." But in fact, I would expect the sort of "type sharpening" discussed above to kick in and treat the variable as if it _still_ has unspecified nullness. So that is actually of no help. To get help, you'd want a _method_ that converts the value to a nullable type (another thing that a JSpecify runtime jar could theoretically supply if we wanted to go that direction, which probably we don't)—or, you know, to annotate the API that you got the value from :))

**Comment by netdpb** [comment]
**Current decision**: Local variable root types are very much "implementation code", and tools will be able to derive (and refine) the nullability of the root type component without annotations. For consistency, JSpecify does not allow `@Nullable` or `@NonNull` in those locations.

**Argument for changing**: It might be nice to allow some tools to interpret these annotations in those locations for their own non-portable purposes.

**Timing**: This must be decided before version 1.0 of the spec.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by netdpb** [comment]
**Decision**: JSpecify does not allow `@Nullable` or `@NonNull` on local variable root types. They are allowed on other type components (including wildcard bounds and non-wildcard type arguments).
