### ISSUE TITLE
Decide javadoc permalink

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#277]
Decide javadoc permalink. Until then it is at mumblemumble-"nolink".

**Comment by cpovirk** [comment]
I've been happy with the _short links_ at https://guava.dev/api and https://truth.dev/api, but the paths that those redirect to are not consistent across the two projects :\ The `api` directory seems like a reasonable place to put things under, I guess?

But we do have jspecify.org/docs/various-things, so there would be some sense in jspecify.org/docs/api, too.

Should we publish a separate directory for each version, should do we have just one, which is always the latest? I'd love to convince myself that we can get by with just one: We know that there are many links to old versions of the Guava Javadoc that will hang around forever. People who really do want a particular version can probably get javadoc.io to generate it for them, but most people will probably be happy with `@since` tags and a policy of never removing anything. The main thing to offer for may be "latest release" vs. "snapshot," where the snapshot may contain unrelated stuff... which most people probably don't care about, so the snapshot Javadoc could live somewhere less prominent.

**Comment by kevinb9n** [comment]
Yes, I like the idea that there are at *most* two versions with any useful value: snapshot and latest, both at stable URLs. If any jspecify javadoc link anywhere on the web ends up linking to the version 1.1 docs specifically... I just see almost no benefit to that. It seems unlikely that a user would be able to tell which older release is the right one to consult, anyway. Better to have the newest, and let `@since` tags warn you about things you might not have yet.

Then the question would be if we even need the latest-release one at all. That the snapshot can include unreleased things (a) is often desirable and (b) most problems are once again addressed by `@since` tags (`@since NEXT`?). Okay, the snapshot might be slightly volatile -- have a typo for a couple days, etc. The release is _less_ likely to. But is that even worth the bother?

**Comment by cpovirk** [comment]
It sounds nice to be able to fix Javadoc typos (or even more significant problems) and have those fixes show up for users without needing a release. Not that releases are hard for us to do. But if we hit `jspecify-1.0.57` because we produce a bunch of releases on account of tiny Javadoc fixes, that's a _lot_ of Dependabot PRs and similar for users (plus some manual toil) that could have been avoided.

Granted, to actually get the fixed Javadoc in front of users' eyes in IDEs (or for those who direct reading the source code from the release they're using), we'd need, well, a release. Still, having the _option_ to fix something without a release seems like it can't hurt?

--

Alternatively: If for some reason people are worried about having only the snapshot docs, I could imagine having only the latest release docs instead. The snapshots are useful primarily to a smaller group of interested parties, so those people might be willing to generate it themselves. Now, we do hope that the group of interested parties continues to expand over time: In an ideal world, all JSpecify users could peek at the forthcoming features easily so that they could offer feedback. Maybe that outweighs the cost of seeing (to pick a hypothetical example) a reference to `@PolyNull` in the `@Nullable` documentation when `@PolyNull` isn't in a released artifact?

**Comment by kevinb9n** [comment]
First: it seems like we're fine to provide only snapshot docs for the foreseeable future, but have "room" for others.

Second: I suppose which subset of {"snapshot", "latest", numbered versions} we want to host is a question that's not specific to api docs but general to this whole tree:

* `./api`
* `./spec`
* `./user-guide` (probably)
* (maybe more)

So whichever of the following we provide probably wants to have that same structure:

* `jspecify.org/docs/snapshot/`
* `jspecify.org/docs/latest/`
* `jspecify.org/docs/1.0/`

If we like that enough to go ahead with `jspecify.org/docs/snapshot/api/` as the answer for this particular issue, that would close this. (If we change our minds later, I admit that breaking early permalinks is not the absolute worst thing in the world.)

**Comment by cpovirk** [comment]
First, I wonder if it's practical to leave the `docs` segment out. We didn't use to have it, and it came along during the Docusaurus transition, so we wouldn't be breaking much by removing it (assuming that that's not hard to get Docusaurus to do).

Second, especially when `snapshot` might be the only directory forever, it feels oddly prominent for it to be the first segment (well, "second segment" if we keep `docs` :)):

- `jspecify.org/snapshot/api`
- `jspecify.org/snapshot/spec`
- `jspecify.org/snapshot/user-guide`

An alternative would be something like:

- `jspecify.org/api/snapshot`
- `jspecify.org/spec/snapshot`
- `jspecify.org/user-guide/snapshot`

That said, we also still have the opportunity to define the kind of [short links I mentioned above](https://github.com/jspecify/jspecify/issues/277#issuecomment-1234789385), so maybe no one cares too much what the full URL looks like.

**Comment by kevinb9n** [comment]
> First, I wonder if it's practical to leave the `docs` segment out.

I do like it though! To group all the things that properly constitute "product documentation" and not things like the blog or a "status" page (maybe the design faq too).


> An alternative would be something like:
> 
> * `jspecify.org/api/snapshot`
> * `jspecify.org/spec/snapshot`
> * `jspecify.org/user-guide/snapshot`

This would suggest that individual documents (that aren't subtrees) become directories containing just "snapshot.md", which is odd.

Vaguely, it sorta "makes sense" to me that there is one snapshot of one complete picture, instead of lots of different things having their own independent snapshots.

But indeed, I don't love the idea of the user guide becoming 'jspecify.org/docs/snapshot/user-guide'. So, alternative: the directories with parallel structure (each containing `api`, `spec.md`, etc.) would be:

* `jspecify.org/docs/`
* `jspecify.org/docs/releases/latest/`
* `jspecify.org/docs/releases/1.0/`

And to reiterate, I don't propose to even create `releases` at all right now (possibly ever).

**Comment by cpovirk** [comment]
> I do like it though! To group all the things that properly constitute "product documentation" and not things like the blog or a "status" page (maybe the design faq too).

I think it would be OK to have both, e.g., jspecify.org/api and jspecify.org/blog: Having an additional level of the directory hierarchy under which we could classify some of those as "docs" doesn't seem necessary to me. And, to turn the package-name discussion back on you, are you looking forward to the debate about whether the design FAQ is a "doc" or not? ;)

All that said, `jspecify.org/docs/api`, `jspecify.org/docs/spec`, etc. looks good enough to me: I think that cutting `docs` would be an improvement, but if that doesn't resonate with anyone, I'm happy to drop it.

---

If we go with that, then we don't need to worry about the following for now, but, in case we come back to it....

> This would suggest that individual documents (that aren't subtrees) become directories containing just "snapshot.md", which is odd.

Ah, I had been figuring that they'd all become directories eventually, quite possibly with multiple pages ("nullness spec," "meta spec," ...) each or, if not, that we could still use "jspecify.org/user-guide/snapshot/" as the canonical URL (rather than "jspecify.org/user-guide/snapshot" (sans trailing slash))—compare "https://mail.google.com/mail/u/0/". Maybe that's not how things are typically done nowadays, though—I am far enough removed from web development that I don't even know what the tradeoffs are.

**Comment by kevinb9n** [comment]
I feel fine about jspecify.org/docs/api/org/jspecify/... and am trying to make that change.

**Comment by kevinb9n** [comment]
voilà https://jspecify.dev/docs/api/org/jspecify/nullness/Nullable.html
