### ISSUE TITLE
Support projects that want to ban `@NullUnmarked` in some way

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#280]
We view `@NullUnmarked` as being a transitional step. I doubt any new codebase would have cause to use it, nor would a codebase that already got itself migrated want to face backsliding.

So, I think that banning `@NullUnmarked` whenever possible will be a practice we heartily recommend. Yet it seems we're leaving everyone on their own to rig up some ad-hoc way to ban it on their own.

(Admittedly this is only half of the puzzle: such projects would equally wish for a way to ensure `@NullMarked` IS always used on every new (module/package/class, their preference). So what I list below are only partial solutions.)

One pretty severe idea is to banish `@NullUnmarked` and future others like it to a separate artifact! The package might be something like `org.jspecify.migration.*`. This of course lets the build configuration control whether to let it in or not.

Another idea is `@NullMarked(overridable = false)`. (If we wanted that to be the default behavior (?), we'd have to do this by 1.0; that's the only reason I conservatively set this issue as milestone=1.0.)

Since we're listing ideas, I guess I'll add `@BanWithinThisScope(NullUnmarked.class)`...

**Comment by cpovirk** [comment]
My assumption had been that support for this wouldn't come from JSpecify per se. I tend to think of something like a presubmit or pre-commit hook or, if there's support from a checker, support that's more configurable than we'd be able to offer. Let me see if I can figure out what was underlying that assumption....

First, the separate artifact is quite interesting! I probably wouldn't go that far, perhaps partially because "Add these _two_ dependencies for the full set of nullness annotations" sounds like an easy thing to make fun of, even if one of the artifacts won't be necessary for some projects :) Oh, and then it has to go in a separate package... and maybe we'd want a separate artifact for the "legacy" annotation for each of our other domains besides nullness.... Plus, there are build tools that don't enforce "strict deps," so, as soon as you have a dependency that uses `@NullUnmarked`, then everyone else can use it. Put all together, that's worse than I expected when I started writing this paragraph. The thing I'm actually planning to harp more on is the configurability argument.

One sort of configurability argument is this: `@NullMarked(overridable = false)` and `@BanWithinThisScope(NullUnmarked.class)` work if you can put those on every package (#34, #30, #221, sigh) or on every module (and my understanding is that module adoption isn't quite there yet). If you want to rely on that, you're probably going to want a way to _enforce_ that people include those annotations. That means writing external configuration to your checker or the other "enforcers" in your development environment. And if you're willing to do that, then you can just as well use those same tools to straight-up ban `@NullUnmarked`.

Then there's the main sort of configurability argument: How many people will be sure that they'll _never_ use `@NullUnmarked`? I'm sure there will eventually be a good number of people in that position, but I would expect a common other need to be "no `@NullUnmarked` except in this set of locations that Team X has audited." That's not something that a JSpecify annotation is likely to support well.

Another possibility is that some people will want warnings for `@NullUnmarked` and others will want errors. That is of course the kind of configuration that a checker can offer for `@NullMarked(overridable = false)` and `@BanWithinThisScope(NullUnmarked.class)`. But it's another reason to feel that JSpecify could solve only a portion of this problem, likely having to answer a number of questions about potential features along the way. So we could end up with `@NullMarked(overridable = false, butAllowSuppressionOfThat = true)`, and then our rules need to specify what to do with `@NullMarked(overridable = false, butAllowSuppressionOfThat = false)` inside that scope, and... it's probably all manageable, but it doesn't feel worth pursuing to me unless I'm being overly pessimistic about the usefulness of the feature.

**Comment by msridhar** [comment]
I personally don't think we have a strong need for this in the JSpecify spec.  I agree with @cpovirk that users will want configurability of these bans, and needing to implement such configurability within JSpecify-compliant checkers will add complexity.  IMO, clear documentation about the intent of `@NullUnmarked` is good enough, and bans can be enforced by other linters / checkers.

**Comment by kevinb9n** [comment]
I think we can rule out the separate migration-support artifact:

* It won't play well; will make JSpecify look more like a "pain" in general.
* When people hit a snag in migration, we want it to be *easy* to reach for `@NullUnmarked`.

I think we can rule out `@NullMarked(overridable = <boolean>)`:

* It's only a partial solution anyway.
* It doesn't actually communicate information *about the code*, which is JSpecify's purpose.
* It seems to have no good choice for default value.

I think we can rule out `@BanWithinThisScope(NullUnmarked.class)`:

* It's only a partial solution anyway.
* It doesn't actually communicate information *about the code*, which is JSpecify's purpose.
* It lacks release pressure: it could always be added compatibly later. In such cases there is little sense in trying to predict its value.

In general, any scheme for how projects can enforce annotation usage policies:

* Can't logically be purely annotation-based
* Doesn't need to be married to JSpecify in any way

This issue was a bit of a time-waster, but if the arguments above seem valid then I at least see some potentially reusable principles here.

**Comment by netdpb** [comment]
**Current decision**: This feature is not required for JSpecify 1.0.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.
