### ISSUE TITLE
Publish 0.3.0-alpha-1 release

### ISSUE THREAD

**Issue by netdpb** [jspecify/jspecify#298]

**Comment by cpovirk** [comment]
https://github.com/jspecify/jspecify/tree/v0.3.0-alpha-1

https://github.com/jspecify/jspecify/releases/tag/v0.3.0-alpha-1 (to be filled in)

https://repo1.maven.org/maven2/org/jspecify/jspecify/ (The 0.3.0-alpha-1 directory should be appearing soon; I already closed and released in the Sonatype UI.)

The other task here is to revise and expand the instructions linked above. I may open a separate issue for that so that I can close this one when the details above are done.

**Comment by netdpb** [comment]
@msridhar, please let us know if you can use this.

**Comment by cpovirk** [comment]
(You may soon see https://github.com/jspecify/jspecify/issues/302 if you haven't already :) I will reply there, hopefully shortly.)
