### ISSUE TITLE
@NullMarked (and its negation) to include module and package targets

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#34]
Filing this so we can punt on it. [edit: haha no]

Trying to accommodate package- or module-level defaults is fraught with issues, so for now, we are going to require an annotation like `@DefaultNotNull` to appear on every class.

We know people aren't going to like this. So this issue is about continuing to try to figure something out eventually.

**Comment by artempyanykh** [comment]
> I think we are pretty certain now that the answer to the question asked by the summary line of this issue "yes, absolutely". Do we need to keep this issue open?

@kevinb9n could you perhaps elaborate on this? From the discussion I see a number of issues mentioned re: package level defaulting annotations but not much about pros besides the implicit "ease of bulk-annotating classes".

**Comment by cpovirk** [comment]
I think the big benefit of package-level defaults is that they make it much more difficult for library owners to forget to annotate a new class. Of course, there are ways to perform similar checks with your build system (or the proposed [`@WantDefaultForEveryClass`](https://github.com/jspecify/jspecify/issues/34#issuecomment-506916714)), but if users have to set up their build systems, many of them won't.

**Comment by mernst** [comment]
I think users have to set up their build systems to run a checker.  Does that obviate the benefits you note here?  Or, could you clarify the benefits?  Thanks.

**Comment by cpovirk** [comment]
I'm thinking of it this way:

1. I have already configured my build to run a checker that gives me errors for "proven dangerous" nullness conversions (like dereferencing a `@Nullable` value).
2. I want to additionally get errors if I forget to apply `@DefaultNonNull` to one of my files (because, without `@DefaultNonNull`, many dangerous operations fall into the category of "possibly dangerous" rather than "proven dangerous").

In my mind, the fundamental question of this issue is whether the same checker than I'm running for (1) is also capable of checking for (2). That "checking" could take either of two forms:

- a way to apply the default at the package/module level (the main proposal on this issue)
- a way to say, at the package/module level, that the checker should require all classes to have `@DefaultNonNull` (`@WantDefaultForEveryClass`)

(Or either of those could be configured with a command-line flag, IDE setting, or other information outside the Java sources.)

In the absence of such features, I need to set up some additional layer of checking. That checking might be as simple as grepping for files that don't contain `^@DefaultNonNull`, so I don't want to overstate its importance. But I can imagine that Google might want to turn on nullness checking by default internally. That would mean that our projects would get nullness checking without even having to configure their build systems. It would be even nicer if they didn't have to even _think_ about their build systems, even if they want an additional check that all their files are fully annotated.

**Comment by cpovirk** [comment]
Minor updates about `ElementType.MODULE`:

- The JLS now [explicitly permits an annotation with no `@Target` to appear on a module](https://docs.oracle.com/javase/specs/jls/se14/html/jls-9.html#jls-9.6.4.1) ([JDK-8231435](https://bugs.openjdk.java.net/browse/JDK-8231435) -- contrast to [the previous text](https://docs.oracle.com/javase/specs/jls/se13/html/jls-9.html#jls-9.6.4.1)), but it doesn't sound like javac has been fixed to match ([JDK-8231436](https://bugs.openjdk.java.net/browse/JDK-8231436)). (Thanks, Werner and Mike, for the discussion with upstream.)
- Using `MODULE` can probably cause problems not just [for users of javac 8](https://github.com/jspecify/jspecify/issues/34#issuecomment-526611681) (and perhaps even newer versions if using `--release 8`??) but also [for some Android users](https://github.com/google/error-prone/issues/2122): I see no `MODULE` value when running `javap -bootclasspath android.jar java.lang.annotation.ElementType`, so they will likely see warnings (which of course become errors with `-Werror`).

**Comment by cpovirk** [comment]
I just [noted](https://github.com/jspecify/jspecify/issues/127#issuecomment-767033040) that the split-package (and split-module) problem may arise especially with generated code. Yes, checkers can avoid _checking_ generated files (as identified by `@Generated` or other heuristics), but they'd still assume that `@InTheClub` on a package/module _applies_ to any generated files in that package/module. And that includes not just "implementation" classes that are essentially invisible to users (like AutoValue implementations) but also things like protocol buffers that generate user-facing API.

One possible solution is that we recognize `@Generated` as an [alias](https://github.com/jspecify/jspecify/issues/35) for `@NotInTheClub` (though I'm sure this "magic" treatment of `@Generated` would confuse someone eventually...). But then we'd still want for generated code to be able to identify itself as `@InTheClub` when it really is. So we'd need to allow `@Generated @InTheClub` -- which, under my proposal, would roughly mean [`@NotInTheClub @InTheClub`](https://github.com/jspecify/jspecify/issues/111)! So perhaps `@Generated` is a special case, not "just an alias" :)

**Comment by cpovirk** [comment]
For a while now, I've been thinking as if we can allow usage on modules by [omitting `@Target` entirely](https://github.com/jspecify/jspecify/issues/34#issuecomment-520242055). I did have the significant concern that [javac still misinterprets that](https://github.com/jspecify/jspecify/issues/34#issuecomment-763026878), but at least that problem is fixable in principle (perhaps with the fixing even driven by Google's own Javac Team). And indeed, if we fixed that problem, then we could omit `@Target` entirely, and our annotation would be usable on modules.

But! I had not overlooking the rest of the obvious significance of omitting `@Target`: It makes the annotation usable, well, [_everywhere_ (except type usages and type-parameter declarations)](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/annotation/Target.html). That includes methods and constructors (probably good IMO, but [we haven't decided](https://github.com/jspecify/jspecify/issues/43)) but also `PARAMETER` ([probably bad IMO](https://github.com/jspecify/jspecify/issues/128)), `LOCAL_VARIABLE` (very unlikely to be what we want), and `FIELD` (no strong opinion, but I'd probably default to [not allowing it](https://github.com/jspecify/jspecify/issues/50)).

So it seems clear that, if we want to support putting the annotation on modules, then we need to declare that explicitly:

```java
@Target({TYPE, PACKAGE, MODULE})
// or whatever:
@Target({METHOD, CONSTRUCTOR, TYPE, PACKAGE, MODULE})
```

Or! Maybe this is another case in which we would want to exploit aliasing/implies: We could declare our main, official annotation _without_ including `MODULE`, but we still could define semantics for if it appears on a module -- and those semantics would carry over to an alias that _does_ support `MODULE`. Users could define such an alias. Or, if we wanted, we could provide a standard one -- [yet another possible variant of our main annotations](https://github.com/jspecify/jspecify/issues/109#issuecomment-766976421)!

(And we could always add `MODULE` to ours in the future if [the javac8/Android issue](https://github.com/jspecify/jspecify/issues/34#issuecomment-763026878) went away.)

**Comment by kevin1e100** [comment]
tl;dr I think [multi-release Jars](https://docs.oracle.com/javase/10/docs/specs/jar/jar.html#multi-release-jar-files) can resolve the `MODULE` conundrum.

Back in the day, we had decided JSpecify would be Java 8 compatible, which I assumed to mean Java 8 bytecode.  In such bytecode it would seem difficult or at least weird for `ElementType.MODULE` to appear.  On the other hand, for Java 9+ users, we probably want `MODULE`.

I do believe the Jar format offers us a solution though, which should also cover the Android case: multi-release Jars.  Thus we would have the `Annotation.class` file twice in the Jar, once in its normal location (as Java 8 bytecode) and once in

```META-INF/versions/9/path/to/Annotation.class`

as Java 9 bytecode (or 11 if you prefer); only including MODULE in the 9+ version.

The alternative seems to be compiling JSpecify annotations for Java 11, which should work but is maybe not (yet) desirable.

**Comment by cpovirk** [comment]
Ah, I didn't think about multi-release jars! That sounds worth investigating. (I think we've heard of tools that have problems with such jars, but that should become rarer over time.)

As for compiling for Java 11: Are you talk about dropping support for Java 8 (and I guess Java 9 and 10) entirely? (And presumably we'd also be dropping support for the people who compile with an Android bootclasspath, since we'd (I think?) still be referring to `MODULE`.)

**Comment by cpovirk** [comment]
Hmm. Multi-release jars ought to help people who build with javac8, but I'm wondering if it helps [Android users who compile against `android.jar`](https://github.com/google/error-prone/issues/2122#issue-789236038). Still, if we can solve the javac8 problem, we may be able to find another solution to the Android problem.

**Comment by kevin1e100** [comment]
Android tools such as d8 typically ignore META-INF/versions, so I think
they're fine.

Compiling against android.jar I'd expect should minimally work with -target
8 (regardless of javac version, and otherwise it's just a warning printed
by javac), but you could try it.  In any case I'd assume we can work
something out, as Android Studio afaik supports Java 11 (and even newer
versions).

As an aside I guess the linked error-prone issue could maybe also be
resolved using multi-release Jars?

**Comment by cpovirk** [comment]
On the Android side, my impression was that they may be running javac itself with `android.jar`? If so, then even if d8 ignores `META-INF/versions`, javac will probably still look at it and still find that it's missing `ElementType.MODULE`. But I'm not clear on all the details. (As for the Error Prone case, they probably also need to maintain compatibility with Java 8, so the main, non-`META-INF/versions` copy of their annotation still needs to refer to `Modifier` -- and then we're back where we started.)

Backing up, though: Multi-release jars don't do what we need :(

I think this was hinted at in [the docs you linked](https://docs.oracle.com/javase/10/docs/specs/jar/jar.html#multi-release-jar-files):

> The public API exported by the classes in a multi-release JAR file must be _exactly_ the same across versions

In our case, I figured, every method that users can call is present in both copies, so we could probably get away with the difference. But nope: If I set `@Target(MODULE)` only in the Java 9+ copy, then I can't use the annotation on a module, even when targeting Java 9+. My best guess is that _javac_ looks only at the "main" copy of each class.

```
$ find -type f | sort | xargs tail -n +1
==> ./8/com/google/annotation/InTheClub.java <==
package com.google.annotation;

import java.lang.annotation.Target;

@Target({})
public @interface InTheClub {}

==> ./9/com.google.annotation/com/google/annotation/InTheClub.java <==
package com.google.annotation;

import static java.lang.annotation.ElementType.MODULE;

import java.lang.annotation.Target;

@Target({MODULE})
public @interface InTheClub {}

==> ./9/com.google.annotation/module-info.java <==
module com.google.annotation {
  exports com.google.annotation;
}

==> ./com.google.user/module-info.java <==
@com.google.annotation.InTheClub
module com.google.user {
  requires com.google.annotation;
}

==> ./MANIFEST.MF <==
Multi-Release: true

$ javac -source 8 -target 8 -d jarcontents 8/com/google/annotation/InTheClub.java

$ javac -source 9 -target 9 -d jarcontents/META-INF/versions/9/ 9/com.google.annotation/com/google/annotation/InTheClub.java 9/com.google.annotation/module-info.java

$ jar -cfM com.google.annotation.jar MANIFEST.MF -C jarcontents .

$ javac -source 9 -target 9 -d /tmp --module-path com.google.annotation.jar com.google.user/module-info.java
warning: [options] bootstrap class path not set in conjunction with -source 9
com.google.user/module-info.java:1: error: annotation type not applicable to this kind of declaration
@com.google.annotation.InTheClub
^
1 error
1 warning
```

(Hopefully I did all that right.)

**Comment by cpovirk** [comment]
(I wouldn't be surprised if I messed it up. I'm going to play around some more.)

**Comment by cpovirk** [comment]
Sorry, I did mess it up. Somehow I wound up with my MANIFEST.MF in the root directory. I'll post the corrected instructions below.

When you create a _real_ multi-release jar, then it does work.

**Comment by cpovirk** [comment]
Instructions that show that a multi-release jar _does_ work:

```
$ find -type f | sort | xargs tail -n +1
==> ./8/com/google/annotation/InTheClub.java <==
package com.google.annotation;

import java.lang.annotation.Target;

@Target({})
public @interface InTheClub {}

==> ./9/com.google.annotation/com/google/annotation/InTheClub.java <==
package com.google.annotation;

import static java.lang.annotation.ElementType.MODULE;

import java.lang.annotation.Target;

@Target({MODULE})
public @interface InTheClub {}

==> ./9/com.google.annotation/module-info.java <==
module com.google.annotation {
  exports com.google.annotation;
}

==> ./com.google.user/module-info.java <==
@com.google.annotation.InTheClub
module com.google.user {
  requires com.google.annotation;
}

$ javac -source 8 -target 8 -d jarcontents 8/com/google/annotation/InTheClub.java

$ javac -source 9 -target 9 -d jarcontents9 9/com.google.annotation/com/google/annotation/InTheClub.java 9/com.google.annotation/module-info.java

$ jar -cf com.google.annotation.jar -C jarcontents . --release 9 -C jarcontents9 .

$ javac -source 9 -target 9 -d /tmp --module-path com.google.annotation.jar com.google.user/module-info.java
<success>
```
```

**Comment by cpovirk** [comment]
(And if I build the user code with `--release 8` (or `-source 8 -target 8`), it doesn't issue the warning. Again, hopefully I got all this right.)

**Comment by cpovirk** [comment]
I've filed https://github.com/jspecify/jspecify/issues/161 to track the work of setting up a multi-release build. I don't plan to do it anytime soon, so if anyone (perhaps someone who knows more about Gradle than I do -- i.e., pretty much anyone :)) wants something to do, this would be a great candidate.

**Comment by cushon** [comment]
> it doesn't sound like javac has been fixed to match ([JDK-8231436](https://bugs.openjdk.java.net/browse/JDK-8231436))

I mailed a fix for that, although hopefully it's irrelevant if using mrjars pans out, since it'll be a while before it's safe to assume a JDK that has that fix.

**Comment by cpovirk** [comment]
Thanks, Liam.

Perhaps I was [too dismissive above](https://github.com/jspecify/jspecify/issues/34#issuecomment-768379178) of the idea of omitting `@Target` entirely:

- Yes, we still wouldn't want to rely on people to use a new enough javac. But people stuck on an old javac could still declare an alias. (And at least we now have a concrete step toward delivering a fixed javac someday.)
- Yes, omitting `@Target` entirely allows users to put the annotation on locations where we don't want to recognize it. Now, that will always be possible with aliases, so this isn't technically a _new_ problem: Tools still should be programmed not to recognize annotations at that location. Still, it raises the stakes of getting that right. And it's never _good_ for users to be able to write annotations that won't have an effect. We could try to fight that by encouraging tool authors to issue an error on code that has annotations in unrecognized locations. (Again, this is arguably something that tools would do ideally regardless, thanks to aliases.) But that works only on code that is run through such a tool. _And_ it means that the valid locations for our annotation are built into each individual tool, rather than encoded in the annotation itself. (But again, [aliasing raises questions about the right place to encode that information in general](https://github.com/jspecify/jspecify/issues/124#issuecomment-768383434). And we will have to encode plenty of other rules into each tool, too, barring future developments like #101 and #136.)

Anyway, I think it's fair to say that omitting `@Target` will not be our first choice. But I can imagine a world in which we end up considering it again.

Part of the reason that I'm thinking about this: Even though I (eventually) [found](https://github.com/jspecify/jspecify/issues/34#issuecomment-768527944) that a multi-release jar solves the problem for users of `--release 8`/javac8, I haven't tested whether it solves the problem [for Android users](https://github.com/jspecify/jspecify/issues/34#issuecomment-763026878) -- and I suspect that it does not :( _They_ could probably work around it by using an alias, but I would feel sad if ~all Android users were stuck in that situation. Still, I'm hoping that we can get `MODULE` added to the Android SDK, eliminating the problem there.

**Comment by kevin1e100** [comment]
> I haven't tested whether it solves the problem for Android users -- and I suspect that it does not

Why wouldn't it work with mrjars, at least when compiling Java 8 source code?  We can certainly try both 8 and 11 (in Android Studio) and file bugs as needed, but I'd minimally expect 8 to work, and that seems good enough to me.

Also note any issues would just be javac warnings on the console for most users so I'm not sure there's enough reason to worry more here.

**Comment by cpovirk** [comment]
I would expect for Android builds to be much like `--release 11` (to permit `var`, etc.), just with the modified bootclasspath. But I am hoping to eventually test to find out.

I agree that warnings aren't too bad. Bbut we have some Uber folks on board, and they're the ones who reported the problem with annotation-valued enums, thanks to their use of `-Werror`. We could of course try to talk them out of using that :) Perhaps we could even pursue a javac change to make this particular warning suppressible.

**Comment by kevin1e100** [comment]
You could check, but to my knowledge, Android builds can [configure the source level](https://developer.android.com/studio/intro/studio-config#jdk) just like other Java builds, with the default starting to be 8 (previously 7) in the upcoming Android Studio 4.2 (currently in beta).  Java 11 support [is in preview](https://developer.android.com/studio/preview/features/#use-java-11).  That probably means there currently are no Java 11 Android builds, but there will be at some point.

**Comment by cpovirk** [comment]
Thanks, that's good info. Kevin is also pulling in some more people internally to ask about Android tooling.

Plus, he noted that `ElementType.MODULE` is a problem that Android is going to have to solve eventually, independent of anything JSpecify does.

So I think all that _our_ annotations are changing is adding one more variant to the ways that `ElementType.MODULE` can cause Android trouble. Here are the 2 variants I can think of if we ignore JSpecify:

- Even today, it's possible for `ElementType.MODULE` to cause trouble because people can compile jars that use it and try to use them from Android. (Presumably they would do this only for cross-platform jars: There would be no reason to use `ElementType.MODULE` in an Android app today, since Android apps are generally built for Java 8 and thus can't use modules. And of course modules will have no runtime effect under Android even in the future, as far as I know.)
- _After_ an Android user switches to the Java 11 source level, that user will be able to use modules. Even if modules have no runtime effect, the user might conceivably want to use them -- perhaps even as a way to make a single `@InTheClub` annotation apply to an entire app ;) At that point, the user will want for `ElementType.MODULE` to be present.

What's special about JSpecify -- well, besides the near-universal adoption that we'd like to see :), which is itself notable -- is the likelihood that we'll use a multi-release jar to only _conditionally_ include `ElementType.MODULE`. This produces the first(?) way in which a project, _merely by updating its Java source level_, can see problems related to `ElementType.MODULE`. This is in contrast to the 2 problems I described above, which exist (a) before upgrading the Java source level and (b) only after beginning to use modules, respectively.

Overall, I have been feeling much better about this as the conversation has gone on.

**Comment by cpovirk** [comment]
cushon@ says that javac [was in fact fixed](https://bugs.openjdk.java.net/browse/JDK-8254023) to allow no-`@Target` annotations on module declarations, but that doesn't take effect until Java 16.

Apparently there's also a _chance_ that no-`@Target` annotations [will become applicable to type-use locations, too](https://mail.openjdk.java.net/pipermail/compiler-dev/2019-September/013715.html).

kevin1e100@ points out that, regardless of the decisions in these particular cases, we're seeing that omitting `@Target` gives permission to the JDK developers to change the meaning in the future.

This is all even more reason to just set an explicit `@Target`, lest our annotation become applicable to [`RECORD_COMPONENT`](https://download.java.net/java/early_access/jdk16/docs/api/java.base/java/lang/annotation/ElementType.html) (though that is maybe [not the best example](https://github.com/jspecify/jspecify/issues/43#issuecomment-700277489)) or other future locations. It would be especially sad for people to start using our annotations on such locations and then have us break them later when we update our tools to say "no, wait, that's not allowed"....

**Comment by mernst** [comment]
An annotation without `@Target` was always intended to be applicable to all locations.  Infelicitous writing has caused a lot of confusion, but that is getting resolved.  There is movement to correct this now, and the meaning will not change again in the future.

But yes, I agree it is best style to provide a `@Target` meta-annotation.

**Comment by cpovirk** [comment]
Interesting, thanks. So we can say "no-`@Target` annotations will become applicable to yet-to-be-invented locations." That's a weaker claim than I posted above, since it's not about changing behavior for existing locations again, but it's also stronger, since you're saying that's almost certain to be what happens if new locations are added (as is happening with `RECORD_COMPONENT`).

Anyway, it's sounding like we're all pretty happy with including `@Target`.

(Digressing a bit: When javac changes to permit no-`@Target` annotations on type-use locations, that will change the meaning of existing code like `@Foo private final String;`: Before the change, `@Foo` will apply only to the field; after, it will apply to both the field and `String`. I'm not sure if that behavior will change for _all_ `-source` values or just for `-source 16` (or whichever version it happens to be) and up. [The fix for `MODULE`](https://github.com/openjdk/jdk16/commit/41f312eb#diff-00bc9a257a3f99bd7729dd582d6983158a7e50277b426746017d6557ed880ca1R122) looks to apply to all `-source` values. That seems fine, since it doesn't change the behavior of existing code. But a fix for `TYPE_USE` _would_ affect existing code. I don't really have a strong opinion about this -- "it is best style to provide a `@Target` meta-annotation," after all -- but I know that the JDK can be pretty conservative, so @mernst, @cushon, or others closer to JDK development than I am might have opinions on whether it's worth further discussion. I see that [mernst already mentioned the behavior change](https://mail.openjdk.java.net/pipermail/compiler-dev/2019-September/013705.html); I had just missed that it's a bit more significant then the behavior change around `MODULE`, since it affects existing code.)

**Comment by cpovirk** [comment]
@PetukhovVictor , does the Kotlin compiler look for annotations on package-info and module-info when it looks at Java code?

(I should really check myself, instead of asking you to tell me, but I know I won't check anytime soon.)

**Comment by cpovirk** [comment]
This thread has gone in a lot of directions, but I think we may be able to tie off one of them: I think our annotation can safely refer to `MODULE`. That's because:

- KengoTODA set up a multi-release jar for us in https://github.com/jspecify/jspecify/issues/161. This should eliminate problems for users of javac8 / `--release 8`.
- Android is adding `MODULE` to its `ElementType` in [1596572](https://android-review.googlesource.com/c/platform/libcore/+/1596572/). This should eliminate problems for the Android users who would have encountered them. (I'm a little fuzzy on the details, but it seems to come up with at least some usages of the Android toolchain, and it may come up with minifiers like Proguard more generally.)

(IIUC, both of the problems described here would have come up only for users of `-Werror` or similarly strict build-time checks. Still, it's good to accommodate that use case -- and nice to eliminate the warning spam even for users who don't promote warnings to errors.)

**Comment by kevin1e100** [comment]
That's excellent progress, thank you everyone who helped work that out!

**Comment by PetukhovVictor** [comment]
@cpovirk sorry for delayed answer, I've looked at the support nullability annotations at package level: they are supported both for JSR 305 (as said before) and jspecify `@DefaultNonNull`. There was a small bug in the type enhancement, due to which at first look it seemed that there is no support for jspecify annotations. I've fixed it and added [the corresponding internal tests](https://github.com/JetBrains/kotlin/commit/15de3858467ac6e26a9688657b732762b482fd66) to the Kotlin compiler.

But module level annotations aren't supported yet, I've created the corresponding issue: https://youtrack.jetbrains.com/issue/KT-45189. BTW the question about support reading nullability annotations at the module level was open in the [JSR-305 KEEP](https://github.com/Kotlin/KEEP/blob/master/proposals/jsr-305-custom-nullability-qualifiers.md). Probably, we need some design discussion before supporting module-level annotations.

**Comment by cpovirk** [comment]
[IDEA-273004](https://youtrack.jetbrains.com/issue/IDEA-273004) reports that IntelliJ has some difficulty with `@NullMarked` on a module because of our use of a multi-release jar.

- @akozlova is aware. Anna and @amaembo, let us know if you think we should reconsider the multi-release jar for this reason.
- It would be a good idea for us to test with Eclipse, NetBeans, and any other commonly used IDEs. If anyone is up for trying, please do.
- We've noted before that [the mrjar spec](https://docs.oracle.com/javase/10/docs/specs/jar/jar.html#multi-release-jar-files) requires that "The public API exported by the classes in a multi-release JAR file must be exactly the same across versions." It's never been completely clear what counts as "API" for that requirement. Quoting myself from a discussion with some Android people:

> As I understand it, the different `@Target` will have [no implications on linkage](https://wiki.eclipse.org/Evolving_Java-based_APIs_2#Evolving_annotations_on_API_elements). That may be all that the spec is aiming for: "If you compile against the old version, you'd better run against the new version."
> 
> (Sort of support for that: The spec permits a `module-info` in a per-release directory even if one is not present in the root. Perhaps they consider the module to not be "exported by the classes?" The docs are confusing even about this: "A modular multi-release JAR file is a multi-release JAR file that **has** a module descriptor, module-info.class, **in the root at the top**." But then: "A multi-release modular \[jar\] **need not** have a module descriptor **at the located root**.")
> 
> Here's one quote that suggests that the full details may be unsettled -- but that, even under the strictest interpretation, the limitation is meant to refer to _signature equality_, which we're preserving:
> 
> > [Every version of the library should offer the same API; investigation is required to determine whether this should be strict backwards compatibility where the API is exactly the same (byte code signature equality), or whether this can be relaxed to some degree without necessarily enabling the introduction of new enhancements that would blur the notion of one unit of release.](https://openjdk.java.net/jeps/238#Modular-multi-release-JAR-files)
> 
> I do feel a _little_ iffy about the whole thing, but I've become reasonably comfortable with it. Plus, we have a tolerable (if unfortunate) exit strategy: Just add `MODULE` to the Java 8 version, too, and tell people they have to avoid using `-Werror` or compile with a classpath that includes `MODULE`....
> 
> Anyway, I'm happy to hear further thoughts on this, and I've wondered if we should try reaching out to actual JDK developers for their interpretation and/or the world at large for any problems they've encountered.

**Comment by cpovirk** [comment]
I'm told that it works OK with NetBeans. If anyone has Eclipse already installed, here's how to get a jar to test with:

```
git clone git@github.com:jspecify/jspecify.git && cd jspecify && ./gradlew
```

That produces a `build/libs/jspecify-0.1.0-SNAPSHOT.jar` for you to use.

**Comment by cpovirk** [comment]
Switching to a separate concern about large-scope defaults:

Something reminded me that a Java package or module may contain both Java and Kotlin code. That means that a `@NullMarked` annotation on those scopes would apply to enclosed Kotlin code, which currently [does not contain JSpecify nullness annotations](https://youtrack.jetbrains.com/issue/KT-47417).

- Users can work around that by avoiding using `@NullMarked` on such scopes for cross-language code.
- Alternatively, they could apply the annotation but also add `@Nullable` to their Kotlin code wherever they use `?`.
- Maybe someday they will be able to apply the annotation but [undo it with `@NotNullMarked` annotations on the Kotlin classes](https://github.com/jspecify/jspecify/issues/127).
- Or maybe by then Kotlin will have begun writing JSpecify annotations.

**Comment by kevinb9n** [comment]
(_Module_-specific topics to #222 now.)

**Comment by kevinb9n** [comment]
Propose: we will include MODULE and PACKAGE in the targets, and

- When users use modules, these should have relatively well-defined behaviors (and see #222 for any issues that may arise with this)
- When they don't, many problems can result from using package annotations in this way, but we believe these problems are addressable in various ways (not necessarily filed yet), and don't add up to an argument to actually _not_ support package annotations.

Please view this issue on github and add a comment **or even just an emoji reaction!** to express your feedback.

**Comment by netdpb** [comment]
Looks like we have consensus.

**Comment by cpovirk** [comment]
I made an accidental discovery: I could use `@NullMarked` on a method even before we [added](https://github.com/jspecify/jspecify/commit/80c288776ea84af78bf9ae5f254d72ab5514d16e#diff-403d33a100f9aba9f7e875f64d60a30f8163f6cbd19392f5873958817cfeb9a9) `METHOD` to its `@Target`... because it had ***`MODULE`*** in its `@Target`?!

```java
$ tail -n +1 *.java
==> Anno.java <==
import static java.lang.annotation.ElementType.MODULE;

import java.lang.annotation.Target;

@Target(MODULE)
@interface Anno {}

==> Foo.java <==
class Foo {
  @Anno
  void go() {}
}

$ javac Foo.java Anno.java
# no errors?!

$ javac -version
javac 11.0.13
```

I do get the expected error with a newer javac:

```
$ ~/jdk-19-ea+26/bin/javac Foo.java Anno.java
Foo.java:2: error: annotation interface not applicable to this kind of declaration
  @Anno
  ^
1 error
```

I didn't immediately find a bug about this upstream.

Anyway, that's fine because now we allow `@NullMarked` on methods anyway :)

The not-as-fine part is that this same bug also allows `@NullMarked` on fields, parameters, and local variables (and probably packages, but I didn't check), which [we don't want](https://github.com/jspecify/jspecify/issues/50). (It doesn't allow it in type-use-only locations, at least.)

I don't think that rises to the level that should make us actually avoid `@Target(MODULE)` (even though [this isn't the first problem we've seen with `@Target(MODULE)`](https://github.com/jspecify/jspecify/issues/245) :)). But it does give tool authors more reason to write code to explicitly disregard annotations in locations where they aren't expected—and to issue errors when they see source code with such annotations.

**Comment by netdpb** [comment]
The current, working decision, as of 2022-03-20, is that users can use `@NullMarked` on modules and packages, and `@NullUnmarked` on packages, even though there are pitfalls. The pitfalls are common to all annotations used at those levels, however, not specific to JSpecify's.

The argument for changing this decision is that the pitfalls are interesting, including the fact that package-level annotations apply to split packages, including tests, and the fact that module-level annotations apply only when the artifact is installed in the module-path by clients, and not in the classpath.

However, because the pitfalls are not JSpecify-specific, we should allow the obvious application at these levels.

This must be decided before version 1.0 of the jar.

**I propose the current decision be finalized for 1.0.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by cpovirk** [comment]
I agree (and I have given my thumbs up), but I feel obligated call attention to one more pitfall that I don't think came up on this particular thread:

Some users expect for annotations on a package to apply to subpackages, or at least they wonder if that might be the behavior. I expect us to finalize our working decision that annotations do _not_ apply to subpackages (#8). Regardless of what we decide, some users will have different expectations than that. I think that's unfortunate but not a reason to pull back from supporting package-level annotations at all.
