### ISSUE TITLE
Whether an exception parameter is nullness-applicable and why [working decision: intrinsically non-null]

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#347]
[(earlier)](https://github.com/jspecify/jspecify/issues/165#issuecomment-776310185)

Suppose we're trying to null-mark this existing code *without changing it*:

```java
try {
  ...
} catch (SomeException e) {
  e = expressionThatDoesNotExcludeNull();
}
```

The answer might be one of:

1. `e`'s type here is **nullness-applicable**
    * Therefore we expect a finding here, but a change to `@Nullable SomeException` makes it go away
2. `e`'s type here is **nullness-inapplicable** for reason of being **intrinsically non-null**
    * Therefore we expect a finding here, and suppression is the only way out
3. `e`'s type here is **nullness-inapplicable** for reason of being (morally) a **local variable root type**
    * Therefore we expect no finding here
4. This is deep enough into implementation code that we really don't care
5. other?

Notice that the difference between 2 and 3 is just whether we think of `e` more like a parameter or more like a variable.

I'm not sure that this 1-5 choice even affects which issues a flow-sensitive analyzer *could* find and report. If so, is there any big reason to have a finding at the site of the assignment anyway?

**Comment by cpovirk** [comment]
(I was happy to see this separated from the other issue :))

One of the random regrets I have from JSpecify is that I spent an embarrassing amount of time trying to get our reference checker to _not_ report an error in this exact scenario.

I was doing that because I was (and generally remain) a fan of (3). The problem was that the dataflow library we're building on is implemented like (2). To me, what we have is basically a local variable with an implicit "initializer" that assigns a known-to-be-non-null value to it. But probably I should take my experience as at least slight evidence that (3) is simpler to implement, especially since a lot of projects use the same dataflow library as we do.

I should note, though, a big reason that I regret this experience: The situation I was investigating was entirely hypothetical. I just noticed that exception parameters were treated "differently" (under my model) that "normal" local variables, so I tried to change that. My work wasn't prompted by any real code. (That's not to say that _no_ such code exists. I don't think I even looked. We could search around if we wanted.) So there's some evidence here for (4), too.

**Comment by kevinb9n** [comment]
Comparing to the 3 other ways an implementation-code variable can get implicitly initialized:

* A **lambda parameter**. The only other kind of non-API "parameter". We decided they *are* nullness-applicable in #261, partly because they look *so* much like method parameters, and some arguments about type inference.
* A **for-each variable**. Like an exception parameter, the nullness of the *initial* value is knowable, but the variable could be reassigned. For some reason, I have little trouble classifying this as just another kind of local variable (you "almost" see the expression it's being initialized to). So this is nullness-inapplicable.
* A **pattern variable**. For now there are only type patterns and record patterns. In both cases I think the nullness should be determinable without annotations, like any other local variable. When you can provide custom destructuring I imagine the same will hold. Again inclined toward nullness-inapplicable.

More thoughts later.

**Comment by cpovirk** [comment]
(Thanks, I had the vague thought that "maybe there's precedent for 'something like this,'" but that thought left my mind before I could write it down, let alone explore it.)

To come at [my comment above](https://github.com/jspecify/jspecify/issues/347#issuecomment-1329949657) from another angle: For purposes of 0.3, we make our reference-checker work significantly easier if we choose (2) or (4). Given those options, I suppose I like (4), since it at least _permits_ a tool to take the approach of my true preference (3) :)

**Comment by kevinb9n** [comment]
With (4) I think we'd lose our well-defined and tidy answer for [where do these annotations apply?](
https://jspecify.dev/docs/api/org/jspecify/annotations/Nullable.html#applicability). I could see losing that for *multiple* reasons that add up, but this doesn't seem like enough.

Since (2) is more feasible right now, let's working-decide for that, and reevaluate before 1.0.

**Comment by kevinb9n** [comment]
Here's a defense for each of the 3 proper options.

First, JLS says:

* **parameters** are: method params, constructor params, lambda params, exception params
* **local variables** are: in a declaration statement (the "normal kind"), in try-with-resources, in classic for header, in enhanced for header, and pattern variables

(And I believe that where `@Target(PARAMETER)` annotations can appear respects that categorization precisely.)

1. would make this *very* tidy: everything in bucket 1 is nullness-applicable, everything in bucket 2 isn't.
2. might seem anomalous, but I think it's effectively just as consistent as (1) is; it's just that we *also* know it to be the only kind of parameter that's intrinsically non-null; null can absolutely never be passed to it.
3. is a much more jagged edge. We would lump just *one* kind of parameter in with the second row, which is irregular. Admittedly I'm not sure I could explain *why* that kind is considered a parameter when pattern variables aren't.

**Comment by cpovirk** [comment]
Nice. Is that from [4.12.3](https://docs.oracle.com/javase/specs/jls/se19/html/jls-4.html#jls-4.12.3)? If so, do they actually define "parameter" somewhere as an umbrella term, or are you (quite reasonably) grouping them together based on the presence of the word "parameter" in each term? I ask in part because it looks like they probably _do_ define "local variable" as an umbrella term. And I see that [6.1](https://docs.oracle.com/javase/specs/jls/se19/html/jls-6.html#jls-6.1) has an umbrella definition for "_formal_ parameter," which notably includes everything from the list you gave _except_ exception parameters. And there is additionally at least one part of the spec (in [6.4.1](https://docs.oracle.com/javase/specs/jls/se19/html/jls-6.html#jls-6.4.1)) that has a rule specifically for "a local variable or exception parameter."

Given all that, I'm not currently putting a lot of weight behind the use of the word "parameter" in a term.

**Comment by cpovirk** [comment]
I forgot to include one other thought, which conveniently is unrelated—and possibly actually a bad idea? :)

We _could_ consider whether we might feel different about a hypothetical domain _other_ than nullness. Sure, caught exceptions are necessarily _non-null_. But if a given exception could be either `@Red` or `@Green`, would that change how we feel about annotating `catch` blocks? If so, then presumably it would also change how we feel about annotating `throws` clauses, and maybe it makes sense to tie those two together per your take on option 2 [above](https://github.com/jspecify/jspecify/issues/347#issuecomment-1334543018)?

(Bolting a further type system onto exception handling would no doubt raise all kinds of questions: It's not like I can both `catch (@Green FooException e)` and `catch (@Red FooException e)` for the same `try` block. But I could believe that a checker could do _something_, like forcing you to write `catch (@UnknownColor FooException e)` if both colors were possible.)

**Comment by kevinb9n** [comment]
Sorry for not citing.

> Nice. Is that from [4.12.3](https://docs.oracle.com/javase/specs/jls/se19/html/jls-4.html#jls-4.12.3)?

Yeah, it was, but seemingly confirmed by [9.6.4.1(8)](https://docs.oracle.com/javase/specs/jls/se19/html/jls-9.html#jls-9.6.4.1). Although we know we can't take annotation targets as the definitive word on what things are....

> And there is additionally at least one part of the spec (in [6.4.1](https://docs.oracle.com/javase/specs/jls/se19/html/jls-6.html#jls-6.4.1)) that has a rule specifically for "a local variable or exception parameter."

So local variables and exception parameters are different but shadow in the same way. Okay.

(Incidentally, I think the distinction I would have made is between implicitly or explicitly initialized, which would be somewhat similar to the JLS categorization except the for-each variable and pattern variables would actually be parameters.)


> We _could_ consider whether we might feel different about a hypothetical domain _other_ than nullness.

I'm having a hard time imagining any type-use-annotating of exception types in throw/throws/catch coming to any real profit. It would all just be an effort to simulate what real types already do, but worse.

**Comment by Mooninaut** [comment]
I have exception parameters so mentally ingrained as effectively final non-null values that I didn't even understand the question at first. Personally, I would take option 4. "write bad code, get bad results".


However, Java treats them as non-final parameters, and I don't see an _inherent_ reason for JSpecify to treat them differently. Option 1 seems reasonable.

**Comment by Kroppeb** [comment]
I want to point out that catch var's are not the only kind of "parameter" that is guaranteed to be initialized to a non null value. The `this` parameter is also always non null, however it can't be reassigned so we don't have the same issues.
 
Initially I was personally feeling more like 1 and 3, as 2 felt too opinionated compared, but I'm now more leaning towards 2 as java already restricts which kind of types are allowed anyway for a catch parameter: they need to extend `Throwable`, they can't have type parameters. We would now be adding another limitation: they can't be nullable.

**Comment by kevinb9n** [comment]
True; I tend to avoid mentioning receiver parameters because (a) we provisionally ruled out null-annotating any part of them in #157 and (b) when people don't know about them I feel they should go right on blissfully not knowing about them :-)

**Comment by kevinb9n** [comment]
This has a working decision so should be marked closed.

**Comment by netdpb** [comment]
**Current decision**: Exception parameters are intrinsically non-null.

**Argument for changing**: No strong case is made, although there are different ways to describe the rationale.

**Timing**: This must be decided before version 1.0 of the jar.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by netdpb** [comment]
Decision: Exception parameters are intrinsically non-null.
