### ISSUE TITLE
Remove `@Target(MODULE)` from `@NullUnmarked`?

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#348]
Seems like it can't serve any purpose and might confuse someone (who rightly thinks "but I thought it was the default").

**Comment by cpovirk** [comment]
That sounds sensible, and I like it a lot for an additional reason:

Removing `MODULE` would at least marginally decrease the chances that users would encounter the crash discussed in #302. In fact, if we imagine a world in which users use `@NullMarked` only at the class, package, and module levels, while perhaps using `@NullUnmarked` on individual methods, then removing `MODULE` would _eliminate_ #302. In practice, I'm sure it wouldn't _totally_ eliminate it. But it might help a lot.

The main counterargument I can see is that an enterprising organization might try to "flip the default" for now code so that _all_ code is considered null-marked unless otherwise annotated :) Then they might theoretically want to unmark their already existing modules. But I'm inclined not to worry about that, thanks to some combination of:

- For that to work, every tool that the organization uses would need to support "null-marked by default."
- Some people don't make use of modules.
- It doesn't seem that hard to put in place enforcement that all _new_ modules are `@NullMarked`.
- We might even look askance at the idea that code without `@NullMarked` should be treated as null-marked in general.

**Comment by kevinb9n** [comment]
This is my askance look.

**Comment by cpovirk** [comment]
https://github.com/jspecify/jspecify/pull/351 did this and updated docs accordingly.

**Comment by tbroyer** [comment]
> Arguably, my use case can be solved differently:
> 
> * By adding a `package-info.java` in the test scope, annotated with `@NullUnmarked`
> * By configuring ErrorProne with `-XepExcludedPaths:.*/src/test/java/.*`

or by disabling NullAway when compiling your test code

<details>
<summary>With Maven</summary>

(untested)

```xml
<plugin>
  <artifactId>maven-compiler-plugin</artifactId>
  <configuration>
    <compilerArgs combine.children="append">
      <arg>-XDcompilePolicy=simple</arg>
      <arg>--should-stop=ifError=FLOW</arg>
    </compilerArgs>
    <executions>
      <execution>
        <id>default-compile</id>
        <configuration>
          <compilerArgs>
            <arg>-Xplugin:ErrorProne -Xep:NullAway:ERROR</arg>
          </compilerArgs>
        </configuration>
      </execution>
      <execution>
        <id>default-testCompile</id>
        <configuration>
          <compilerArgs>
            <arg>-Xplugin:ErrorProne -Xep:NullAway:OFF</arg>
          </compilerArgs>
        </configuration>
      </execution>
    </executions>
    <annotationProcessorPaths>
      <path>
        <groupId>com.google.errorprone</groupId>
        <artifactId>error_prone_core</artifactId>
        <version>${error-prone.version}</version>
      </path>
      <path>
       <groupId>com.uber.nullaway</groupId>
        <artifactId>nullaway</artifactId>
        <version>0.12.13</version>
      </path>
    </annotationProcessorPaths>
  </configuration>
</plugin>
```

</details>
<details>
<summary> With Gradle</summary>

```kotlin
tasks {
  compileTestJava {
    // using the net.ltgt.errorprone and net.ltgt.nullaway plugins
    options.errorprone.nullaway.disable()

    // without plugins
    options.compilerArgs.add("-Xep:NullAway:OFF")
  }
}
```

</details>

**Comment by kevinb9n** [comment]
Thanks, filed #784
