### ISSUE TITLE
Run reference checker tests on each PR

### ISSUE THREAD

**Issue by netdpb** [jspecify/jspecify#370]
For each PR (and post-merge), add a job to run tests (maybe just conformance tests?) for [the reference checker](https//github.com/jspecify/nullness-checker-for-checker-framework).

That way we can know whether the reference checker needs to be updated for any given change in this repo.

**Comment by netdpb** [comment]
Looks like #371 only half worked. It runs the checks on the PR before merge but skips them post merge.

**Comment by scolsen** [comment]
To run on post merge, I think you need to add a `push` condition.

But, if we run pre-merge, is there any reason to run post-merge? If there are no merge conflicts in the PR, which is already a prerequisite, wouldn't running post-merge, in theory produce the same result as pre-merge runs?

**Comment by netdpb** [comment]
> To run on post merge, I think you need to add a `push` condition.

There already is a push condition. We run the rest of the workflow both post- and pre-merge. It's just that the conformance tests don't run. I suspect that the `github.base_ref` isn't set the way I thought it would be post-merge.

> But, if we run pre-merge, is there any reason to run post-merge? If there are no merge conflicts in the PR, which is already a prerequisite, wouldn't running post-merge, in theory, produce the same result as pre-merge runs?

I think that's there in order to check for a race condition. Consider the case of two racing PRs:

1. PR A passes pre-merge.
2. PR B passes pre-merge.
3. PR A gets merged.
4. PR B gets merged.

It may be the case that A and B conflict in a way that would only be caught post-merge.

**Comment by scolsen** [comment]
> > To run on post merge, I think you need to add a `push` condition.
> 
> There already is a `push` condition. We run the rest of the workflow both post- and pre-merge. It's just that the conformance tests don't run. I suspect that the `github.base_ref` isn't set the way I thought it would be post-merge.

ahhhhhhhhhhhhhhhhh

> > But, if we run pre-merge, is there any reason to run post-merge? If there are no merge conflicts in the PR, which is already a prerequisite, wouldn't running post-merge, in theory, produce the same result as pre-merge runs?
> 
> I think that's there in order to check for a race condition. Consider the case of two racing PRs:
> 
> 1. PR A passes pre-merge.
> 2. PR B passes pre-merge.
> 3. PR A gets merged.
> 4. PR B gets merged.
> 
> It may be the case that A and B conflict in a way that would only be caught post-merge.

Even in this case, wouldn't PR B need to pull head after PR A merge since it will no longer have the latest head commit? At which point the workflows should re-trigger (at least that's how it works on some other projects I've worked on, if not we can probably set that w/ some settings). I don't think github let's you merge unless you're up to date w.r.t to head w/ no conflicts. I suppose there might be some tiny edge case in which both A and B get their merge buttons pressed at the precise same time and github can't sequentialize the operations, but I think this would be really rare.

All that said, it's probably good to just run these occasionally on head anyway, so post merging or even just setting up some kind of scheduled run on main sgtm.

**Comment by netdpb** [comment]
> > I think that's there in order to check for a race condition. Consider the case of two racing PRs:
> > 
> > 1. PR A passes pre-merge.
> > 2. PR B passes pre-merge.
> > 3. PR A gets merged.
> > 4. PR B gets merged.
> > 
> > It may be the case that A and B conflict in a way that would only be caught post-merge.
> 
> Even in this case, wouldn't PR B need to pull head after PR A merge since it will no longer have the latest head commit? At which point the workflows should re-trigger (at least that's how it works on some other projects I've worked on, if not we can probably set that w/ some settings). I don't think github let's you merge unless you're up to date w.r.t to head w/ no conflicts. I suppose there might be some tiny edge case in which both A and B get their merge buttons pressed at the precise same time and github can't sequentialize the operations, but I think this would be really rare.

It's possible for A and B to have no conflicts, or even touch no files in common, and still run into this problem.

> 
> All that said, it's probably good to just run these occasionally on head anyway, so post merging or even just setting up some kind of scheduled run on main sgtm.

**Comment by scolsen** [comment]
> It's possible for A and B to have no conflicts, or even touch no files in common, and still run into this problem.

True. I think B or whichever PR got merged a nanosecond slower would need to pull from head (which would be then contain A's changes) and in so doing would catch problems since I'm pretty sure that would re-trigger workflows even if there were no conflicts introduced. None of this matters though, unless we hit rate limits or some other cost to just running these semi-frequently regularly. Barring that, it does make more sense to just run these on both pre/post.

**Comment by netdpb** [comment]
But if there's yet another PR C merged while B reruns the checks, we're in the same boat. This is why I think people generally run pre- and post-merge. With rate limiting, maybe not every PR is run post-merge.
