### ISSUE TITLE
How to handle nullness with generic parameters? (specific example)

### ISSUE THREAD

**Issue by bowbahdoe** [jspecify/jspecify#373]
Hey, so i'm writing with the jspecify annotations in one of my little projects.

I am not running the tool so I'm actually unsure what the exact rules being enforced would be, but I am trying to get a mental model.

I have this "successor" record where, only in a very narrow context, it can be given a `null` action.

Outside of that scope, the only folks who can access the record will be guaranteed a non-null action. I'm wondering if I am representing that correctly

```java
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

@NullMarked
public record Successor<State, Action>(State state, @Nullable Action action, double cost) {
}
```

```java
package dev.mccue.keys.search;

import io.vavr.collection.Vector;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

import java.util.List;
import java.util.Objects;

@NullMarked
final class Path<State, Action> {
    private final double costSoFar;
    private final Vector<Successor<State, @Nullable Action>> soFar;

    public Path(State initialState) {
        this.soFar = Vector.of(new Successor<>(initialState, null, 0));
        this.costSoFar = 0;
    }

    private Path(Vector<Successor<State, Action>> successors, double costSoFar) {
        this.soFar = successors;
        this.costSoFar = costSoFar;
    }

    public State mostRecentState() {
        return this.soFar.get(this.soFar.size() - 1).state();
    }

    public Path<State, Action> withNext(State state, Action action, double cost) {
        return new Path<>(this.soFar.append(new Successor<>(state, action, cost)), this.costSoFar + cost);
    }

    public List<Successor<State, @NonNull Action>> withoutNullActions() {
        return this.soFar.filter(Objects::nonNull)
                .toJavaList();
    }

    public double totalCost() {
        return this.costSoFar;
    }
}
```

**Comment by Mooninaut** [comment]
As I understand it, and I'm far from an expert, annotating a record component (the first case) only affects that record component. Annotating a generic type parameter (the second and third cases) affects all usages of that parameter.

So in the first case, the effect of `@Nullable` is restricted in scope to the `action` record component, but in the second and third cases, `@Nullable` affects all uses of `Action`, not just the `action` record component. Therefore, in the second and third cases, methods that accept/return `Action`, such as `withNext`, would be considered to accept/return nullable values.

I don't know what difference there is, if any, between `@Nullable Action` and `Action extends @Nullable Object`.

**Comment by kevinb9n** [comment]
I'm sorry I was taking a bit of a JSpecify breather when this came in! At some point we hope reports like yours will become more common occurrences and we'll be in the habit of watching.

> I don't know what difference there is, if any, between `@Nullable Action` and `Action extends @Nullable Object`.

In `class Foo<A extends @Nullable Object>`, the part in angle brackets is a declaration of a type parameter. That incantation says that the type argument given in a *usage* of the `Foo<...>` type can be any nullable OR non-nullable type (because "non-null extends null").

*Inside* the `Foo` class (and *only* there), we may see `@Nullable A`, for example as a method return type. That says that regardless of whether the usage is of `Foo<String>` or `Foo<@Nullable String>`, we want that return type to be `@Nullable String` either way.

Back to the original statement: cases like this, where a type can only ever be null within one constrained context, while usages in general can count on it being non-null, are probably best addressed by making the thing non-nullable and just suppressing warnings inside the special scope. Of course this has to be done carefully and one could shoot oneself in the foot.

I suspect I haven't fully helped with the original questions but let me start here and let me know what I can answer next!

(Aside: using type parameter names that look like class names will definitely confuse a lot of readers; it's customary to use a single letter for them to keep the distinction clear.)

**Comment by ExE-Boss** [comment]
> (Aside: using type parameter names that look like class names will definitely confuse a lot of readers; it's customary to use a single letter for them to keep the distinction clear.)

I’ve also seen type parameters declared using a `T_` prefix and all caps, e.g.: <code>[PrimitiveIterator]&lt;T, T_CONS&gt;</code> and <code>[Spliterator.OfPrimitive]&lt;T, T_CONS, T_SPLITR extends [Spliterator.OfPrimitive]&lt;T, T_CONS, T_SPLITR&gt;&gt;</code>.

[PrimitiveIterator]: https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/util/PrimitiveIterator.html
[Spliterator.OfPrimitive]: https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/util/Spliterator.OfPrimitive.html

**Comment by kevinb9n** [comment]
I'll optimistically resolve for now, but am happy to be more helpful if needed.

(To the side point, Google Style opted to keep these names distinct even from constant names as well, so in the few cases where `T`, `E`, `X2` etc. don't help, we write `RequestT`, `ResponseT`, etc. Always ending with `T`. And of course then we don't let a class name end with `[a-z]T`. Still, it's a last resort.)
