### ISSUE TITLE
@NotNull field semantics

### ISSUE THREAD

**Issue by donnerpeter** [jspecify/jspecify#39]
Basic question: when a field is marked as `@NotNull`, when can it be safely assumed to be non-null?

If a field is final, then it probably becomes notnull after its initialization. But before that, other methods can be called, also via superclass constructor, and it seems an undecidable problem in general to determine if a specific field reference is done after its initialization or before it. IntelliJ does some guessing here to avoid marking `if (field == null)` as "always true" in such semi-initialized places, but to avoid false positives, it'd also skip useful warnings sometimes.

If a field is non-final, things get even more complicated, not even compiler complains about obvious field dereferences before its initialization. Should we even allow notnull fields not initialized before or inside all constructors? AFAIK Eclipse doesn't. IntelliJ has an option for this, and some people don't like it because they have non-null fields initialized in test set-up, or by dependency injection.

**Comment by kevinb9n** [comment]
Above I said, "Non-final fields are the source of most problems" and I fantasized about handwaving them away. But yeah, maybe it's not so bad.

There's no problem with `public @Nullable Type field`; you can assign anything to it, but any read from it is nullable.

As for `public @NonNull Type field`, first, this would prevent assigning a nullable type to it, which is all good. For reads, it documents the owner's promise that no one outside the class or its subclasses should ever observe a null value. The owner could fail to meet that promise, but it can also fail to meet its promise for a nullable method return type or anything else too.

**Comment by kevinb9n** [comment]
Here's a broader proposal for how we might look at non-final fields.

First, we could stick to my beloved "all we're doing is making enhanced types" design anchor, but in this case it doesn't get us far. Fields go through changes; types are unchangeable. Once a field gets marked nullable then a checker has little opportunity left to do anything smart about it.

So: class `Foo` has non-final field `bar`.

First, I want to talk about `Foo`'s *responsibilities* toward `bar`, *then* get into "how might a tool *help* `Foo`'s author get those responsibilities right."

1. `Foo` is responsible for *initializing* `bar` (making it able to serve its purpose) _sometime_ before any code outside the class might read its value, directly or indirectly (with a few more coping strategies available if the latter).
2. If `Foo` wants to *invalidate* `bar` (making it unable to serve its purpose), then `Foo` is likewise responsible for ensuring that outside callers won't access it anymore, directly or indirectly (with a few more coping strategies available if the latter).

None of this is new or specific to nullness checking, it's just a way to write less-buggy code in general.

Bringing nullness checking into the picture: if we leave `bar` non-nullable, this expresses the following idea: "part of what it means for `bar` to be 'able to serve its purpose' is that it is non-null."

How can tools help?

They will naturally help with #2 at least in that setting the field to `null` would produce a warning that would have to be suppressed. A culture that values safety would require an adequate explanation to be provided in a comment.

With #1, it helps a _bit_ that we can differentiate real initializations (no warning) from dubious initializations that might still leave the field null (warning). And of course it can be validated that the field is set _somewhere._ Then I think the problem reduces to the general problem of API sequencing contracts.

**Comment by kevinb9n** [comment]
We need to ground ourselves in an understanding that "we are just creating types, here" -- however, they are _erased_ types, and just like with other erased types, the flexibility that gives the user to "cheat" and suppress is often going to be very useful.

Any stateful instance could potentially be in an "alive" state or not. But the specifications that are most worth capturing are the alive-state specifications. We can't say otherwise without sometimes _losing_ information that would have been valuable for the alive state. There are already plenty of strategies for containing the damage of the "dead" states (e.g. careful instance control; making every method throw ISE() if the instance is invalidated, etc.). Adjusting field annotations isn't going to do anything to help that situation anyway.

Chris has brought up a potentially very useful guideline for annotating an API: assume that some bytecode rewriter is gratuitously inserting null-checks everywhere the annotations don't tell it not to. Of course, we'll need exceptions to that rule. Maybe this might be one of them: such checks probably make a lot more sense for inter-class API usages than intra-class.

**Comment by cpovirk** [comment]
To (eventually) elaborate on the guideline that Kevin just referred to:

I'm going to first set aside initialization so as to start the discussion with invalidation.

I don't love any of our options for invalidation (or, to be honest, for initialization :)). But my thinking has been to approach this from the opposite direction: If `Foo` is going to invalidate `bar`, then it needs to mark it as `@Nullable`. Then it may _supplement_ that with a hypothetical JSpecify `@NonNullWhenThisObjectIsValid` annotation. (I suppose that this new annotation could even [imply](https://github.com/jspecify/jspecify/issues/35) `@Nullable`, in which case it could _replace_ the `@Nullable` annotation on `bar`.)

(Even if we don't have such an annotation, users can still take steps to reduce the pain. For example, they could introduce a `private Bar requireBar()` method that performs a null check or cast. ([I said "reduce," not eliminate](https://github.com/google/guava/blob/e1ec6968a7d584281f56a38674d6722bea83811c/guava/src/com/google/common/collect/CompactHashMap.java#L1146) :))

A big reason for my thinking is, as Kevin suggests, tools like Kotlin that insert runtime nullness checks: Tools like that just _won't let you_ put `null` into the field, no matter what tricks and suppressions you attempt (OK, barring reflection or something).

As Kevin also says, this is mostly an issue for inter-class API. But I'll note that sometimes people do press the button in IntelliJ that converts Java code to Kotlin code, and it would be nice if that tool didn't produce code with nullness errors from intra-class usage, either. Plus, the line between inter-class and intra-class is not necessarily always clear, such as when a class's implementation includes a private implementation of a public API. (But I haven't thought about this much.) Still, I agree with Kevin that inter-class is by far _more_ important.

Sometimes I've found it helpful to think in this framework: A `Bar` field is "just" a `Holder<Bar>` with methods `void set(Bar)` and `Bar get()`. A nice feature of this framework is that it gives a somewhat strict and precise yet still lenient and fuzzy answer to questions around initialization: You'd better never _write_ `null` into the field. And in fact, you'd better never _read_ `null` from it, either. But you might overwrite the `null` that the field was default-initialized with, and tools are unlikely to care because that `null` is never "passing through" the imaginary `get` or `set` APIs.

**Comment by kevinb9n** [comment]
Your model is also valid and we can have a hearty discussion about which one to go with. My main argument, perhaps, is that a "while-alive" spec is merely what most people want for most purposes, whereas a "least-common-denominator" spec can easily be what _no one_ wants, for no purposes. :-)

I don't think we should feel bound by what Kotlin is currently doing; in any future where we accept "my" model then we'd be trying hard to persuade Kotlin of why it's the right one, in which event maybe it would stop doing that.

**Comment by cpovirk** [comment]
It will be good to talk to the Kotlin people (and Android people, since this issue is common in the Android lifecycle). My impression is that they've given a lot of thought to this issue. For example:
- [this decision to not provide a way to null out `lateinit` properties](https://youtrack.jetbrains.com/issue/KT-9327#focus=Comments-27-2419131.0-0)
- [this advice on providing `private val binding get() = _binding!!` to wrap `private var _binding: ResultProfileBinding?`](https://developer.android.com/topic/libraries/view-binding#fragments)
- [this sample code for a way to perform the initialization+invalidation+wrapping automatically](https://github.com/android/architecture-components-samples/blob/30d783b4e64019aeadc8d082f1c23cf93c776f10/GithubBrowserSample/app/src/main/java/com/android/example/github/util/AutoClearedValue.kt)

My overall impression is that they want for nullness to be as "real" a part of the type system as possible. Given that, I would be a bit surprised if they wanted to support a way of putting `null` into a non-null field. I say that especially when "fields" in Kotlin can be properties with [custom accessors](https://kotlinlang.org/docs/properties.html#getters-and-setters), including those [written in Java](https://kotlinlang.org/docs/java-interop.html#getters-and-setters): Which of those count as "putting `null` into a field?"

A big difference between Java and Kotlin, of course, is that Kotlin lets you dereference a nullable field by writing `bar!!`, whereas nullness-checked Java requires some kind of `!= null` check, assertion, or call to a utility method. It may be that our best strategy for invalidation is to make `@Nullable` values easier to deal with, either for "non-null when valid" fields specifically or for values in general.

Still, if JSpecify annotations catch on as we hope, that may provide Kotlin new motivation to match our model. But when we're talking mainly about private fields, maybe that's still not a big motivation: The main case in which matching would be important is when converting Java to Kotlin, and presumably their migration tools just generate a `bar: Bar?` property and use `bar!!` when necessary. It's just not a huge cost in Kotlin relative to in Java.

**Comment by kevinb9n** [comment]
We've been debating whether the right practice for an API is to annotate toward the "alive state" or to the "general state" (or some third possibility). Note I'm trying to set aside the idea of additional annotations, because I think we want a sane approach without them, which they would simply try to improve further upon.

But do tool implementors actually need to know this answer? What might they want to do differently based on one answer or the other?

If it's not much, or if it doesn't harm anything for different tools to answer differently, it seems like we'd be well-justified in punting. We're priortizing APIs, and the problem here is only with non-final fields, and non-final fields are extremely rare in APIs (and nasty in worse ways than just nullness if they do show up). There's some question of what *exactly* "punting" would look like.

**Comment by kevinb9n** [comment]
I've moved the stuff about "objects with lifecycle" to #225. I think it's most (?) of the "meat" of this issue.

Having done that, I'm actually not sure what the ongoing distinct purpose of this issue becomes. I believe the plan is that field types should work like all other types in API-shaped elements.

I think a tool would probably want to warn if a non-nullable non-final field is never set by some constructor, but I'm not sure we need to say anything about that.

**Comment by cpovirk** [comment]
If I were to call anything "field-specific," I would go with [the model that a `Bar` field is "just a `Holder<Bar>`."](https://github.com/jspecify/jspecify/issues/39#issuecomment-892144846)

But I agree that it makes sense to focus on lifecycles.

**Comment by kevinb9n** [comment]
Okay, I think that makes sense. We will want to write up that model somewhere, and this issue might as well track that part of it.

**Comment by kevinb9n** [comment]
In [Data in Java Programs](https://docs.google.com/document/d/1J-a_K87P-R3TscD4uW2Qsbt5BlBR_7uX_BekwJ5BLSE/preview), I emphasize that a value is always passing from "source" to "sink", and a variable is a special thing that can act as either of those.

This applies to reading/writing fields, and it does also already apply in the same way to reading/writing array elements, just as you want. In both cases, in _theory_ a user could want to annotate the read case and write case separately, but for simplicity's sake we will ask them to make a few compromises.

That compromise might look like "look there's just one type and it has to do double duty, just like the base type" or maybe more specifically "annotating for the read case is more important than the write case" (?).

**Comment by kevin1e100** [comment]
> That compromise might look like "look there's just one type and it has to do double duty, just like the base type" or maybe more specifically "annotating for the read case is more important than the write case" (?).

Is this referring to whether one should be able to assign `null` to an `@NotNull` field? To me that's like passing `null` to a `@NotNull` method parameter, so a sound tool would error on it, modulo this being an implementation concern that can be handled by individual tools. Are there additional concerns?

**Comment by kevinb9n** [comment]
Don't worry, I believe I'm just confirming something won't be possible which you already never thought would be possible anyway.

"My variable is null only when unintialized. But it can actually be read before initialization (of course just be null then). So, I'd like to declare it as nullable for purposes of reading but non-nullable for purposes of writing!"

Us: "yeah sorry no"

This is only to say that if the mental model of a variable as either "holder" or "pair of source and sink" proves to be a useful conversational/educational tool, then we just want to be able to explain that annotating the inward and outward cases differently from each other might be _theoretically_ sensible but just not supported because yuck.

**Comment by kevin1e100** [comment]
I see and don't disagree.

> I'd like to declare it as nullable for purposes of reading but non-nullable for purposes of writing!

Checkerframework's `@MonotonicNonNull` has that flavor/effect, fwiw. I don't know that this is something one would want to use in a non-private field, however, so I feel it's fine to consider out of scope for now.

Kotlin's `lateinit` is, for comparison, a slightly different take: reading a property `lateinit var foo: String` is assumed non-null but causes a runtime check emitted by the compiler, and additionally, it's possible to [check whether the property has been initialized](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/is-initialized.html) (instead of "reading `null` from it").

**Comment by kevinb9n** [comment]
At this point, I don't actually see anything specific worth keeping this issue open for (and we would file it separately if we do).

**Comment by kevinb9n** [comment]
(re-close with summary)

**Comment by kevinb9n** [comment]
I still think that I said all there really is to say when I closed this, but I'll try again.

* Most of this is more generally about any stateful object that transitions into and out of its "usable" state (i.e. has lifecycle), and that's still #225.
* I don't see this discussion of `a variable is just a Holder` as needing an issue to track it.
