### ISSUE TITLE
Relationship of nullness findings to java unchecked warnings

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#395]
(Minor.) In any case where:

* We would issue a nullness finding, and
* Javac already issues an unchecked finding, and
* We're doing this for highly analogous reasons

My first claim is that _in concept_ a nullness finding is redundant.

Claim 2 is that I think JSpecify can/should simply require that tools _do_ recognize a finding anyway. A tool can still decline to actually _issue_ that finding to the user (and maybe should).

Another strange option might be to specify that tools should actually recognize _both_ `"nullness"` and `"unchecked"` as a valid suppression of this particular finding. (A build that doesn't use -Xlint:unchecked would then still get them, which might or might not make sense.)

Any other stance seems like it could encumber tools with having to reverse engineer "did javac warn here already or should it have?" which obviously we don't want.

**Comment by cpovirk** [comment]
I think I agree with Claim 2 and maybe also Claim 1, but here is a sorta kinda counterargument to Claim 1 that I'm pondering:

A legacy codebase contains a cast from `List<?>` to `List<Object>`, whose `unchecked` warning the owners have suppressed because it's safe because they only ever _read_ from the list. They might not consider a further `nullness` warning to be "redundant," since it's actually calling out a _further_ assumption, which is that the list doesn't contain nulls. And so they might not want for `@SuppressWarnings("unchecked")` to suppress such a warning.

But I'd guess that that's a somewhat unusual case. Certainly Guava ended up with 10 copies of `@SuppressWarnings({"unchecked", "nullness"})`. (But arguably that's really not that many! However, I'm not sure how aggressively the reference checker warns on casts.) In contrast... well, I guess I can't simply grep for "How many places _would_ that have happened if we hadn't decided to address the `nullness` error in some way other than suppression?" :\

Setting that aside: Claim 2 has me wondering how easy it will be to distinguish "a cast that is unchecked for nullness reasons" from "a cast that is unchecked for nullness _or other_ reasons"... at least without "having to reverse engineer 'did javac warn here already or should it have?'" :) Can we "check only the nullness parts" the way that we otherwise do? But I am nowhere near up to thinking about JLS 5.1.6.2 and such things at the moment.

**Comment by netdpb** [comment]
**Current decision**: JSpecify will require conformant tools to recognize nullness issues even when there are also Java unchecked warnings for the same reason. Tools do not have to report them to users if they feel that the warnings would be redundant.

**Argument for changing**: None.

**Timing**: This must be decided before version 1.0 of the spec.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by netdpb** [comment]
**Decision:** JSpecify requires conformant tools to recognize nullness issues even when there are also Java unchecked warnings for the same reason. Tools do not have to report the nullness issues to users in that case. (In general, conformant tools do not need to report anything in particular to their users.)
