### ISSUE TITLE
Decide whether to include a `@NonNull` annotation

### ISSUE THREAD

**Issue by dzharkov** [jspecify/jspecify#4]
\[TODO: direct link to doc about this issue\]

The question was initially asked by `@cpovirk`

To be honest, I didn't get the question

**Comment by kevinb9n** [comment]
Here is what we are working on:

1. Explaining, convincingly, that there is actually a reasonably sane world in which `@NonNull` does not exist in our project. (This step is NOT convincing anyone to *like* that world, just that it does fundamentally make sense.)

2. Explaining the benefits and the drawbacks of having a `@NonNull` annotation relative to that picture. Warning: we have so far come up with about TEN arguments on each side. We are working to distill that morass down into something consumable for you. If you are keen to have it shared to you before then, let me know.

For a long time, I believed there was really no controversy to be had here; of *course* we would need `@NonNull`. I was dead wrong: while we may want it, there really is a case to be made either way, and our sacred duty is to fully explore both sides.

We've been talking about an initial 0.1 pre-release that supports only the use cases of (a) fully, properly annotated source files and (b) all-legacy source files, but nothing in between. (Of course, that fails a key project requirement, which is why it's not called 1.0.) Also, support for non-nullable type projections would come later as well (if at all; #86). If our working decisions on issues like #12  go the way the currently seem to be, then this means that we would not actually have much need for `@NonNull` for this 0.1 release yet no matter which way we end up deciding here.

Hopefully that means the time pressure is a little reduced on making this decision.

**Comment by sdeleuze** [comment]
FYI we have 16 concrete use cases of `@NonNull` in Spring Framework codebase which is (a) fully, properly annotated source files. The use case is to avoid unnecessary checks on a subclass that returns for sure a non-nullable value whereas the interface or the superclass define `@Nullable`. For example https://github.com/spring-projects/spring-framework/blob/a11a592734b4518332239425973cf11cb4f80fcf/spring-jdbc/src/main/java/org/springframework/jdbc/core/namedparam/MapSqlParameterSource.java#L169.

We can't really avoid `@Nullable` on the interface or superclass because we want to be defensive and force null-safety checks when they are used, and only skip those when the specific subclass annotated with `@NonNull` is used.

I guess we can live with 16 warnings in 0.1 release, but we would like a proper solution that allows 0 warnings after.

**Comment by cpovirk** [comment]
Thanks: I am embarrassed to discover that, as far as I can tell, I had not searched through Spring for usages of `@NonNull`.

For the 16 that you have, all would be unnecessary under jspecify semantics: Our annotations aren't automatically inherited by overrides, so overriding `@Nullable Foo getParameterNames()` with `Foo getParameterNames()` already makes the return of the latter non-null.

Our recent discussions about sample inputs remind me that I should add some samples for this case. I'll try to come back and link them from this post once I've done so.

(Of course, in all this, I'm assuming that you apply `@DefaultNonNull` (or make your `@NonNullApi` an alias for it), since your files are fully annotated. The big use case for `@NonNull` is for code that does _not_ use `@DefaultNonNull`. We have been preparing some giant docs for the eventual discussion :))

**Comment by cpovirk** [comment]
kevinb9n suggested that we close this thread in favor of a new one -- not with the intention of having this discussion tomorrow but at least to give interested parties a rough idea of the areas of past conversation.

When we're ready to make a decision, we'll clean up and old, unpublished doc we have about this -- or throw it out and write a new one, too :) But for a quick summary, see #229.
