### ISSUE TITLE
Allow annotating null-markedness at method/constructor level?

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#43]
It's possible we don't need to.  It also has drawbacks, such as when you compare two signatures that look similar without realizing they're very different.

**Comment by kevinb9n** [comment]
I consider this question to be back on the table. After we get a revised/improved requirement about incrementality/adoptability I will come argue why I think we might need method/constructor-level defaults at least. We would still persuade users to really try not to leave things that way but use it as a temporary stepping stone only (in full knowledge that the advice won't always be heeded).

**Comment by cpovirk** [comment]
Random point that shouldn't weigh too heavily here (and which I may have made previously somewhere?):

In domains _other_ than nullness, we are likely to have annotations that apply at both the class scope and the method scope. So there could be a _tiny_ argument for supporting that here for "consistency."

One example is `@MustUseResult`. However, that example is somewhat different: `@MustUseResult` is (arguably?) an intrinsically per-method concept, not a per-type concept. At the very least, there's no _other_ annotation that it goes along with. (Contrast with `@NullExplicit`, which goes along with `@Nullable`.) So maybe consistency between `@MustUseResult` and `@NullExplicit` would actually be _misleading_.

Very minor point in either case -- just trying to get it out of my head.

**Comment by kevinb9n** [comment]
I should point out that, our adoptability requirements notwithstanding, supporting partially annotated files is out of scope for 0.1, so we shouldn't worry about this issue _right now_.

**Comment by cpovirk** [comment]
By coincidence, I just learned about [annotations on Java's forthcoming "records."](https://openjdk.java.net/jeps/384#Annotations-on-records) The impact on our defaulting annotations looks "interesting"....

It sounds like records will let you write:

```java
record Foo(@DefaultNonNull Bar bar) {}
```

Then Java will effectively "paste" `@DefaultNonNull` onto the field, getter method, and parameter of the constructor it generates -- or rather, all of those locations where it is permitted. So:

- Suppose that we forbid defaults on methods. Then surely we'll forbid them on fields and parameters, too. That would make `@DefaultNonNull` useless on records. (Hopefully javac would outright forbid it, but I haven't confirmed.) But it's consistent (which is good), in contrast to...

- Suppose that we allow defaults on methods but not fields or parameters. Then Java will definitely allow the annotation on components in the record header, and it will:
    - copy it to getters: That's presumably as intended.
    - _not_ copy it to fields: That's presumably "wrong" but fairly harmless: The fields are `private` fields, and there is not any source code that directly accesses those fields, so checkers aren't likely to care about the annotations. (I'm not even sure yet if javac generates getter-implementation _bytecode_ at compile time (which a bytecode-analyzing tool could theoretically look at -- though it could easily exclude such generated code) or if it's all done at runtime with `invokedynamic` or similar.)
    - _not_ copy it to the constructor parameter: That's presumably wrong, and it matters: If I thought that I was making `Bar` non-nullable in my example above, I turn out to be wrong. Worse, the getter _says_ that it's non-nullable, but it's a lie!

- Suppose that we allow defaults on methods and parameters (#128) -- and let's set aside fields, which are less interesting, as discussed above. Then Java will copy the annotation to the constructor parameter, as well. This makes the getter and the constructor parameter consistent, but it opens up the potential confusion discussed in #128.

I would be sad to leave off method-level defaults, but records now have me thinking twice....

**Comment by cpovirk** [comment]
(Note that record authors can manually declare the getters or constructors themselves, specifying the appropriate annotations. And they can probably just _annotate the whole record at once already_ -- especially since records will appear only in newer code, which we can hope is more likely to get annotated for nullness than legacy code is. So I am probably making too much of a minor issue that arises only if users do something highly weird.)

**Comment by cpovirk** [comment]
I still think it's reasonable for this not to be our top priority, but another quick thought:

Even if we wanted to tell users "Don't expose a half-annotated class to users," I think that method-level defaults could be useful: When I go to annotate a legacy type, it could be nice to be able to annotate a single method or two, deal with the fallout, and then repeat until the whole class is done. Then I would switch to a class-level annotation before submitting my change. This iterative process is probably less intimidating -- and maybe even easier, since I can easily pick out all errors related to a given `getFoo()` method to address together.

**Comment by kevinb9n** [comment]
I still think method scope makes good sense, but I'm really leery about anything that lets @NullMarked go any narrower than that. That really messes with my desire to believe that there's just two different "modes" that my code can be in. I would rather there was a plain old `@NonNull` type annotation at that point!

**Comment by kevinb9n** [comment]
About records: if we have a "scope annotation", and that includes target type METHOD, and then this automatically allows it to be used on a record attribute .... well, perhaps we can at least explicitly specify that it has no meaning when used on a record attribute (or, I'm not sure here, but maybe specify it to be a wrong application of the annotation?) This seems similar to how javac lets you put TYPE_USE annotations in three places that aren't type usages, and we may similarly have _something_ to say about what happens if you do it.

**Comment by cpovirk** [comment]
We could definitely say that `@NullMarked` on a record component has no meaning to JSpecify. But I looked into what happens if someone compiles code with such an annotation (either by using a tool that doesn't care about JSpecify annotations or by suppressing any tool warnings/errors). It turns out that there will be no way for consumers of the `.class` file to distinguish it from a record in which someone applied `@NullMarked` to the accessor method. That is, the following two source files produce essentially identical class files:

```
import org.jspecify.nullness.NullMarked;

record RecordAnnotation(@NullMarked Object o) {}
```

```
import org.jspecify.nullness.NullMarked;

record RecordAnnotation(Object o) {
  @NullMarked 
  public Object o() {
    return o;
  }
}
```

(I confirmed this with `jdk-16-ea+34`, which is what I had handy. I just had to edit [the `java9` copy of `NullMarked`](https://github.com/jspecify/jspecify/blob/main/src/java9/java/org/jspecify/nullness/NullMarked.java) to apply to `METHOD`. And this fits with [the section on annotations in JEP 395](https://openjdk.java.net/jeps/395#Annotations-on-record-components), which I think is the final version, replacing the JEP 384 link I used above?)

We might have to just live with this. But it's something to keep in mind for #128.

**Comment by kevinb9n** [comment]
copying a @kevin1e100 comment from https://github.com/jspecify/jspecify/issues/127#issuecomment-884566188 that seems relevant here:

> Using this annotation on something like an inner class (or a method) could
> also be useful but does seem to create some complexity (or at least room
> for misunderstanding) if the outer class has type parameters. In
> particular, the question becomes how to interpret usages of the outer
> class's type parameters in the inner class. Minimally we'll have to define
> that case, but I'm also simply not sure what most users will expect to
> happen in that case, and how close we can and should get to that
> expectation.

**Comment by kevinb9n** [comment]
(TODO: slice off record-specific discussion to its own issue)

**Comment by kevinb9n** [comment]
> > Using this annotation on something like an inner class (or a method) could
> > also be useful but does seem to create some complexity (or at least room
> > for misunderstanding) if the outer class has type parameters. In
> > particular, the question becomes how to interpret usages of the outer
> > class's type parameters in the inner class.

(Taking "inner class" to mean a non-static named nested class, or local class not in a static context. Which I think is the useful definition.)

**Proposal** (reacticons appreciated):

1. Every type variable is declared in one and only one place (here, the containing class), and the null-markedness of that location is in effect. We should not pretend the same type variable is differently-bounded in one scope vs. another.
2. When code forms a new parameterized type of the surrounding class's type (so, not using the type variable, just giving a type argument to the type parameter exactly as an external consumer would do), it should have the same meaning whether that _is_ the surrounding class or just a sibling class.
3. Task: we should review what kinds of confusion/surprise that might cause and add helpful documentation about them. Such confusion can also be cited as a good reason to actually complete the migrations you start -- but a less-good to delay starting them!

**Comment by cpovirk** [comment]
I'm having trouble following the second bullet. At least part of the problem is that I'm not sure what the antecedent for "that" is. I'm not sure if there's more to the problem than that.

**Comment by kevinb9n** [comment]
Now to the overall issue,

**Proposal** (reacticons appreciated): 

Decide affirmative: both `@NullMarked` and its negation (#127 / #109) may target methods and constructors.

(Records-specific complications should be filed separately.)

More broadly, I'm advocating this principle: features that we expect to help users apply `@NullMarked` a little sooner, more easily, or less annoyingly should be prioritized highly even *pre-1.0*. The more adoption we can get before finalizing designs the better.

**Comment by cpovirk** [comment]
+1 for affirmative to this question.

As for the broader point, I have a partial disagreement that is resisting my attempts to summarize it here. I'll finish up the doc that I've been working on and share it, hopefully within a few days.

**Comment by kevin1e100** [comment]
I'm not strictly against this, but I do wish we could avoid it: the conceptual simplicity of entire classes either in or out seems very appealing.

**Comment by kevinb9n** [comment]
In our last meeting we made a "working decision" of "yes" for the time being. We'll proceed with documenting and implementing that way and find out how it goes.

**Comment by cpovirk** [comment]
I had observed in https://github.com/jspecify/jspecify/issues/50#issuecomment-1016598323 that bytecode doesn't always fully distinguish between what's done by a field initializer and what's done by a constructor. We avoided the important part of that problem by rejecting `@NullMarked` on fields, but we're still _theoretically_ vulnerable to part of it by permitting `@NullMarked` on constructors.

Fortunately, constructors present much less of a problem: Basically any _class_ defined inside a constructor produces bytecode that identifies it as "enclosed by" that constructor. Thus, tools that are looking at that class will know to consult the annotations on the constructor. (Presumably the same would hold true if Java were to permit methods defined directly inside methods in the future.)

(This is different than the situation with fields: If we see an anonymous class with no enclosing method/constructor, then we probably(?) know that it's defined either in a `static` (`clinit`) block or in the initializer of _some_ field, but we don't know which of those it is, and we certainly don't know _which_ field. Thus, we wouldn't know how to react if a class had a `clinit` method or if only some fields in a class were null-marked.)

But wait, not _every_ class defined inside a constructor produces the bytecode we want:

```
$ cat EnclosingInLambda.java 
class EnclosingInLambda {
  final Supplier supplier;

  EnclosingInLambda() {
    supplier = () -> new Object() {};
  }

  public static void main(String[] args) {
    System.out.println(new Enclosing().supplier.get().getClass().getEnclosingClass());
    System.out.println(new Enclosing().supplier.get().getClass().getEnclosingMethod());
    System.out.println(new Enclosing().supplier.get().getClass().getEnclosingConstructor());
  }

  interface Supplier {
    Object get();
  }
}

$ javac EnclosingInLambda.java && java EnclosingInLambda
class Enclosing
private java.lang.Object Enclosing.lambda$new$0()
null
```

`new Object() {}` is quite clearly enclosed by the `EnclosingInLambda` constructor as far as the syntax tree goes. But its bytecode (and thus the `java.lang.reflect` API) disagrees. So, in theory, a tool that tried to analyze any APIs (or implementation code) declared inside that anonymous class could behave differently based on whether it operated on source code or bytecode.

Fortunately again, this feels like a theoretical problem, unlikely to bite anyone for a very, very long time and unlikely to be a significant problem even when it does.

**Comment by cpovirk** [comment]
Oh, cool, that got fixed:

```
$ ~/jdk-19-ea+26/bin/javac EnclosingInLambda.java && ~/jdk-19-ea+26/bin/java EnclosingInLambda
class EnclosingInLambda
null
EnclosingInLambda()
```

See [JDK-8215470](https://bugs.openjdk.org/browse/JDK-8215470).

**Comment by cpovirk** [comment]
OK, so the other thought I had here, which is _even less_ important, is that that bytecode for "pure implementation code" doesn't offer us a way to know whether it comes from source code inside a constructor or source code inside an initializer (whether a field initializer or an instance initializer).

Again, this seems much, much, much less likely to matter. Like, is a tool that consumes bytecode really going to differentiate between a `Foo[]` local variable declared inside a `@NullMarked` constructor ("an array of non-nullable `Foo`") a `Foo[]` local variable declared inside a non-`@NullMarked` instance initializer ("an array of unspecified-nullness `Foo`")?

So I'm noting this for completeness and to get it out of my head.

**Comment by msridhar** [comment]
As another data point in support of allowing `@NullUnmarked` at the method / constructor level, the [NullAway Annotator](https://github.com/nimakarimipour/NullAwayAnnotator) tool automatically inserts `@NullUnmarked` at the narrowest scope that removes errors it cannot automatically resolve.  We chose to insert `@NullUnmarked` at the method / constructor level whenever possible, so that the rest of the code in the containing class still gets checked by NullAway (which makes future changes to that other code safer).

**Comment by netdpb** [comment]
The current, working decision, as of 2022-05-16, is that `@NullUnmarked` and `@NullMarked` are applicable to methods and constructors.

This issue must be finalized before the release of version 1.0 of the annotation JAR.

None of the discussion above has made a strong case for changing that decision, as far as I can tell.

**I propose this decision be finalized for 1.0.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and _briefly_ explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative. Please do not add a thumbs-down only because you have a preference for an alternative.

**Comment by netdpb** [comment]
**Decision**: `@NullUnmarked` and `@NullMarked` are applicable to methods and constructors.
