### ISSUE TITLE
Not possible to annotation a return enum @Nullable from a method

### ISSUE THREAD

**Issue by alexandrenavarro** [jspecify/jspecify#492]
Not possible to annotation a return enum with @Nullable from a method (compilation error).
Is it wanted?

**Comment by kevinb9n** [comment]
Hi, can you share the sample code?

**Comment by ascopes** [comment]
```java
enum Foo { BAR; }

static @Nullable Foo getBar(boolean isNull) {
  return isNull ? null : Foo.BAR;
}
```

does this not work?

**Comment by netdpb** [comment]
That should work. Which nullness analyzer are you using? What error are you seeing?

**Comment by agentgt** [comment]
@netdpb @kevinb9n @cpovirk  This is sort of orthogonal to this bug/issue but have you guys made it clear where to file bugs for the reference checker vs the spec itself?

I say this because I can see some future confusion of issues that are related with the spec (and doc) vs issues with the reference checker.

Right now in the https://jspecify.dev/docs/start-here/#how-can-i-get-involved

We have: 

> [File an issue](https://github.com/jspecify/jspecify/issues/new) to request a feature or if something is wrong.

Perhaps that should be clear that issues here should be about the spec and documentation? Then perhaps another link for the reference checker.

**Comment by alexandrenavarro** [comment]
I have problem with a method like that

@Nullable
AEnum map(AnotherEnum anotherEnum)

**Comment by agentgt** [comment]
@alexandrenavarro Can you paste the error output here. `javac` should not have a problem with you annotating the return of an enum method. Also can you paste the exact code in triple back ticks.

What I suspect might be your problem is if you do  have a true `javac` compiler error and not an analyzer error is that the enum is an inner class.

That is this will not work:

```java
@Nullable OuterClass.AEnum map(AnotherEnum anotherEnum) {}
```

It has to be:

```java
OuterClass.@Nullable AEnum map(AnotherEnum anotherEnum) {}
```

Or if you import the outer class:

```java
@Nullable AEnum map(AnotherEnum anotherEnum) {}
```

**Comment by alexandrenavarro** [comment]
The compiler error was "Annotation not applicable to this kind of reference".

I understood the problem, it was linked to the package before the enum.

It was like that in reality :

@Nullable com.mypackage.AEnum map(AnotherEnum anotherEnum) {


By importing the enum (and removing the com.package), like :

@Nullable AEnum map(AnotherEnum anotherEnum) {

The problem is solved.

In my specific case, I can do it but if you have same enum with different package (it was sometimes my case on my project because some people creates the same enum but in different package and use the 2 enum in the same classe which is not a good idea), you can have the problem.

You can close the issue if you want, it is really a rare case but it is not really clear at first why it does not work, it was the reason why I created the issue.

**Comment by netdpb** [comment]
I see. That is a feature of [how type-use annotations are applied](https://www.oracle.com/technical-resources/articles/java/ma14-architect-annotations.html#:~:text=Applying%20Type%20Annotations).

If you don't want to import, you can do this:

```java
com.mypackage.@Nullable AENum map(AnotherEnum anotherEnum) { ... }
```

Thanks for the question. We are updating some documentation for 1.0 that will include information about this.
