### ISSUE TITLE
Can @NullMarked target fields, method parameters, or local variables? [working decision: no, but see #310]

### ISSUE THREAD

**Issue by kevin1e100** [jspecify/jspecify#50]
From proposal comment thread by @brychcy:

> But types can appear in the field's declaration (for generics or array contents) and there can be an initializer (which can contain type declarations as it can be an anonymous type or lambda).
> 
> Same for local variables and the declaration part of parameters.
> 
> Eclipse's `@NonNullByDefault` is supported in all these locations and the effect goes to the end of the initializer ( if present )
> 
> This also has the advantage that `@NonNullByDefault` doesn't need a `@Target` annotation, which would be problematic as the MODULE value is not understood pre-java9.
> 
> Yet I won't argue it is absolutely necessary in a common standard - I don't know how hard it would be for other tools to implement this.

No question these locations could be useful (though maybe mostly for implementation checking, with the possible exception of method parameters?), but I believe they don't define a "scope" per JLS, hence why they were originally excluded \[edit: cpovirk adds: nor are they ever the element that ["encloses" anything in the Java compiler API](https://docs.oracle.com/en/java/javase/14/docs/api/java.compiler/javax/lang/model/element/Element.html#getEnclosingElement()), a natural match to [how we define scoping](https://github.com/jspecify/jspecify/issues/154)\].  Moreover, anonymous inner classes' bytecode I believe doesn't indicate if they were defined "inside" one of these things, but maybe tools never need to look at bytecode for them?

One question I have is what the use cases are for placing `@NonNullByDefault` in these locations?  How commonly do users do that?

**Comment by cpovirk** [comment]
> Moreover, anonymous inner classes' bytecode I believe doesn't indicate if they were defined "inside" one of these things

I just wanted to add that the importance of this sank into me recently: If we imagine a bytecode rewriter that adds null checks for non-null parameters and return values, _then_ it matters whether methods in an anonymous class are "enclosed by" the field (or local variable) or not. Since the bytecode rewriter can't tell, we'd be forced to say "no, they're not enclosed." This may be surprising, especially because it differs from `@SuppressWarnings("nullness")`, which I'd expect tools _would_ apply to any code inside a field initializer. (And tools get away with handling `@SuppressWarnings` that way because it has source retention -- an interesting upside to source retention that I'd never considered!)

So, to me, that makes this feature request, which we were already not planning to do, a non-starter :)

(OK, technically, I don't think this concern affects _method parameters_, only fields and local variables....)

**Comment by cpovirk** [comment]
I've filed #310 to think more about the `FIELD` case specifically.

**Comment by netdpb** [comment]
The current, working decision, as of 2022-03-20, is that `@NullMarked` and `@NullUnmarked` cannot target fields, method parameters, or local variables because those declarations do not enclose other nonlocal declarations. No compelling use case has emerged that requires such annotation targets.

No strong argument is made for changing that decision, except for fields, which are covered in #310.

This must be decided before version 1.0 of the jar.

**I propose the current decision be finalized for 1.0.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by netdpb** [comment]
**Decision**: `@NullMarked` and `@NullUnmarked` cannot target fields, method parameters, or local variables
