### ISSUE TITLE
Is `java.lang.Void` implicitly always `@Nullable` or should normal defaults apply? [working decision: no special treatment]

### ISSUE THREAD

**Issue by wmdietlGC** [jspecify/jspecify#51]
From a [discussion](https://www.google.com/url?q=https://www.google.com/url?q%3Dhttps://docs.google.com/a/google.com/document/d/15NND5nBxMkZ-Us6wz3Pfbt4ODIaWaJ6JDs4w6h9kUaY/edit?disco%253DAAAADR4CvWM%2526ts%253D5d388595%2526usp%253Dcomment_email_document%2526usp_dm%253Dtrue%26source%3Dgmail%26ust%3D1564089317018000%26usg%3DAFQjCNE12fXn3jB8HFxYLt9MJ4XO3HkMkg&source=gmail&ust=1564091935921000&usg=AFQjCNHqVTX52iyPbA2LenruCeMeaGsNgA):

Werner Dietl:
Should we treat `java.lang.Void` specially? The only value Void can have is null. So defaulting it to `@Nullable`, even in a `@DefaultNotNull` context, would make that explicit. Using `@NotNull Void` to mark an unusable parameter doesn't seem useful, as the method could only ever be called with a null argument.

Kevin Bierhoff:
It certainly seems unfortunate to have to annotate `@Nullable Void` every time. I've been grappling with this a bit b/c I expect some tools to want to treat Void as "definitely null" (as opposed to possibly-null), which is a commonly used lattice element I believe but we don't have an annotation or effective specifier for it. I'd be curious what your take is on that. Would you mind filing an issue for the treatment of Void?

Kevin Bourrillion:
My current impression is that if we can't distinguish definitely-null from possibly-null we will still meet all of our requirements. That might be untrue, or we might have some reason to want to add it as a requirement, but barring those two possibilities we should be free to not worry about it.

I do think filing an issue on the question of whether `Void` can be implicitly assumed to be `@Nullable` is a fine move though.

**Comment by cpovirk** [comment]
I still feel pretty good about _not_ having a special case for this. That said...

I did just hear about some fallout from `@Nullable Void` that was more noisy than I'd been picturing. (IIRC, I'd primarily been picturing `Future<@Nullable Void>`. As an aside, users _could_ choose to replace that with the terser `Future<?>` -- though arguably that is less clear, and for that reason, we recently went the direction of `Void` in Guava's [`Futures.submit`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/util/concurrent/Futures.html#submit-java.lang.Runnable-java.util.concurrent.Executor-).)

Anyway, the other common case for ending up with `Void` is with a visitor pattern. Here are some examples from Error Prone:
- https://github.com/google/error-prone/blob/4c49d590e41e875cc91d6061e6cb986f0ede559c/core/src/main/java/com/google/errorprone/bugpatterns/threadsafety/HeldLockAnalyzer.java#L193
- https://github.com/google/error-prone/blob/4c49d590e41e875cc91d6061e6cb986f0ede559c/check_api/src/main/java/com/google/errorprone/scanner/ErrorProneScanner.java#L461

Each of those files would need several `@Nullable` annotations on its `Void` return types. This is arguably extra unfortunate when many visitors don't care about return types in the first place (and so even `Void` -- and the `return null` it requires) is extra noise. (Granted, one option is to switch from `Void` to a dummy type with a single instance.)

That still seems like the lesser evil to me. In addition to [the arguments I made above](https://github.com/jspecify/jspecify/issues/51#issuecomment-514830030):
- If tool authors provide migration tooling, it can add `@Nullable` to every occurrence of `Void` automatically.
- We can always hope that nullness is a language feature _someday_, at which point users can hopefully write `Void?` or something instead of `@Nullable Void`. (For that matter, we can hope that language features like sealed classes and enhanced `switch` reduce the need for visitors specifically.)

**Comment by kevin1e100** [comment]
Right visitors are a common reason to reach for `Void`.  My guess is though that visitors (with parameterized return) aren't all that common outside compilers, so while `@Nullable Void` is a nuisance for tool vendors in that context, it may not be for developers at large.  Additionally this may be an issue we can simply punt on and get back to later.

Just to say this explicitly, what's "special" about `Void` is that `null` is its _only_ valid value.  That means that `@NonNull Void` is a vacuous type, inhabited by _no_ values.  Also, `Void` values are _definitely_ `null`, which tools could hypothetically special-case.  If they did special-case then `@NonNull Void` would be a contradiction, aka, unreachable (like Kotlin's `Nothing` type).

**Comment by cushon** [comment]
> If tool authors provide migration tooling, it can add @Nullable to every occurrence of Void automatically

+1

Here's another compiler-like visitor example where I had to add a bunch of `@Nullable Void`s: https://github.com/google/turbine/commit/873a1be5c0e07feb4edff200979523066bddccfa. It's a little unfortunate, but I agree with the earlier discussion about this not being a very common case and there being a high bar for special cases.

**Comment by kevinb9n** [comment]
(Note this issue is closed; is there something that merits reopening it or opening something else?)

Suggesting `@Nullable` on every `Void` might be a reasonable default, and I think nothing else could make sense for a parameter or variable type. But -- just to check my understanding -- for a return type is non-nullable `Void` also occasionally useful as that "nothing" type? For example, for a Callable that never completes normally? In that case, maybe passing the result of `call()` to anything is always bogus and would probably get the error it deserves.

**Comment by cushon** [comment]
(I found this while trying to find previous discussions on `java.lang.Void` while creating the change I linked to earlier. I wasn't advocating for reopening/revisiting the conclusion, but I figured I'd add a note. If we see a a lot more examples of this, especially ones outside the known compiler/visitor use-case, it might be worth considering.)

(Another meta-comment: should there eventually be a home for write-ups of decisions like this in the user guide or an FAQ or something? Having to write `@Nullable Void` make sense but is also a little unintuitive, it might be a useful sort of thing to capture somewhere user-facing.)

> maybe passing the result of call() to anything is always bogus and would probably get the error it deserves

That makes sense, but to take that further, is passing anything other than `null` for `Void` always a little weird? Even if the callable returns normally I generally would prefer `callable.call(); foo(null);` to `foo(callable.call())`.

**Comment by cpovirk** [comment]
I just got asked about this by a user again :)

My initial thinking was that not much significant had changed during the course of this thread. From my perspective, the biggest thing was encountering [the visitor use case from over a year ago](https://github.com/jspecify/jspecify/issues/51#issuecomment-736699441).

But I'm realizing something else that I didn't appreciate: This is another case in which it matters that Kotlin takes types very seriously. So, if you try to use a `Future<Void>` in Kotlin, then Kotlin is could throw `NullPointerException` every time you use the result of `get()`. Now, it might be that Kotlin doesn't typically consider you to "use" the result, so maybe it's _usually_ safe... currently? But even if the runtime problems are unlikely, I've seen a bunch of compile-time problems during my work to annotate our codebase. To address them, I changed every(?) `Future<Void>` in Google's Kotlin codebase to `Future<Void?>`. But new instances have been creeping in.

Actual Kotlin appearance of `Future<Void>` are not quite what we're talking about in this issue, though: JSpecify wouldn't necessarily speak to what _Kotlin_ does for _Kotlin_ appearances of `Void`. (But it would be great if they'd either require users to write `Void?` or else treat the code that way automatically: That would result in bytecode that contains the equivalent of `@Nullable Void`. To investigate, I dug up an old Kotlin feature request for special handling of `Void`, [KT-20379](https://youtrack.jetbrains.com/issue/KT-20379).) But JSpecify _would_ speak to what Kotlin (and other tools) do for _Java_ appearances of `Void`.

And on that topic, I find my position softening. While I still wouldn't want to go down the road of [a general-purpose feature](https://github.com/jspecify/jspecify/issues/51#issuecomment-514878543), I'm finding a special case for `Void` specifically to be easier to swallow.

I _maybe_ got the impression that I'd heard a similar opinion from someone else not long ago...? But I don't want to put words in anyone's mouth.

And I still think we have plenty of time to figure this out.

**Comment by cpovirk** [comment]
Roman [replied on KT-20379](https://youtrack.jetbrains.com/issue/KT-20379/Add-handling-of-java.lang.Void-in-Kotlin-Code#focus=Comments-27-6021664.0-0). He pointed out that a _change_ that switches `Void` from implicitly non-nullable to implicitly nullable could break compilation of existing code (though I don't think it would break anything at runtime under our model). An example is `ImmutableList<Void>`. Another example is `Class<Void>`, at least if `Class` is annotated as [forbidding nullable type arguments](https://github.com/jspecify/jspecify/issues/78). Presumably users would then have to write `Class<@NonNull Void>` or `Class<Void?>`, or else our special case for `Void` would need its own special case for `Class<Void>` :)

**Comment by kevinb9n** [comment]
I think this illustrates that there are meaningful differences between `Void` and `@Nullable Void`. It's only that non-nullable `Void` is a very *weird* type, having no values whatsoever. So a method that accepts or returns `Void` can never be called (at least without warning), but for the examples you share, this situation seems actually... desirable, even?

Contrast with methods accepting or returning `@Nullable Void`: there's nothing weird about them at all, it's just that null is the only value you'll ever pass/receive in those positions.

So this means that in order for `Void` to default to nullable, we would sometimes see `@NonNull Void` to counteract that default, making it work "fully backwards" from everything else. This makes me feel better about leaving this resolved as it is.

**Comment by cpovirk** [comment]
We got another comment about this, so I thought about it briefly again :)

A way to get this off users' radar almost entirely would be an ugly compromise under which `Void` is _unaffected_ by `@NullMarked`, thus leaving its nullness unspecified. Similarly, Kotlin could treat appearances of `Void` in Kotlin code as having a platform type.

That is gross. And it might be a hard sell for Kotlin: The main problem inside Google has been `Future<Void>` (and occasionally some visitors in compiler plugins), but [the average Kotlin code seems not to use `Future<Void>`, etc. as frequently](https://youtrack.jetbrains.com/issue/KT-20379/Add-handling-of-javalangVoid-in-Kotlin-Code#focus=Comments-27-6352539.0-0). (That may be because Google's code interoperates more with existing systems that use `Future`.)

**Comment by kevinb9n** [comment]
Yeah, I think the downsides of the special-casing would be *approximately* the same in that case.

We can file the ugly unfortunate bulk of `Future<@Nullable Void>` under "motivation to keep striving toward the bright `Future<Void?>` future".

**Comment by kevinb9n** [comment]
For some code there's probably few actual `return null`s but the `@Nullable Void` type virally spreads out from there. Maybe they would rather just suppress the warning in the former case and drop the annotation from `Void`. It's not like anyone on the consuming side would see `Void` and expect to be able to get a non-null value from it.

**Comment by cpovirk** [comment]
I think that suppressions will serve fine in many cases (especially in some of the vexing examples, like [those involving the visitor pattern](https://github.com/jspecify/jspecify/issues/51#issuecomment-736699441)). But I would worry about suppressing in "normal" public APIs, again largely on account of Kotlin:

- While I've gotten a little confused about the exact circumstances in which Kotlin inserts runtime null checks for calls to annotated Java methods, I do know we saw code that we needed to change from `Void` to `Void?` or `Void` to `@Nullable Void` in order to avoid such problems.
- The problem may be bigger in the rarer case in which Kotlin code _overrides_ a method: If the method is declared to return `Void!`, then Kotlin will make you declare it that way, and it will insert runtime checks that force it to throw `NullPointerException` rather than ever actually return `null`. This is worse than the previous case, in which you likely had options (casts, explicitly specifying variable types? But again, I've gotten confused about this) that you could employ if you were seeing runtime values.

**Comment by netdpb** [comment]
**Current decision**: Do not special-case `Void`. Most (or maybe all) type usages of `Void` should be `@Nullable Void`, which is slightly awkward, but there are not that many type usages of `Void` anyway.

**Argument for changing**: It would be better not to have to type `@Nullable Void` all the time. `@NonNull Void` (or plain `Void` in null-marked code) is a vacuous type, so why make that easier to type/read?

**Timing**: This must be decided before version 1.0 of the spec.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by JojOatXGME** [comment]
> In fact, in a null-aware world, I would expect an equivalent of Kotlin's Unit to be more useful.

For me, it feels more like a workaround for a type system which does not support a simple names for nullable types. Even the documentation of `Unit` in Kotlin says, _“This type corresponds to the void type in Java.”_ In Java, we just use `Void` directly. Anyway, it might be a good tradeoff considering that it reduces the complexity of the type system. (Complexity can also be bad for the user, after all.)

In a language which has native support for using `void` in type arguments, I would assume that the language would just forbid access to the value of symbols of that type, making the value (and therefore the difference between `Void` and `Unit`) indistinguishable.

> But -- just to check my understanding -- for a return type is non-nullable `Void` also occasionally useful as that "nothing" type? For example, for a Callable that never completes normally? In that case, maybe passing the result of `call()` to anything is always bogus and would probably get the error it deserves.

Using `Void` in a way similar to `Nothing` doesn't work well in my experience. The problem is that it very often fails to provide a solution to satisfy javac.

```java
Void unwrapThrowable(ExecutionException e) {
  Throwable cause = e.getCause();
  if (cause instanceof Error error) {
    throw error;
  } else if (cause instanceof RuntimeException runtimeException) {
    throw runtimeException;
  } else {
    throw new IllegalStateException(cause);
  }
}

Result doSomethingOnThreadPool() throws InterruptedException {
  try {
    return executorService.submit(this::doSomething).get();
  }
  catch (ExecutionException e) {
    unwrapThrowable(e); // We cannot return anything as we don't have a valid instance of `Result`.
  }
} // <- Compile Error because the method may not return
```

In one project at my company, we had introduced our own `Never` type for that. It is similar to `Void` in terms that it cannot have any value (except from `null`), but it also extends `RuntimeException`. This allows to satisfy the compiler by just adding `throw` before the method call.

```java
Never unwrapThrowable(ExecutionException e) {
  ...
}

Result doSomethingOnThreadPool() throws InterruptedException {
  try {
    return executorService.submit(this::doSomething).get();
  }
  catch (ExecutionException e) {
    throw unwrapThrowable(e);
  }
}
```

**Comment by netdpb** [comment]
Thanks for the comment, @JojOatXGME. I don't think you're disagreeing with the proposed conclusion here (do not special-case `Void`). Please correct me if I'm wrong.

-----

To continue your discussion, I think there's a distinction between `Void` (one value: `null`) and `void` (no values). Kotlin's `Unit` is meant to be equivalent to Java's `void` in that you can omit it as a returned value since there is only one value and there is special syntactic treatment.

**Comment by JojOatXGME** [comment]
> I don't think you're disagreeing with the proposed conclusion here (do not special-case Void). Please correct me if I'm wrong.

No, I am not disagreeing, as I understand that the pain may not be high enough to add a special rule only for this class. I find the conclusion a bit sad, though.

> I think there's a distinction between Void (one value: null) and void (no values).

Yes, but `Unit` in Kotlin also has exactly one value.

> Kotlin's Unit is meant to be equivalent to Java's void in that you can omit it as a returned value since there is only one value and there is special syntactic treatment.

Yes, but Kotlin could have added the same special treatment for `Void?` instead. Of course, it wouldn't be a nice solution if you had to add the quotation mark (`?`) everywhere. I cannot think of another good reason why `Unit` is better off with a single instance, instead of using `null` as the only value. Anyway, I don't think that this is a bad solution. I am not actually sure why I pointed that out. 😅 I guess I somehow interpreted the following quote a statement about a universal truth (to which I wouldn't agree), rather than a statement in the context of the JVM-ecosystem.

> In fact, in a null-aware world, I would expect an equivalent of Kotlin's Unit to be more useful.

**Comment by netdpb** [comment]
> > I don't think you're disagreeing with the proposed conclusion here (do not special-case Void). Please correct me if I'm wrong.
> 
> No, I am not disagreeing, as I understand that the pain may very well not be high enough to add a special rule only for this case.

Whew!

> I find the conclusion a bit sad, though.

😢 

> 
> > I think there's a distinction between Void (one value: null) and void (no values).
> 
> Yes, but `Unit` in Kotlin also has exactly one value.
> 
> > Kotlin's Unit is meant to be equivalent to Java's void in that you can omit it as a returned value since there is only one value and there is special syntactic treatment.
> 
> Yes, but Kotlin could have added the same special treatment for `Void?` instead. Of course, it wouldn't be a nice solution if you had to add the quotation mark (`?`) everywhere. I cannot think of another good reason why `Unit` is better off with a single instance, instead of using `null` as the only value. Anyway, I don't think that this is a bad solution. I am not actually sure why I pointed that out. 😅

If you're wondering why _Kotlin_ decided to introduce `Unit` rather than just use `Void?`, then that's a good question, but not one I can answer. On the other hand, I think `Void?` is more complex than `Unit` because of that question mark.

**Comment by kevinb9n** [comment]
> I think there's a distinction between `Void` (one value: `null`) and `void` (no values).

Just to make it clear for posterity, the Java/JSpecify story is:

* `Void?` has one value, `null`
* `Void!` has no values
* `void` is not a type
