### ISSUE TITLE
Usage clarification about nullness semantics in case of abnormal occurrences

### ISSUE THREAD

**Issue by stechio** [jspecify/jspecify#544]
I'm facing a semantic problem about the way invalid structures relate to nullness.

Let's say the specification of a data structure requires one of its properties to be non-null, so its annotated declaration would look like this:

```
@NullMarked
interface MyData {
  MyPropertyType getMyProperty();

  . . .
}
```

Nonetheless, real-world instances of such data structure may (rarely) be invalid (getMyProperty() == null) and I need to deal with them too, as they cannot be rejected nor forced to any default. To my understanding, JSpecify is low-level and domain-agnostic (it is focused on nullness per-se, no matter its meaning in the domain context), so abnormal/unintended null occurrences should be expressed as well:

```
@NullMarked
interface MyData {
  @Nullable MyPropertyType getMyProperty();

  . . .
}
```

Such arrangement seems appropriate for static analysis (it ensures no predictable NPE could crawl across the execution), yet I wonder whether abnormal null occurrences should be dealt with like regular application exceptions instead, as implied by the former, specification-compliant arrangement (i.e., without `@Nullable`) — in such case, I would consider `NullPointerException` as an acceptable runtime exception, alike `NumberFormatException` or `IllegalStateException`.

What do you think about that?

**Comment by cpovirk** [comment]
Hi, thanks for the question. It's a question that you would really think we _should_ have a clear answer to, but it's proven to be quite slippery :) You might read [nullness-borderline-cases#the-something-has-already-gone-wrong-case](https://github.com/jspecify/jspecify/wiki/nullness-borderline-cases#the-something-has-already-gone-wrong-case) and some of the other sections of that page to see if any of them sound similar to the case you have in mind. I'm not saying that you'll come away with an _answer_, but it might set us up for a more focused discussion than we have sometimes had in past discussions of such questions amongst ourselves :)

**Comment by stechio** [comment]
Thanks for guiding me through this pesky topic ;) I'm pleased such fringe case has already come under scrutiny, whilst it's kinda uncomfortable to realize that its solution is stuck in a trade-off between **over-specific non-null** and **over-general nullable**, confirming the diametrically opposite alternatives I had empirically identified in my initial comment.

In my context, the over-general nullable, even if more robust (as it encompasses all possible occurrences), would be severily impairing/overkilling for API users, forcing endless defensive checks for something that is alien to the canonical data structure and statistically unlikely to happen; to me, the over-specific non-null feels more appropriate, flexible and clean (I will certainly add a caveat to javadoc informing users that data structures may be incomplete and require some fault protection).

**Comment by cpovirk** [comment]
One approach I have taken in a few unusual cases is to provide two ways of accessing the same value: one in which the type is nullable and one in which it's not. 

Here's an example with a nullable field (since it starts out null and can switch back to null later) but a method with a non-nullable return type and a runtime null check:

https://github.com/google/guava/blob/8dac907542aff4cae90209e93a810a8ca0bfff92/guava/src/com/google/common/collect/CompactHashMap.java#L1148

That might might not be quite as easy for an interface (like in your case), but it's another thought.

**Comment by stechio** [comment]
¿Something like this:

```
@NullMarked
interface MyData {
  @Nullable MyPropertyType getMyProperty();

  default MyPropertyType requireMyProperty() {
    return requireNonNull(getMyProperty());
  }
  . . .
}
```

That's certainly robust, but rather ugly as an API — feels like a matter of style (to trade API terseness with rock-solid runtime robustness), depending on how critical it is to prevent NPEs in the execution context.

**Comment by cpovirk** [comment]
Right. And yeah, I don't love it, myself.

I forgot to add that the naming of that example was inspired by Android's [`findViewById`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/escape/CharEscaper.html#escape(char)) + [`requireViewById`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/escape/CharEscaper.html#escape(char)). As I understand it, the Android folks felt that they couldn't change `findViewById` to return a nullable type without causing a lot of pain, and I guess they felt that `requireViewById` was what most people want most of the time, anyway.

This is one of a few classic examples of how existing APIs would likely be designed differently if they had been designed with nullness in mind. Granted, even if Android could arguably have done things better, I'm not sure there's _any_ great solution for cases like that one.

The way to make such APIs actually work well is for the language to have easier ways of dealing with `null`. One of the goals of JSpecify is [to set the stage for that](https://docs.google.com/document/d/1H3TdqjRZQiGEP7ZePLpTnbYxj9s5hJAn9sp6eOiuj_c/preview#heading=h.6ebjuy9io350).

**Comment by GregDThomas** [comment]
FWIW, if it were me, I'd do;

```
@NullMarked
interface MyData {
  Optional<MyPropertyType> getOptionalMyProperty();

  default MyPropertyType requireMyProperty() {
    return getOptionalMyProperty().orElseThrow();
  }
  . . .
}
```

**Comment by cpovirk** [comment]
`Optional` has served us well over the years, but the more that nullness checking catches on, the more uneasy I become about `Optional`: While there are [tools that can verify that you don't call `get()` on an `Optional` that is empty](https://checkerframework.org/manual/#optional-checker), those tools aren't as commonly used as nullness checkers (especially in Kotlin, where I'm not personally aware of any `Optional` checkers). And "`get()`" looks so innocent at the call site, often giving no sign that it's a call to the exception-throwing `Optional.get()` and not, say, `WeakReference.get()` (hence [`orElseThrow`](https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/util/Optional.html#orElseThrow())).

I tend to think of `Optional` as a tool to use in APIs whose callers you can't count on to use nullness checkers. That's a bit of an oversimplification, since methods like `orElse` can still be nice—at least in Java, since Kotlin needs them less and doesn't treat `orElse(null)` as having a nullable type! And I still do use `Optional` in practice some myself, in part because I do work on libraries whose callers don't all use nullness checkers. I just hope that we can gradually shift toward nullable types as the nullness story further improves.

There are, of course, [a variety of opinions on the topic](https://www.reddit.com/r/java/comments/13rv1t2/why_exactly_does_brian_goetz_not_recommend_the/), presumably as a result of the factors I've mentioned and others.

**Comment by stechio** [comment]
I stick to common wisdom, which considers optional properties an anti-pattern adding yet-another level of verbosity and interfering with tools based on venerable standards like JavaBeans; I use `Optional`sparingly, on query-like methods (eg, `findViewById(..)` would be a perfect candidate) where functional expressiveness makes more sense. For domain APIs, I think nullness annotations are currently the most neat solution until a native idiom is included in the language.

BTW, besides the disgraceful `get()`, there is also the factory `Optional.of(..)` (which weirdly throws an NPE, despite the purpose of `Optional` should be *precisely* to deal with `null` gracefully through encapsulation!) and `isEmpty()` (which is intended as semantically complementary to `isPresent()`, despite its obvious name should have been `isAbsent()` instead — same as coeval `Map.computeIfAbsent(..)` vs `Map.computeIfPresent(..)`).

**Comment by kevinb9n** [comment]
I think the crux here is that the implementer is *not right* to return `null`. They should get a warning. I agree that the method result should be non-null. `Object.toString()` is like this btw.

What this highlights, though, is that invoking a method with a non-null result is *not a hard guarantee* that you can't get null back. It just isn't -- [null pollution](https://github.com/jspecify/jspecify/wiki/null-pollution) happens. A caller has the option of coding defensively for this possibility when it deems it important enough.
