### ISSUE TITLE
Make sure the build-docs workflow runs on pull requests and pushes to the specification-1.0 branch

### ISSUE THREAD

**Issue by netdpb** [jspecify/jspecify#547]
I thought #546 would do it, but that appears not to be enough.

**Comment by cpovirk** [comment]
I still want to avoid starting a 10-minute conversation about whether a branch for the docs is worth the effort, but just in case you eventually conclude that those 10 minutes might save you an hour of tearing out your hair... :)

- There's a solid chance that no one outside the current group gives the spec more than a cursory review during the month we're updating it. So even if it were to go out of sync in a confusing way, it might not affect anyone.
   - If anyone pays attention, it might be to the commit history in the main branch, in which case raw activity there might be a good thing :)
- I expect the individual PRs we make to be independent, like how updating the package name is independent of substitution or applicable locations. So I don't expect confusion to result.
   - If anything, I think that every case in which we update the main-branch spec is a chance to avoid confusion that has resulted from differences between the spec and the Javadoc / User Guide.
- If readers really want the 0.2 version of the spec, they can get it at https://github.com/jspecify/jspecify/blob/9abe30d9ded9a088cca97bf2ce79aad603420484/docs/docs/spec.md (with, admittedly, minor rendering hiccups). We could even link directly there if we want.
- If the problem ends up being specifically with branches but we still want to leave the old spec in place, we could consider making a copy of the file in the main branch and iterating on that. (We presumably won't be editing the old spec until it's time to merge, so that shouldn't lead to any merge conflicts.)
- If we do want a branch, my guess is that we could live without doc generation until it's time to merge. We'd just have to review carefully then, especially for links.

**Comment by cpovirk** [comment]
(But I do hope it's just an easy fix :))

**Comment by netdpb** [comment]
I think the workflow change just has to be on the development branch.
