### ISSUE TITLE
Release 1.0.0 on Maven Central but not on GitHub releases

### ISSUE THREAD

**Issue by wmdietl** [jspecify/jspecify#570]
https://central.sonatype.com/artifact/org.jspecify/jspecify

shows that the 1.0.0 release was made. Yay!
However,

https://github.com/jspecify/jspecify/releases

doesn't list the release.

**Comment by agentgt** [comment]
@cpovirk when you write the release notes on github I would load that bad boy up with links to everything as github releases are pretty good broadcast (and thus improves network effect).

I guess the above is pretty obvious but just a reminder.

**Comment by cpovirk** [comment]
That's a good point. We've been treating them mostly as normal incremental release notes, but we might want to rethink that.

Here's what we've been planning on:

---

# Release notes

## 1.0.0

The 1.0.0 release of JSpecify’s annotations contains four nullness-related annotations:

* [`@Nullable`](https://jspecify.dev/docs/api/org/jspecify/annotations/Nullable.html)  
* [`@NonNull`](https://jspecify.dev/docs/api/org/jspecify/annotations/NonNull.html)  
* [`@NullMarked`](https://jspecify.dev/docs/api/org/jspecify/annotations/NullMarked.html)  
* [`@NullUnmarked`](https://jspecify.dev/docs/api/org/jspecify/annotations/NullUnmarked.html)

### Artifacts

* [Javadoc](https://jspecify.dev/docs/api/)  
* Maven Central: [org.jspecify:jspecify](https://repo.maven.apache.org/maven2/org/jspecify/jspecify/1.0.0/)

### Changes since version 0.3.0

No code changes, only Javadoc changes and OSGI metadata.

---

Thoughts from either of you, from @netdpb, or from others?

**Comment by wmdietl** [comment]
Maybe include a reference to the compatibility commitment and that the artifact is safe to depend on?

**Comment by agentgt** [comment]
I think the key is a blurb above the Release Notes on what JSpecify is. 

You don't need this for each release but how people often discover libraries is on the github dashboard and I think it is populated by people you follow and the projects you star. I am probably wrong on this but I don't think it can hurt..

The other is people starring the project and then forgetting about it.

Maybe this blurb from the home page:

> **JSpecify 1.0.0 is the first artifact of tool-independent annotations for powering static analysis checks in your Java code.**
> # Release Notes

But it isn't a big deal and I think your version is good.

**Comment by cpovirk** [comment]
https://github.com/jspecify/jspecify/releases/tag/v1.0.0
