### ISSUE TITLE
TYPE_USE annotations in TYPE_PARAMETER locations

### ISSUE THREAD

**Issue by kevin1e100** [jspecify/jspecify#60]
We have so far stayed away from allowing annotations in `TYPE_PARAMETER` positions at all.  In part that's because it's not strictly necessary when only tracking upper bounds, and for `@Nullable`, it seems a lot clearer what `<T extends @Nullable Object>` means than `<@Nullable T>`.

There's also the issue of what happens when both type parameter and bound are annotated.  We don't need to answer that question when disallowing annotations directly on type parameters.  For consistency, and to again sidestep this problem, we've also opted to rule out annotations on a wildcard (`?`) itself (even though they're considered `TYPE_USE`s).

By contrast checkerframework assigns a particular "lower bound" semantics to annotating type parameters, which allows defining type parameters that cannot instantiated with `@NotNull` simply with `<@Nullable T>`.  I'm not sure how `<@NotNull T>` is interpreted by checkerframework.  Either way, except with `? super` wildcards, lower bounds don't need to be explicitly tracked when type parameters can't be annotated.

On a more technical note, javac makes it a lot harder to keep track of `TYPE_PARAMETER` annotations than annotations on type parameter bounds (because the latter are (sometimes) propagated into javac's `Type` objects), so excluding `TYPE_PARAMETER` technically simplify things a bit.

Note that support for `TYPE_PARAMETER` can seemingly be added later.  For now disallowing them avoids inconsistencies with how checkerframework (and possibly other tools) would interpret annotations on type parameters.

**Comment by kevinb9n** [comment]
If we prohibit our annotations before a type parameter or wildcard, then are later convinced it's worth supporting, I think our adding it wouldn't directly break any existing code.

I think that's the plan right now. I'm going to close this for now -- and I think if someone wants to reopen it, it might actually be #85 they want to reopen instead?

**Comment by mernst** [comment]
Prohibiting annotations before type parameters or wildcards will be very burdensome to users, who will have to write a different `@Nullable` or `@NonNull` annotations at different locations in their program -- some of which will have to be fully-qualified since two annotations of the same name cannot be imported.

I don't see the benefit of prohibiting annotations on these locations, especially given the user burden.

**Comment by kevinb9n** [comment]
Thanks for reopening. Let's separate two questions:

1. Should this project define semantics for `@Nullable` used in these positions. This is probably captured as #85 more or less.
2. If we don't, what happens when users put them there anyway?

This issue seems like a fine place to discuss question 2.

My last comment was confused. I'm sorry about that. Some things are coming back to me more slowly than others.

Suppose we simply state some phrasing of, "This annotation has no defined meaning if it is placed before a type parameter or wildcard". Then I think tools that *want* to ascribe such meaning at least have a couple options open (possibly not *great* ones):

1. They could provide their own `@Nullable`, marked with `@Implies(org.jspecify.nullness.Nullable)`, and specifying additional semantics. They are only strengthening our contract, not contradicting it (as they might be if we were "prohibiting", again, sorry about that).
2. They could provide a class/package/module annotation saying some form of, "within the annotated scope, types annotated with `org.jspecify.nullness.Nullable` have the following additional properties unless marked otherwise..." I think this is legitimate as well.

**Comment by mernst** [comment]
For the first option, I think you mean that users would use a different annotation throughout their source code, and never use org.jspecify annotations.

Then, neither option forces users to have two different `@Nullable` annotations in their source code.  That is, both options address my concern.

For the first option, does that require JSpecify to define an `@Implies` annotation?

For the second option, I don't think an extra annotation is even necessary.  A tool could choose to behave that way always.  But, a tool could define such an annotation if it saw value in doing so.

**Comment by kevinb9n** [comment]
Oh my, I think maybe we understand each other perfectly here! What is this feeling? :-)

Option 1: yes, I became personally convinced that we are not viable without it. I'll check back on that issue to see if there's been movement.

I did leave out your Option 3, only because I would expect us to discourage it to _some_ degree (to _what_ degree being a more fine-grained debate than we'd benefit from having _today_). But there may be a smooth continuum between Options 2 and 3 anyway: suppose a tool has a config option to treat code *as if* it has this annotation on every class. And maybe that option becomes the default. Etc.

**Comment by kevinb9n** [comment]
I think the status remains as:

* Use cases should be argued as use cases on #85 or other appropriate issue
* We don't need to _prohibit_ our annotations in these kinds of locations, only declare that they have no usable meaning on their own.

**Comment by netdpb** [comment]
Thinking about the original request for a way to specify a collection of nullable subtype of `Foo`. Would a generic method like this work, without needing to apply type-use annotations to the type parameter itself?

```java
<T extends Foo> void accept(Collection<@Nullable T> collection);
```

**Comment by cpovirk** [comment]
Probably. I think we'd want to tie this back to a specific use case to see if that satisfies its needs. As far as I know, the use cases that we've seen have been satisfied by various formulations, whether `<T extends @Nullable Foo>` or `Collection<? super @Nullable T>` or something else. If we do have other cases, we should probably discuss them in issues like #85 (referenced by kevinb9n above) or #145.

**Comment by netdpb** [comment]
I see that in https://github.com/jspecify/jspecify/issues/85#issuecomment-562255814 you already proposed this idea. Thanks.

**Comment by netdpb** [comment]
**Current decision**: Java generally doesn't support lower bounds on type parameters or specifying both lower and upper bounds on wildcards, and there isn't a strong enough case to support them. There are other ways to support the use cases for which this is suggested.

**Argument for changing**: We need a way for methods to accept parameters like collections of `Foo` into which they can add `null`. Allowing `Collection<@Nullable ? extends Foo>` would support that use case, which is otherwise unsupported.

**Timing**: This must be decided before version 1.0 of the jar.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by wmdietl** [comment]
Does "unrecognized" here mean the same as "meaningless" [there](https://github.com/jspecify/jspecify/issues/7#issuecomment-2099139237)?
Possibly allowing the usage on `TYPE_PARAMETER`s in the future would be preferable to me.

**Comment by kevinb9n** [comment]
As I just proposed [here](https://github.com/jspecify/jspecify/issues/7#issuecomment-2099742506), I believe we should clarify that only type usages can be nullness-applicable, and a type parameter declaration is not a type usage.

I think (?) we settled on "unrecognized" instead of "meaningless". The idea is that a nullness annotation anywhere that isn't "nullness-applicable" is unrecognized (there are other cases of being unrecognized, too).

**Comment by netdpb** [comment]
@kevinb9n Are you still 👀 on this issue? The working decision is that they are inapplicable/unrecognized, whatever the wording.

**Comment by kevinb9n** [comment]
Sorry - the issue I linked to got resolved, so removing eyes.

**Comment by netdpb** [comment]
**Decision**: JSpecify type use annotations (`@Nullable` and `@NonNull`) are inapplicable to type parameters (for example ~`class Foo<@Nullable T>`~).
