### ISSUE TITLE
A type parameter that wants nothing to do with nullness

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#78]
This may be an issue only with the current "explicit annotation on type variable usage wins" model, not with the "most-nullable" proposal.

Consider a class like this:

```
class WeakRef<T> {
  WeakRef(@NotNull T referent) { ... }
  @Nullable T get() { ... }
}
```

Note that *every* type usage of T has an explicit nullness override.

In this case, we really have no interest in seeing type usages of `WeakRef<@Nullable Foo>` OR `WeakRef<@NotNull Foo>` at all, because the distinction between these is meaningless.

Would we prefer a way to mark T itself:

```
class WeakRef<@HasNothingToDoWithNullness T> 
```

Yeah, it would be hard to name this.

Then it would be an error to leave any type usage of `T` within the `WeakRef` class unannotated. (Or let the defaults apply, but maybe let's not debate that yet.)

**Comment by kevinb9n** [comment]
I feel very good about 

```
@NullMarked
class WeakRef<T> {
  WeakRef(T referent) { ... }
  @Nullable T get() { ... }
}
```

I'm not sure we need to keep pulling on any of the threads above. Reopen if desired.

**Comment by cpovirk** [comment]
I still feel good about using `<T>` for this in general, but I wanted to note here that we may end up using `<T extends @Nullable Object>` in one specific, unusual case, when theoretically we'd use a special-purpose "type parameter that wants nothing to do with nullness" if such a thing existed.

The case is [`TypeToken`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/reflect/TypeToken.html). There is no difference between a `TypeToken<String>` and a `TypeToken<@Nullable String>`. (OK, it's technically possible to differentiate between the two by using reflection, since `TypeToken` users create an anonymous subclass, which defeats erasure.) The `TypeToken` APIs don't expose the annotation, and they certainly don't propagate it through substitution, use it in subtyping checks, etc. In short, `TypeToken` wants nothing to do with nullness.

However, in order to allow users to create a `TypeToken<T>` for a type parameter that is declared `<T extends @Nullable Object>`, we'd need to declare `TypeToken` itself with `<T extends @Nullable Object>`. Or, alternatively, we'd need a `@DefinitelyNonNull` annotation (#4), which is, I grant, looking more likely now that [Kotlin is adding such a feature](https://github.com/Kotlin/KEEP/issues/268).

I left a couple comments about this a while back in `TypeToken` and `TypeParameter`.

- https://github.com/google/guava/blob/2331170e5b52b0db1d6aa73a5e7f66b8466b695a/guava/src/com/google/common/reflect/TypeToken.java#L225-L231
- https://github.com/google/guava/blob/2331170e5b52b0db1d6aa73a5e7f66b8466b695a/guava/src/com/google/common/reflect/TypeParameter.java#L38-L43

There's also a little discussion on Google-internal bug 198793040. The main thing to note is that the use case for this is Kotlin, so we can't say "just suppress."

(Now, there was also Google-internal CL 398047525, in which people were explicitly using `TypeToken<@Nullable Foo>`, which we'd probably rather they didn't.... But if we cared enough, we could write our own additional checks to ban that pattern.)

**Comment by kevin1e100** [comment]
I guess I'm wondering if `TypeToken` is completely nullness-oblivious: seemingly, in a nullness-annotated world, we _could_ want it to understand and (ideally, correctly) deal with things like `TypeToken<@Nullable Foo>`. We'd nearly certainly want it to understand `TypeToken<List<@Nullable Foo>>` (which is probably "automatic"), so why not `TypeToken<@Nullable Foo>`? Differentiating `TypeToken<Foo>` from `TypeToken<@Nullable Foo>` seems at least "in the wheelhouse" of `TypeToken`'s purpose. Not sure this is making a lot of sense for some of the methods defined on `TypeToken`, but as a token to identify a type, it seems actually important to be able to express and differentiate `TypeToken<@Nullable Foo>`, wdyt?

**Comment by cpovirk** [comment]
It definitely would be nice for `TypeToken` to support nullness. I mostly doubt that we would get around to it anytime soon: The time that we have to work on tooling is likely to keep going toward compile-time checking and toward tools to add annotations to source code.

**Comment by netdpb** [comment]
The current, working decision, as of 2021-06-19, is that when a generic type is equivalent whether its type parameter's argument is nullable or not (for example, `Class`), then that is representable by a plain (bounded by non-null) type parameter. All usages of that type variable should be null-projected or non-null-projected.

The argument for changing this decision is that it would be more explicit to call out those type parameters, so that tools could either enforce that all type usages are projected, or treat plain usages as if they were projected.

However, no strong case was made that such a change is worth the added complexity.

This must be decided before version 1.0 of the jar.

**I propose the current decision be finalized for 1.0.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by wmdietl** [comment]
To me it seems like it is up to API designers whether they want to use `<T>` (and not require projections) or use `<T extends @Nullable Object>` (making usage easier, but possibly requiring projections to ignore nullness).
If this issue is about whether we add a new mechanism to express that a type parameter "wants nothing to do with nullness" and the working decision for that is "no", then 👍 .
If the issue is that we prescribe how people have to use the annotations: why get mixed up in those discussions? We can separately provide "best practices" but don't need to prescribe that in the specification.

**Comment by kevinb9n** [comment]
Yes, the actual design decision is only that we won't have any special solution for this. I don't think I read David's summary as implying more than that.

Separately, I think we want to recommend a particular approach, but that doesn't strictly need to be decided here.

**Comment by netdpb** [comment]
**Decision**: JSpecify provides no special way to declare that none of a type parameter's usages should have parametric nullness. Users can declare the type parameter with a non-null bound and add nullable projection to some usages, or they can declare it with a nullable bound and add nullable or non-null projection to all usages.
