### ISSUE TITLE
Scope of package-level default annotations

### ISSUE THREAD

**Issue by dzharkov** [jspecify/jspecify#8]
The question was initially raised by @amaembo:
> If it’s applied to the package, I suggest that it should not be applied to any subpackages, so it’s required to write DefaultNotNull once per every package.

cpovirk edit much later:

(See, for example, [this question](https://groups.google.com/g/jspecify-discuss/c/wpSl8ViESHQ/m/SNyG4kYlAAAJ), these feature requests ([IntelliJ](https://youtrack.jetbrains.com/issue/IDEA-197110), [JDK](https://bugs.openjdk.org/browse/JDK-8204140), [jOOQ](https://github.com/jOOQ/jOOQ/issues/9115)), these StackOverflow questions ([1](https://stackoverflow.com/q/32847542/28465), [2](https://stackoverflow.com/q/25391559/28465)), and [this behavior in the Checker Framework](https://checkerframework.org/manual/#default-qualifier) (and I want to say maybe some behavior in Spring?).)

**Comment by NicklasWallgren** [comment]
I think there should be an option to make subpackages inherit the `NullMarked` annotation. What other alternatives are there for projects not utilizing JPMS?

**Comment by cpovirk** [comment]
The current approach has the advantage that there's no chance of confusion if a superpackage from another module is `@NullUnmarked` but the current module is `@NullMarked`: Because we never look at superpackages, it's clear that the current module's setting "wins."

This also matches Java's [definition of "enclosing elements,"](https://docs.oracle.com/en/java/javase/21/docs/api/java.compiler/javax/lang/model/element/Element.html#getEnclosingElement()) though I admit that I'm not sure how significant that usually is above the package level.

This current approach can be inconvenient for users (as we've seen inside Google, for example), and we hope that some tools will offer a way to enforce that packages or classes are annotated with `@NullMarked` where desired.

**Comment by agentgt** [comment]
I will just add to what @cpovirk in that there is no such thing as a "subpackage" or "super package" in Java. The facilities to apparently navigate package trees at runtime in things like Spring are not really reliable in a compiler setting.

It is sad that JPMS solves the problem but the uptake of it has been so poor. I'm perhaps overly optimistic but I'm hoping for a future for where that isn't the case.

@cpovirk one possible solution is to put something in META-INF similar to Automatic-Module-Name but I'm not sure how reliable retrieving that information is across tools.

**Comment by cpovirk** [comment]
Interesting, I don't think we'd considered `META-INF`. One concern would be that it's theoretically possible to consume directories of class files instead of jars, and (I assume??) tools won't look for `META-INF` unless there's a jar. Probably lots of people do always consume jars, though, so it's less of a risk. My concern then would be tools that, e.g., build fat jars: It's unlikely that everything would "just work" when merging together the `META-INF` data from multiple jars. Or who knows, maybe it would if we could invent a scheme like `META-INF/null-marked-packages/com.foo`? I've never looked into that.

I guess there's also the principle that we want for the nullness specifications to be clear from the Java source files, without need to look at separate configuration files. (_Ideally_, we want it to be clear from looking at _only_ the Java source file that you care about. But obviously we've felt it necessary to compromise there a little by supporting package-level and module-level defaulting at all. Even _that_ leads to issues sometimes, since people will put `@NullMarked` on a a package but not want it to apply to the _tests_ that they put in the same package... :) There are really no great options as far as we've been able to tell.)

**Comment by agentgt** [comment]
I'm not really a fan the `META-INF` solution either. I have had some users particularly Spring users complain about the fact my library requires annotations on each package or modules.

My preferred solution as @dsyer can tell you is JPMS (its an ongoing joke we have that when this comes up I just say use modules 😄 ).

https://github.com/jstachio/jstachio/issues/69

**Comment by agentgt** [comment]
Even more why I don't think `META-INF` is a problem is  that most IDEs can auto create `package-info.java` with a template.

In fact Eclipse (I'm like 1 of the 10 only people left that use it) will if null analysis is turned on warn you if miss not putting a NullMarked annotation of your choosing on a `package-info` as an option. Search for *Missing `@NonNullByDefault` annotation on package* in the preference window. 

@NicklasWallgren are you using Eclipse or IntelliJ out of curiosity?

**Comment by cpovirk** [comment]
Thanks for the link, which I admit I only skimmed after seeing you mention _runtime_ concerns. So now, yikes, I'm afraid of runtime questions when looking for parent packages: If my classloader loads `a.b.c` and `a` but another classloader loads `a.b`, then do we inherit from `a` or from `a.b`? This seems like further evidence that we'd be swimming upstream if we tried to make subpackages "a thing."

**Comment by agentgt** [comment]
I think once JSpecify is released the tooling in IDEs will get better and enforce `package-info.java` on null analyzed project which IMO is the best solution other than modules. 

That is something like IntelliJ can just auto turn on create `package-info` if null analyzed project.

**Comment by kevinb9n** [comment]
This thread has covered a lot of ground, but my impression is that the decision it represents is specifically that a package-level annotation will affect only *that* package (in that module) and no "subpackages" (which are not even a real concept in Java). If there was any other significant/debatable aspect please file separately.

**Comment by netdpb** [comment]
**Decision**: JSpecify annotations on a Java package affect only symbols declared in that package, and not in "subpackages" (packages with a prefix that matches the annotated package).
