### ISSUE TITLE
Consider permitting `extends Object` to be treated differently from `extends NotObject`

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#82]
It *might* be best in the long run if we are willing to define different treatment for `<T extends SomeType>`/`<? extends SomeType>` based on whether `SomeType` is `java.lang.Object` or not, as Eclipse does.

However, in order to manage a ballooning state space, and because I claim this is a relatively "exotic" solution that adds perceived complexity and puzzlers for users, I want to *for now* treat this as out of bounds.

This will allow us to make a series of provisional decisions; then, when those are settled, we can take a fresh look at "how would this change and improve if we were willing to drop that assumption?"

The risk is that the assumption can end up becoming the _de facto_ decision because we'll be accustomed to it. We shouldn't let that happen; we should preserve our "question everything - but in the right place and time" mentality.

**Comment by kevinb9n** [comment]
Some notes I wrote up back on April 20 of last year:
https://docs.google.com/document/d/1ixjAUGSAohbEUHsC730KxMy2vrwVkpXOy1iub2XCR20/edit

We have remained comfortable with the working decision of "nay" (and I think we currently lack an advocate for the "yea" side), so I'll close for now.

**Comment by netdpb** [comment]
**Current decision**: Treating `<T extends Object>` differently from `<T extends NotObject>` is a special case that makes the specification more complex. It's really required only to support #12, which we have decided not to support, partially because of this complexity. (See https://github.com/jspecify/jspecify/issues/12#issuecomment-2045917065 for more information.)

**Argument for changing**: To suport #12.

**Timing**: This must be decided before version 1.0 of the jar.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by netdpb** [comment]
**Decision**: JSpecify treats `<T extends Object>` just like `<T extends NotObject>`; it is not a special case.
