### ISSUE TITLE
Nullness bound for unbounded wildcard 

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#83]
\[update: [direct link to doc about this issue](https://docs.google.com/document/d/1HGupJjYkFs6OPjH4tQFmivNr1sPcHicaXDdMVvGfu4A/edit)\]

Consider these classes:

```java
// what default is in effect does not matter

class Foo<T extends @Nullable Object> { … }
class Bar<T extends @Nullable NotObject> { … }
```

And these precise types written within a default-not-null context:

```java
// we are in a default-not-null context

Foo<?> foo = ...
Bar<?> bar = ...
```

The question is: what nullness do the upper bounds of these wildcards have?

(Assuming the answer to #82 is "no", we must have the same answer in both cases.)

**Comment by netdpb** [comment]
**Current decision**: In null-marked code, the wildcard in `Foo<?>` can capture nullable types (assuming the corresponding type parameter isn't bounded by a non-null type). If you want it not to capture nullable types you'd have to write `Foo<? extends Object>`. (Unlike type parameter declarations, bytecode does distinguish between `Foo<?>` and `Foo<? extends Object>`).

**Argument for changing**: The current decision is inconsisitent with the fact that nullability must be explicit in all other type usages in null-marked code.

However, no strong case was made for changing the decision.

**Timing**: This must be decided before version 1.0 of the jar because it's mentioned in the Javadoc for `@NullMarked`.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by netdpb** [comment]
**Decision**: In null-marked code, the wildcard in `Foo<?>` can capture nullable types (assuming the corresponding type parameter isn't bounded by a non-null type). If you want it not to capture nullable types you'd have to write `Foo<? extends Object>`.
