### ISSUE TITLE
Should we support a definitely-nullable type parameter (or wildcard)?

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#85]
I'm splitting this from #60 as a single focused *requirements* question.

Should we support declaring a type parameter which can *only* be given nullable types as type arguments?

What are the compelling use cases?  We think Guava's `ArrayTable` *might* be one and should examine it in a future comment here.

Its `Equivalence` is *almost* an example, because its public APIs guarantee to accept null and to return null in cases. But, it has a protected API as well, which makes clear that we actually need `<T extends @NotNull Object>` and it is only the appearances of `T` in the public methods that should be projected to nullable. (Not the other way around, since it's senseless to admit different parameterizations of that type; all Equivalences are mandated to handle null in exactly the same way.)

The case has been raised in #60 of a method which reads values from a list but nulls them out as it goes.

**Comment by cpovirk** [comment]
This is already closed, but I wanted to add another concern for us to consider if we reopen it someday.

[Above](https://github.com/jspecify/jspecify/issues/85#issuecomment-562731976), I talked about the Checker Framework's handling of `ThreadLocal`. I noted that it enables a new pattern -- namely, instantiating the type with an out-of-bounds type argument when it's known to be safe.

It just occurred to me that this pattern is spiritually incompatible with a rule we've proposed for JSpecify -- namely, the rule that out-of-bounds type arguments are "clamped" into the bounds. (That rule is split between [here](https://docs.google.com/document/d/15NND5nBxMkZ-Us6wz3Pfbt4ODIaWaJ6JDs4w6h9kUaY/edit#heading=h.xo15qzmw82i3) and [here](https://docs.google.com/document/d/15NND5nBxMkZ-Us6wz3Pfbt4ODIaWaJ6JDs4w6h9kUaY/edit#heading=h.u8phmghg96wr).) The idea is that, if you have a `BlockingQueue<E>` type that does not permit nullable type arguments, then methods like `blockingQueue.add` should not permit null values -- even if your queue is declared as a `BlockingQueue<@NullnessUnspecified Foo>` (as it would implicitly be in non-null-aware code).

(This is a problem for JSpecify in particular precisely because of "unspecified nullness": Unspecified nullness causes these out-of-bounds type arguments to occur far more easily.)

If we were to apply a similar rule to a hypothetical definitely nullable type parameter, that would mean that a `ThreadLocal<@NonNull String>` would still behave like a `ThreadLocal<@Nullable String>`.
