### ISSUE TITLE
Non-null projection of a type variable usage

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#86]
We've agreed to support the "nullable projection of a type variable"; that is, for a type variable `T`, the ability to denote the type representing "T union null"? This would presumably be written `@Nullable T`. (Of course, we get that for free with the way we've conceptualized what "Nullable" means.)

Should we support the "non-null projection of a type variable"; denoting the type "T minus null"? On this we seem to have less agreement, so let's look at use cases.

**Comment by cpovirk** [comment]
One use case for projecting to non-null that is still hypothetical but looks more realistic (if far away): a `default` method on `Map`:

```java
Optional<@NonNull V> getOptional(@Nullable Object key);
```

See [JDK-8204662](https://bugs.openjdk.java.net/browse/JDK-8204662) and [JDK-8232647](https://bugs.openjdk.java.net/browse/JDK-8232647). The former notes that the JDK owners may consider this once value types exist.

The alternative to supporting such a projection is:
- declare that anyone who needs to implement this method (which should be rare) should just suppress
- ideally, have our spec prescribe some behavior for `Optional<V>` when `V` can take on nullable types. (Currently, [our design proposal's section on Members of Parameterized Types](https://docs.google.com/document/d/15NND5nBxMkZ-Us6wz3Pfbt4ODIaWaJ6JDs4w6h9kUaY/edit#heading=h.xo15qzmw82i3) proposes to make `optional.get()` return a non-null value in this case. Specifically, see the first bullet.)

(Or maybe someday we'll have a way to say that the method can be called only on a `Map` whose value type is non-null, similar to Checker Framework issue 3203.)

(My personal position is still to avoid supporting projection to non-null, but this is at least a small argument to the contrary.)

**Comment by kevin1e100** [comment]
Hmm we might be approaching critical mass here.  Another somewhat similar example that would benefit from projections was a [`filterNonNull`](https://github.com/google/codeanalysis-annotations/issues/4#issuecomment-576958155) method, and given how `getOptional` is discussed in JDK-8204662, a method like `firstOptional` could conceivably be defined in a similar way.

**Comment by cpovirk** [comment]
I do think these are all important possibilities to have an eye on. At the same time, I think it's worth remembering that they are all currently hypothetical. (Additionally, Valhalla in particular is still far off, and the subsequent library improvements could be further still, and both could happen in non-LTS releases and thus take even longer to get to users.)

It's still nice to support what we can. I claim only that the use cases are small enough that they're not decisive on their own. We get to weigh them against the costs (which I grant are not enormous but which I think are non-obvious), similar to how we weigh the (larger) costs and benefits of including [`@PolyNull`](https://github.com/jspecify/jspecify/issues/79) for `Optional.orElse` and `Class.cast`.

(All that said, it does seem fairly likely to me that, if we include `@NonNull`, it's going to project to non-null. I say that based less on use cases and more on the obviousness theorem :) Unless I can pull a different name for `@NonNull` out of the air, I am currently more focused on arguing against it entirely, as you may have noticed :) But for purposes of the current discussion about requirements, I'm making the claim that our current examples are more suggestive than concrete.)

**Comment by kevin1e100** [comment]
To me, the fact that these are examples from APIs that Java developers use
~ every day does suggest significant importance.  They may be hypothetical,
but on the other hand, if we don't have ideas on how to design them to
avoid projections, that still suggests to me that we may be missing
functionality that could be important more generally.

`@PolyNull` to me is a bit different only because it seems that it can be
added "later" with relative ease, and the question there is more how best
to do it (`@PolyNull` vs `@Contract`).  There are also relatively clear
ways of avoiding the need for `@PolyNull` in new APIs (e.g., `orNullI()` :)
).
Just to repeat something I mentioned before, *if* we define
`Optional<Anything>` to implicitly project the type argument to `@NonNull`
because that's `Optional`'s type parameter bound, then we still don't need
explicit projections to handle `Optional`-related examples.

**Comment by kevinb9n** [comment]
I believe @cpovirk has been collecting up use cases for this.

(If we decide to have this then it will need an annotation; and if that annotation wants to be `@NonNull` then we will have to face the question of whether that annotation should also be useful in other ways, like in null-unmarked code. But one step at at time.)

**Comment by kevinb9n** [comment]
It would be pretty useful if we could maintain a running list of known APIs that would be at least half-inclined to adopt this feature, showing what the signature looks like with and without, and briefly discussing any implications.

In case #230 goes yes and this one goes no, I assume we will specify a type variable usage as an "unrecognized location" for `@NonNull`. And this would make it reasonably expected that a tool would report a problem when seeing it placed there; and when seeing it there on a _dependency_ would ignore the annotation and possibly also give a warning at the use-site(?).

**Comment by cpovirk** [comment]
3 known APIs from Guava, all around "A type parameter that wants nothing to do with nullness" (#78), either in the form of `Class` or the form of `Equivalence`:

### [`Iterables.toArray`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/collect/Iterables.html#toArray(java.lang.Iterable,java.lang.Class))

(and its `FluentIterable` equivalent, though note that `FluentIterable` has [many more problems around nullness](https://github.com/jspecify/jspecify/issues/157#issuecomment-1030292196))

Today:
```java
<T> @Nullable T[] toArray​(Iterable<? extends @Nullable T> iterable, Class<T> type)
```

With non-null projection:
```java
<T extends @Nullable Object> T[] toArray​(Iterable<? extends T> iterable, Class<@NonNull T> type)
```

Alternatively, with `@PolyNull` (but note that I see this use case like the first ["less compelling"](https://github.com/jspecify/jspecify/issues/79#issuecomment-897692415) case for `@PolyNull`; the only reason that the usual solution doesn't apply here is because of `Class`):

```java
<T> @PolyNull T[] toArray​(Iterable<? extends @PolyNull T> iterable, Class<T> type)
```

This matters to some existing Google users of the Checker Framework, so we have a stub file set up for them so that they don't need to suppress a warning. I forget how many people are affected.

### [`Maps.difference` (3-arg)](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/collect/Maps.html#difference(java.util.Map,java.util.Map,com.google.common.base.Equivalence))

Today:
```java
<K extends @Nullable Object,​ V> MapDifference<K, ​V> difference​(
    Map<? extends K, ​? extends V> left,
    Map<? extends K, ​? extends V> right,
    Equivalence<? super V> valueEquivalence)
```

With non-null projection:
```java
<K extends @Nullable Object,​ V extends @Nullable Object> MapDifference<K, ​V> difference​(
    Map<? extends K, ​? extends V> left,
    Map<? extends K, ​? extends V> right,
    Equivalence<? super @NonNull V> valueEquivalence)
```

(I guess `@PolyNull` might work here, too? I hadn't thought about it before, and I'm not going to think deeply about it now.)

This matters to no Google users of the Checker Framework, and I even verified that it would matter to no Google users _even if everyone used the Checker Framework_.

It does require us to suppress a warning in the 2-arg overload of `Maps.difference` itself (or at least it will when I finish the current batch of changes to our hacky checker :)) -- or else duplicate some code.

### [`ClassToInstanceMap`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/collect/ClassToInstanceMap.html)

Today:
```java
interface ClassToInstanceMap<B> extends Map<Class<? extends B>, B>
```

Or maybe what we should do today (even though it would be inconvenient to users), given that just a couple users inside Google insert null values, is:
```java
interface ClassToInstanceMap<B> extends Map<Class<? extends B>, @Nullable B>
```

With non-null projection:
```java
interface ClassToInstanceMap<B extends @Nullable Object> extends Map<Class<? extends @NonNull B>, B>
```

**Comment by kevinb9n** [comment]
Is `FluentIterable.getFirst()` a case for it too?

Today:

```java
class Optional<T extends Object>

class FluentIterable<E extends @Nullable Object> {
  @SuppressWarnings("nullness") // it's broken, but we seem to have no choice
  Optional<E> first() { ... }
}
```

Alternative?

```java
  Optional<@NonNull E> first() {
    return Optional.of(...); // if it wouldn't satisfy the projected type it will throw anyway
  }
```

**Comment by cpovirk** [comment]
Yes, thanks. (And to be clear, there are multiple similar methods on that class.) I had gotten too discouraged and distracted about `FluentIterable` in https://github.com/jspecify/jspecify/issues/157#issuecomment-1030292196. But no matter how bad the user's experience is from false negatives, we'd rather get the return type right than wrong :)

And as noted in that same comment, tools cold conceivably be made smart enough to identify bad usages of the methods. (Hmm, maybe they could be made to identify the need to project to non-null automatically even without the annotation?)

A nice bonus of being able to declare the return type correctly is that we would no longer have to suppress warnings at the method level, only at the actual unsafe call. (Granted, if we're able to design sophisticated warning suppression and get it adopted widely, then the method-level suppression could perhaps be written in a way less likely to mask other errors.)

**Comment by kevinb9n** [comment]
> (Hmm, maybe they could be made to identify the need to project to non-null automatically even without the annotation?)

This sounds dodgy. If yes on this issue then they should project the normal way and remove the warning suppression. If no on it, the warning and need to suppress are justified. And then even at the call site (still referencing your linked comment, here) I would have wanted to get a warning any time any expression at any granularity has a bogus static type.

**Comment by kevinb9n** [comment]
minor note: I've been referring to `@NonNull T` as being a "difference type", and maybe it technically is, but a _general_ difference type could be much more complex (e.g. `Number - Integer`). The most this will ever do is to "undo" a union-null. Maybe "projection" really isn't so bad.

**Comment by kevinb9n** [comment]
Using the `FluentIterable` example:

1. I was raising (in https://github.com/jspecify/jspecify/issues/158#issuecomment-1032057973) the question of whether a type like `Optional<@Nullable String>` even _exists_ at all. It seems right to say it does _not_ ...
2. Which then raises the question of whether `Optional<E>` even exists when E is nullable-bounded. It would seem also not to exist, and...
3. IF we are hard-no on explicit non-null projection, then I guess (re: cpovirk last comment) it's worth *considering* having `Optional<E>` in the `first()` signature just do it implicitly. It just doesn't seem like a great place to end up.

Separately: what is the very best we can do for these use cases if we don't have non-null projection? It would of course be very strange for people to actually get an `Optional` that "thinks" it might return null.

**Comment by kevinb9n** [comment]
(question for @cpovirk there)

**Comment by cpovirk** [comment]
I've subsequently said a couple things on #158, and I'm not sure if they were the right direction to take the conversation or the right thing to say them on. But there's a fairly direct question here that I think I can belatedly answer.

What we have now is probably the best option:

[`@NullMarked`<br>`public abstract class FluentIterable<E extends @Nullable Object> implements Iterable<E> {`](https://github.com/google/guava/blob/a1dd6ab0db2eaba56decfe4a9ffbaf5991ddde2a/guava/src/com/google/common/collect/FluentIterable.java#L113-L114)
`  ...`
[&nbsp;`     @SuppressWarnings("nullness") // Unsafe, but we can't do much about it now.`<br>&nbsp;`     public final Optional<E> first() {`](https://github.com/google/guava/blob/a1dd6ab0db2eaba56decfe4a9ffbaf5991ddde2a/guava/src/com/google/common/collect/FluentIterable.java#L522-L523)

The result of that is that it's possible to end up with what our rules would consider to be an `Optional<@Nullable String>` or an `Optional<T>` for some `<T extends @Nullable Object>`.

But ["the `ImmutableList.Builder` rule"](https://github.com/jspecify/jspecify/issues/158#issue-756650991) says that calling `get()` on those nevertheless returns `String` and `@NonNull T`, respectively.

So I'd anticipate issues only if someone is trying to implement a method whose return type is `Optional<String>`, since that's still considered to be distinct from `Optional<@Nullable String>`. Could we "fix" that by adding another rule? I haven't really thought about it. It would be great if we knew how often it would matter to users. For that matter, it would be great if we knew how often the rule that we _do_ have would matter to users :)

Until we can convince ourselves that a new rule would be important to users, I'd lean against having one: While the handling of `get()` fits naturally into our rules for substitution (which we need anyway), this rule for "fixing" type arguments may be the first of its kind: It feels like a new "step" in the process: After we figure out what the annotations say, we then go back and reevaluate whether that's reasonable in this context, and then we use the output of _that_ for the rest of our work. I worry about the cost of that, from implementation complexity to runtime, with the worst case being some kind of infinite recursion. (Hopefully it wouldn't come to that. But we've already had challenges avoiding infinite recursion in some cases where the rules aren't fundamentally infinitely recursive but our implementation ends up going down such a path.)

(But assuming that we do #230, we'll very likely do the topic of this issue, too, in which case we don't have to worry much about `FluentIterable.first()` specifically.)

**Comment by kevinb9n** [comment]
Working decision (as discussed in last meeting): yes, we will have `@Nullable` in 0.3 and it will work in the 2-3 ways expected.

**Comment by cpovirk** [comment]
I should admit here that I have since learned of a JDK method that does use non-null projection in the way that people normally think of it (i.e., not just for `Class<@NonNull T>` or `Optional<@NonNull T>`: `Map.merge`, whose `value` parameter (and whose `remappingFunction`'s parameter types) should be [`@NonNull V`](https://github.com/eisop/jdk/blob/d792ac4e84be3f9bb3aade9da27ef896f880d915/src/java.base/share/classes/java/util/Map.java#L1356): https://github.com/jspecify/jdk/pull/14, https://github.com/eisop/jdk/pull/41.

**Comment by kevinb9n** [comment]
Hmm. They've continued to prove rare?

Was there an issue where we were considering whether `Optional</*parametric*/T>` should automatically conform to bounds? It still feels highly problematic to me, but do you feel like it's worth reconsidering?

**Comment by cpovirk** [comment]
Up until the `Map.merge` thing, it was used only for the `checked*` collections (`Class<@NonNull E>`) and the stream single-element methods (`Optional<@NonNull E>`):

```
$ git grep @NonNull src/java.base/share/classes/java | grep -v ElementType.java
src/java.base/share/classes/java/util/Collections.java:                                                      Class<@NonNull E> type) {
src/java.base/share/classes/java/util/Collections.java:    public static <E extends @Nullable Object> Queue<E> checkedQueue(Queue<E> queue, Class<@NonNull E> type) {
src/java.base/share/classes/java/util/Collections.java:    public static <E extends @Nullable Object> Set<E> checkedSet(Set<E> s, Class<@NonNull E> type) {
src/java.base/share/classes/java/util/Collections.java:                                                    Class<@NonNull E> type) {
src/java.base/share/classes/java/util/Collections.java:                                                    Class<@NonNull E> type) {
src/java.base/share/classes/java/util/Collections.java:    public static <E extends @Nullable Object> List<E> checkedList(List<E> list, Class<@NonNull E> type) {
src/java.base/share/classes/java/util/Collections.java:                                              Class<@NonNull K> keyType,
src/java.base/share/classes/java/util/Collections.java:                                              Class<@NonNull V> valueType) {
src/java.base/share/classes/java/util/Collections.java:                                                        Class<@NonNull K> keyType,
src/java.base/share/classes/java/util/Collections.java:                                                        Class<@NonNull V> valueType) {
src/java.base/share/classes/java/util/Collections.java:                                                        Class<@NonNull K> keyType,
src/java.base/share/classes/java/util/Collections.java:                                                        Class<@NonNull V> valueType) {
src/java.base/share/classes/java/util/stream/Stream.java:    Optional<@NonNull T> reduce(BinaryOperator<T> accumulator);
src/java.base/share/classes/java/util/stream/Stream.java:    Optional<@NonNull T> min(Comparator<? super T> comparator);
src/java.base/share/classes/java/util/stream/Stream.java:    Optional<@NonNull T> max(Comparator<? super T> comparator);
src/java.base/share/classes/java/util/stream/Stream.java:    Optional<@NonNull T> findFirst();
src/java.base/share/classes/java/util/stream/Stream.java:    Optional<@NonNull T> findAny();
```

We may of course still be missing others, but I think we'd be hearing from our Checker Framework users if any of them were of great importance.

**Comment by cpovirk** [comment]
> Was there an issue where we were considering whether `Optional</*parametric*/T>` should automatically conform to bounds? It still feels highly problematic to me, but do you feel like it's worth reconsidering?

If anything, I'm inclined to view the rarity as more reason _not_ to reconsider: Apparently users won't have to reach for `@NonNull T` often, so I'm less inclined to save them the trouble. (And I agree that "saving them the trouble" is likely to complicate things.)

In fairness, I do expect users to hit this more than I'm suggesting here: If you're writing Kotlin, or if you're writing Java using the Checker Framework's "default defaults," then you'll get in trouble if you write a "`class Foo<T>`" that uses a "`Class<T>`." Or actually, you _won't_ get in trouble _with `Class` and `Optional`_ with the Checker Framework as long as you use _its_ stubs. But you could have similar problems with `ImmutableList` and similar. And you can definitely see problems with Kotlin, though probably less, given the lesser usage of `Class` and `Optional` (and perhaps `ImmutableList`) there.

So I do expect users to be confused sometimes. Hopefully we can find ways to manage that, but "automatically conform to bounds" is not at the top of my list.

**Comment by netdpb** [comment]
**Current decision**: Yes, `@NonNull T` is a valid augmented type usage.

**Argument for changing**: It would be simpler not to support nullability projections. However, no strong case was made for changing the decision.

**Timing**: This must be decided before version 1.0 of the jar.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by netdpb** [comment]
**Decission:** `@NonNull T` is a valid non-null projection.
