### ISSUE TITLE
Name(s) of the annotation(s) expressing "in the nullness club" or "not"

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#87]
We used to talk about three defaulting annotations to parallel the three kinds of (non-parametric) nullness: `@DefaultNonNull`, `@DefaultNullable`, and `@DefaultNullnessUnspecified`. 

Currently we want to drop `@DefaultNullable` [#41], and I believe it's a very good idea to at least limit the extra-file context readers need to just one 'bit' of knowledge.

We could keep the other two annotations as the way to control that bit, but here's another possibility: a single annotation like `@NullnessAnnotated` that means "these files are opted in to our nice beautiful new world... where everything in APIs is presumed non-nullable except unbounded wildcards and type variable usages", or something like that.

If something at a smaller scope needs to negate that, that can be `@NullnessAnnotated(false)`.

**Comment by cpovirk** [comment]
A small bonus of using a single annotation for both cases: We can make it invalid _Java_ for a declaration to be annotated `@InTheClub(true) @InTheClub(false)`. In contrast, we can't make it invalid _Java_ for a declaration to be annotated `@InTheClub @NotInTheClub` (though our checkers can refuse to compile sources in which that appears). This helps slightly with #100. (But we may still have similar issues with the _type annotations_: `@Nullable @NonNull`, `@NullnessUnspecified @Nullable`, etc.)

**Comment by kevinb9n** [comment]
That is a good illustration of why the single annotation appeals to me so much in cases like this as well as the future `@MustUseReturnValue(false)`.

There are technical workarounds, but it's more elegant to not need those.

**Comment by kevinb9n** [comment]
For better or worse, I generalized this debate and stuck it into #109.

This issue should only be about agreeing that nullness-defaulting really is just binary (two choices), and then we should be bound by the decision made in #109 from there.

(It might have been better to repurpose this issue for that, maybe, sorry.)

**Comment by cpovirk** [comment]
It looks like we at least tentatively agreed on the binary-ness of nullness-defaulting in https://github.com/jspecify/jspecify/issues/41. So maybe this current issue can be solely about naming, and we can reopen #41 if needed?

**Comment by cpovirk** [comment]
We're going to have an entry in the glossary for "code that is in the scope of such an annotation," so we might hope that that term can be close to the name of the annotation itself.

_Maybe_ this is a slight vote against "nullness-annotated," since it requires that we distinguish between "a type with a nullness annotation on it" and "a type in a nullness-annotated context." (And I think that all 4 combinations of those 2 binary states are possible?)

But we have explicitly postponed this decision to future quarters, so we don't need to figure this out now.

**Comment by cpovirk** [comment]
But naturally, in reading this, I got to thinking... :)

I like including [kevin1e100' s concept of "explicit"](https://github.com/jspecify/jspecify/issues/87#issuecomment-574943889) in the name -- or possibly alternative words related to that, like null-"aware?"

I said [up-thread](https://github.com/jspecify/jspecify/issues/87#issuecomment-577891402) that, to me, "null annotated" doesn't completely suggest "_fully_ null annotated." Also, sometimes you don't need to annotate anything at all (because all types are non-null), in which case you're really saying "I intentionally _did not annotate_ any types in this file." (Also, in rare cases, you need to do _something_, but it's _not_ to _annotate_ but rather to switch from `?` to `? extends Object`.)

**Comment by kevinb9n** [comment]
For use in prose I kinda really like "null-aware context". It really should be "nullness-aware context", but the cheat sees okay and makes the phrase much handier.

The notion is: sure, the same nulls are flying around at runtime  either way, but this way the developer is aware of them, the tools are aware of them, the code is aware of them. (Well, kind of. If you went and annotated everything @Nullable indiscriminately then you'd not be very aware.)  I wonder if "null-aware" might sound odd to users of "NullAway".

**Comment by lazaroclapp** [comment]
I am tentatively not a fan of using `@NullAware` for this, as the name is a bit close to `NullAway`, and I can foresee developers making mistakes with having to e.g. "Annotate your packages as `@NullAware` in order for them to be picked up by NullAway". To me, `@DefaultNonNull` was also generally clearer.

cc: @msridhar

**Comment by cpovirk** [comment]
I think @kevinb9n had raised the possibility of that confusion to me, and it's been perpetually on my to-do list to ask you about it. Thanks for preemptively raising it!

Would you feel better about `@NullnessAware`, at least in that respect? Of course, it's also longer :\ Plus, we definitely will want to explore the question of whether "nullness-aware" or "defaulting to non-null" aligns with the mental model that users have -- and/or with the mental model that we _want_ them to have.

**Comment by kevinb9n** [comment]
I have so far been really liking the "null-aware" terminology at least in prose. Though, I can't square the idea that a single bit of nullness is either *specified* or not with the idea that a broader swath of code is either aware or not. What accounts for the difference between the two unrelated terms? I'm not sure.

**Comment by cpovirk** [comment]
Hmm, good point. It's... aware that it's doesn't know? That maybe makes some sense, but it's hardly a natural way to put it.

That is perhaps a reason to prefer terminology like `@NullExplicit`. Did you (or anyone else, aside from @kevin1e100, who presumably still likes it) have an opinion on that?

**Comment by cpovirk** [comment]
`@DefaultNonNull` may at least hint that the default is otherwise `@Nullable`. But in fact it's closer to `@NullnessUnspecified`. (That confusion is likely to arise no matter what, but maybe `@DefaultNonNull` encourages it?)

**Comment by kevin1e100** [comment]
I'm guessing this is alluding to the following derivation someone might make: "since the apparent opposite of `@NonNull` is `@Nullable`, the _absence_ of `@DefaultNonNull` must mean that `@Nullable` is the default".  I'll admit I find that to be an unlikely line of thinking in this case (because absence doesn't imply opposite in my mind). Moreover, regardless of what name we choose for annotating "in the club" code, I find myself believing that most people will intuit that in the absence of an explicit default annotation, the legacy rules they've been used to in Java for decades will apply.

(I suppose the last sentence is a point in favor of expressing "out of the club" with `@InTheClub(false)`, since people may more easily interpret that as going back to the default-default than a separate `@OutOfTheClub`, depending on the concrete name.)

**Comment by kevin1e100** [comment]
Apologies, I did mean to say that the "default-default must be `@Nullable` derivation appears possible for someone to make.  I don't find it likely but the point is that intuition can be different for different people.

**Comment by cpovirk** [comment]
I do think that "default is `@Nullable`" is an assumption that some people will make. My impression is that some people conceptualize the legacy Java rules as "everything is `@Nullable`." And certainly many systems (e.g., Checker Framework) have a binary view of nullness.

One of our challenges may be to emphasize to users that there is a third option, "unspecified nullness." This is of course what Kotlin has done with platform types.

In a small way, I think that the name `@DefaultNonNull` works against that: I wouldn't say that Kotlin is different from Java because Kotlin "defaults to non-null"; I would say that Kotlin is different because it "includes nullness in the type system _at all_."

(And sorry, I didn't intend anything I wrote as an argument for `@InTheClub(false)`. If anyone wants to read more on that, see #109.)

**Comment by cpovirk** [comment]
And sorry, I missed your followup.

It may depend in large part on how familiar the users are with Kotlin.

**Comment by kevinb9n** [comment]
This is not exactly a data point, but when I was playing at drafting a user guide chapter, I draft-titled the document "Writing null-aware code with jspecify", and the chapter, "Interacting with null-unaware code". So, to me, the adjective seemed to "work".

**Comment by kevinb9n** [comment]
In fact, I might like centering on "awareness" enough to even consider dropping the "unspecified" terminology for it completely. Potentially a single `@NullUnaware` could serve as both the cascading-default annotation and the (if needed) type annotation?

**Comment by cpovirk** [comment]
I think that a single annotation that plays double duty is likely to be confusing:

```java
@NullAware
interface Foo {
  @NullUnaware String bar(String p);
}
```

Is `p` specified to be non-nullable, or is its nullness unspecified? It depends on whether `@NullUnaware` is treated as a method annotation or a type annotation in this case.

**Comment by cpovirk** [comment]
Working decision: `@NullMarked`.
