### ISSUE TITLE
Annotating type parameters and type variables in context of `@DefaultNonNull`

### ISSUE THREAD

**Issue by kevin1e100** [jspecify/jspecify#90]
Trying to split this off issue #45.  Note this is different from issue #12 which is about `<T>`, ie., when type parameters are *not* annotated.

Leaving the question of defaults aside it seems clear that there is a need to be able to specify/modify the type arguments that can parameterize a given type parameter.  In particular, assuming we don't have lower bounds, some type parameters should only allow `@NonNull` types, and others should allow `@NonNull` or `@Nullable`.  Handling `@NonNull` and `@Nullable` (as type parameter bound or type argument nullability) is largely obvious, seemingly, though there is debate in issue #45 on what to do with type use annotations on type variable usages.

`@NullnessUnspecified` creates severe complications though:

* How to handle `<@NullnessUnspecified String>` type arguments?  Should they be allowed?
* What would it mean to bound a type parameter explicitly with `@NullnessUnspecified`?  Should that even be allowed?

My hope is that issue #89 will point a way forward for this issue, but I may be wrong.

**Comment by kevinb9n** [comment]
It's been an eventful 18 months since the last comment here. Can anyone (@kevin1e100, @cpovirk?) provide the modern (and as brief as possible!) synopsis of what has been solved and what is left to be solved, here?

**Comment by cpovirk** [comment]
I think the mapping between problems and GitHub issues is many-to-many, as usual... :)

I'm going to optimistically declare that this particular issue does not serve much purpose until we have more annotations than just `@NullMarked` and `@Nullable`: To the extent there is disagreement over what it means to use or not use `@Nullable` within the scope of `@NullMarked`, that's better handled by the discussions about those annotations, rather than on a thread that brings `@NullnessUnspecified` and `@NonNull` into the mix.

Maybe we close this and link it from [Whether to include a type annotation for "unspecified nullness" (#137)](https://github.com/jspecify/jspecify/issues/137) as something to consider if we find ourselves thinking more about that?

**Comment by netdpb** [comment]
I think we can say that it is not necessary to think about this issue until we decide to move forward with #137. So I'll close this issue for now.
