### ISSUE TITLE
Handling of type-use annotations on type variables

### ISSUE THREAD

**Issue by kevin1e100** [jspecify/jspecify#91]
Issue #45 brought up the idea of sometimes "ignoring" type-use annotations on type variables, or more precisely, union-ing them with other factors when parameterizing generic classes (which effectively means only `@Nullable` will be fully honored).  This affects issues #45, #89, and #90, so trying to split this question out.

**Comment by kevinb9n** [comment]
@cpovirk could you perhaps see whether there's some current action/decision we need to salvage from this historical discussion, and file that if so, and close this either way?

Note that we can assume there will be no `@NonNull`, i.e., if we do reintroduce that it will be clear we have to resurrect various closed topics _then_ but short of that don't worry about it.

**Comment by cpovirk** [comment]
This should be pretty well [covered](https://jspecify.dev/spec) (incidentally, even including the groundwork for `@Nonnull`).

For our current annotations, you can basically view it as the "unioning" approach discussed above, or you can view it as "what Kotlin does." If we introduce `@Nonnull` (or if you do something particularly unusual today), then some non-"unioning" behaviors can arise, again following what Kotlin does.

**Comment by cpovirk** [comment]
In an ideal world, I'd find some time to think about https://github.com/jspecify/jspecify/issues/91#issuecomment-581580007 again: _If_ I recall correctly, the "special consideration" for non-nullable type parameters (also [previously discussed here](https://github.com/jspecify/jspecify/issues/158#issue-756650991)):
- complicates our reference checker's implementation
- doesn't match Kotlin (though even if it doesn't match now, we should check again after [KT-59138](https://youtrack.jetbrains.com/issue/KT-59138)). (But note that there is no exact equivalent to this in pure Kotlin code: You need to involve Java code in order to produce the out-of-bounds type argument. So I don't know how deeply the Kotlin folks felt they needed to think about this.)

On the other hand, I suspect that the "special consideration" catches some bugs. (I would like to have a more compelling example handy, but as an existence proof, it catches the bug in code that calls [`or(null)`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/base/Optional.html#or(T)) on a Guava `Optional<String>` even when that type is unannotated. Perhaps a better example would involve `ConcurrentMap` or something.) And I don't _think_ that there's been much argument that that's an overreach (in contrast to, say, #248).

Now _maybe_ there's a way to produce the same effect without hooking into substitution specifically. Like, maybe usages of `T` can be automatically treated like `@NonNull T` when appropriate. But that scares me because it's easy to imagine that a checker might enter infinite recursion if it naively tries to evaluate the nullness of `T` in `class Foo<T extends Foo<T>>`.

One worry would be that, without this "special consideration," it would technically become useful to write the "redundant" "`@NonNull T`" in place of plain "`T`" in order to catch bugs like the one discussed above.

In practice, probably most of the danger here comes from cases in which the type argument is _unspecified_, rather than nullable or parametric (since nullable or parametric would have already produced an error at the site of `Optional<@Nullable Foo>` or `Optional<T>`—unless those declarations came from unchecked code!). That at least means that it's clear that tools could choose to add their own rules to turn "unspecified" back into "non-nullable," especially if the only significant downside to doing so is checker complexity. (Contrast that to a rule that would change "nullable" to "non-nullable," which makes a lot of sense for something like dataflow but makes less sense when you're changing the parameter type of a public API to be more restrictive.)

(I do think that there may also have been an argument that it's nice to have the escape hatch of being able to write `Foo<@Nullable String>` (and get nullable types as a result) if you think that `Foo` bans nullable type arguments _wrongly_. However, I don't see that as a very strong argument, given that it's a workaround that works only for generic APIs. If we think that people need a workaround, then they'll need a workaround for non-generic APIs, too. (Typically that workaround is provided by suppression.))

**Comment by cpovirk** [comment]
There are some similarities here to other cases in which we've argued that non-null types are "special":
- They're the kind that make a guarantee (one that can even be enforced at runtime).
- They may someday sometimes be stored differently, thanks to Valhalla.

But I'm not sure if any such arguments are exceptionally strong in this particular case: If an API is generic, then I don't have a feel for what Valhalla might be able to do in the future. But it's not obvious to me that parameters and return values could be "flattened" in the way that fields can, at least until the type is specialized.

I still like the idea of catching bugs, like in the cases of `Optional` or `ConcurrentMap` above (or AutoValue, which automatically inserts null checks even for generic types by default). And I still like the idea that the type remains non-nullable no matter what you try to substitute in. My question is just whether our special consideration complicates implementation enough that we'd at least not choose to _specify_ it, even if we'd encourage it. If we were going to change our tune, then the time to do so would be before "spec 1.0" and [while we're getting back to our conformance tests](https://github.com/jspecify/jspecify/issues/248#issuecomment-2008031089).

(But I'd have to actually look more at our reference checker to see how large the complication is. It might be only #248 that really mucks things up.)
